### ISSUE TITLE
str_match incompatibility

### ISSUE THREAD

**Issue by hadley** [gagolews/stringi#129]
https://github.com/renozao/NMF/issues/24#issuecomment-65894197

`stri_match` returns NA for optional groups that didn't match, where `str_match` should return `""`. Could we please have an `omit_na` option for stringr?

```
# dev stringr
> str_match("abcd", "^(:)?([^:]*)(:)?$")
     [,1]   [,2] [,3]   [,4]
[1,] "abcd" NA   "abcd" NA  
> str_match(":abcd", "^(:)?([^:]*)(:)?$")
     [,1]    [,2] [,3]   [,4]
[1,] ":abcd" ":"  "abcd" NA  

# CRAN stringr
> str_match("abcd", "^(:)?([^:]*)(:)?$")
     [,1]   [,2] [,3]   [,4]
[1,] "abcd" ""   "abcd" ""  
> str_match(":abcd", "^(:)?([^:]*)(:)?$")
     [,1]    [,2] [,3]   [,4]
[1,] ":abcd" ":"  "abcd" ""  
```

**Comment by hadley** [comment]
This is a blocker for stringr 1.0.0. Are you planning on releasing a new version of stringi soon?

**Comment by hadley** [comment]
Oh no, I need to use the new argument. Oops!

**Comment by gagolews** [comment]
The only new thing in upcoming stringi 0.5 that slightly affects stringr is #133, #139 (text wrap) 
Release time of stringi_0.5 == I wish soon, but I'm stuck with other duties right now :/
