### ISSUE TITLE
Named capture groups support

### ISSUE THREAD

**Issue by gagolews** [gagolews/stringi#153]
Since ICU 55.1, see [Ticket 5312](https://unicode-org.atlassian.net/browse/ICU-5312), we have an experimental support for named capture groups in regexes.

As of ICU 55.1 this is still marked as DRAFT API, hence we may not rely on it yet.

Waiting for becoming STABLE then. In such circumstances:
- [ ]  `stri_match` should be updated (PROBLEM: in ICU 55.1 there is no way to get all names of NCG,
  see [Ticket 11661](https://unicode-org.atlassian.net/browse/ICU-11661))
- [ ] package documentation should be updated
- [ ] stringi should be shipped with the latest ICU
- [ ] the latest ICU must be used as MinimalRequirements in `autoconf` and `DESCRIPTION`

Anyway, named capture groups may be backreferenced and referred to in replacement operations now (if ICU 55.1 is used)

```
> stri_replace_all_regex("aba acd ede", "(?<test>(?<letter>[a-z])[a-z]\\k<letter>)", "!!!${test}!!!${letter}!!!")
[1] "!!!aba!!!a!!! acd !!!ede!!!e!!!"
> stri_replace_all_regex("aba acd ede", "(?<test>(?<letter>[a-z])[a-z]\\k<letter>)", "!!!$1!!!$2!!!")
[1] "!!!aba!!!a!!! acd !!!ede!!!e!!!"
```

**Comment by bramtayl** [comment]
The code above isn't working for me. I get the error:
Error in stri_replace_all_regex("a", "?<letter>[a-z]", "${letter}") : 
  Syntax error in regexp pattern. (U_REGEX_RULE_SYNTAX)

But I'm fairly certain I have ICU 55.1 . When installing, I get:
checking with pkg-config for ICU4C installed... 52.1
checking for ICU4C >= 50... yes

**Comment by ProfFancyPants** [comment]
Is this issue related to the addition of ["If-Then-Else Conditionals"](http://www.regular-expressions.info/conditional.html)? That is, if the named conditionals feature is added, will If-then-else feature go with it? I ask, because I don't see an issue for explicitly adding if-then-else, and my current version doesn't support it.

**Comment by gagolews** [comment]
This is an ICU-related issue. Try filing a feature request at http://bugs.icu-project.org/trac/.

**Comment by ProfFancyPants** [comment]
There seems to already be a feature request at [Ticket #2907 (accepted enhancement)](http://bugs.icu-project.org/trac/ticket/2907).  The last modification was 3 years ago "Status changed from new to accepted". Does this mean the if-else-then feature already has been implemented within ICU? If so, should I try to help integrate it into stringi?

**Comment by gagolews** [comment]
The status is also UNSCH == Unscheduled. A polite comment regarding this feature @ ICU tracker is recommended, IMO.

**Comment by hadley** [comment]
It appears to be documented in http://userguide.icu-project.org/strings/regexp — does that mean it is now stable?

**Comment by gagolews** [comment]
Yes, it is, but with ICU >= 57 (as far as I remember). The most recent version of stringi is shipped with ICU 61

**Comment by gagolews** [comment]
But still it's not possible to set dimnames for the result of stri_match (there's no support for extracting group names from regexes)

**Comment by angelozehr** [comment]
Any updates on this? With stringi v1.4.3 I'm able to match e.g.

`stri_match("asdf 2017 asdf", regex = "(?<year>\\d{4})")`

But the result does not contain "year". It's just a matrix `"2017" "2017"`.
This does not work either:

`stri_replace("asdf 2017 asdf", regex = "(?<year>\\d{4})", "\\k<year>")`

It returns `"asdf k<year> asdf"`

**Comment by gagolews** [comment]
Nope, still not implemented in ICU.

**Comment by tdhock** [comment]
For those who want to write group names as R argument names (rather than inside the regex string literal), you can use https://github.com/tdhock/nc which supports ICU. The example above from @angelozehr becomes:
```
> str(nc::capture_first_vec("asdf 2017 asdf", year="\\d{4}", as.integer, engine="ICU"))
Classes ‘data.table’ and 'data.frame':	1 obs. of  1 variable:
 $ year: int 2017
 - attr(*, ".internal.selfref")=<externalptr> 
```

**Comment by randy3k** [comment]
The link of the above ticket 11661 is broken, it is now https://unicode-org.atlassian.net/browse/ICU-11661

**Comment by gagolews** [comment]
Done, I've finally implemented it myself.

```r
stri_match_all_regex(c('breakfast=eggs;lunch=pizza',
   'breakfast=bacon;lunch=spaghetti', 'no food here'),
   '(?<when>\\w+)=(?<what>\\w+)')  # named capture groups
## [[1]]
##                       when        what   
## [1,] "breakfast=eggs" "breakfast" "eggs" 
## [2,] "lunch=pizza"    "lunch"     "pizza"
## 
## [[2]]
##                        when        what       
## [1,] "breakfast=bacon" "breakfast" "bacon"    
## [2,] "lunch=spaghetti" "lunch"     "spaghetti"
## 
## [[3]]
##         when what
## [1,] NA NA   NA
```
