### ISSUE TITLE
feature request: Support use of connections with stri_read_raw/stri_read_lines

### ISSUE THREAD

**Issue by richierocks** [gagolews/stringi#187]
Most base R file import functions accept either a string to a file path or a connection object.

`stri_read_raw` currently only allows the `fname` argument to be a string.  The line that prevents the use of connections is:

```
stopifnot(is.character(fname), length(fname) == 1, file.exists(fname))
```

Since the function is based on `readBin`, which accepts file connections, you could do something like

``` r
stri_read_raw <- function (fname) 
{
    UseMethod("stri_read_raw")
}
stri_read_raw.file <- function (fname) 
{
    summary_of_conn <- summary(fname)
    file_path <- summary_of_conn$description
    # Consider using assertive.files to make this prettier.
    # https://bitbucket.org/richierocks/assertive.files
    stopifnot(
      file.exists(file_path), 
      summary_of_conn$`can read` == "yes", 
      summary_of_conn$text == "binary"
    )
    fsize <- file.info(file_path)$size
    readBin(fname, what = "raw", size = 1, n = fsize)
}
stri_read_raw.character <- function (fname) 
{
    stopifnot(length(fname) == 1, file.exists(fname))
    fsize <- file.info(fname)$size
    readBin(fname, what = "raw", size = 1, n = fsize)
}
```

I've not submitted this as a pull request because it still needs a little thinking about.  For example, it makes sense that you should be able to pass a file connection in "r" mode (i.e. reading as text not binary) to `stri_read_lines`, but `readBin` only accepts binary connections.

**Comment by gagolews** [comment]
OK, I'm gonna inspect that in more detail as soon as I find time for that

**Comment by gagolews** [comment]
I have found time for this et voilà. Done.
