### ISSUE TITLE
Ability to "un-vectorise" stri_enc_detect

### ISSUE THREAD

**Issue by hadley** [gagolews/stringi#190]
Often you have a vector of lines, and you'd like to be able to detect their encoding en-masse (I think that's actually more common than the case where you want to detect encoding separately for each element of the character vector)

**Comment by gagolews** [comment]
right

**Comment by gagolews** [comment]
I mentioned that in the documentation (that flattening the string vector can be a good idea in such a case). I still recommend reading data in raw (binary) mode first (`stri_read_raw` is now much smarter and accepts any connection objects), and performing encoding detection prior to conversion and splitting into text lines.

So I will leave the function's API as-is, for consistency.

**Comment by hadley** [comment]
Makes sense, thanks!
