### ISSUE TITLE
Update ICU >= 59

### ISSUE THREAD

**Issue by gagolews** [gagolews/stringi#193]
New features in ICU 56:
- ICU data size reduced by about 7.2%
- StringSearch (based on collation) defaults to matches on normalization boundaries rather than grapheme cluster boundaries

Already not dependent on:
- Most of the old Normalizer/unorm.h had been replaced by (and reimplemented via) Normalizer2, and is now deprecated

Already in stringi doc:
- New FilteredBreakIterator suppresses certain segment boundaries. For example, it can suppress the sentence boundary in the middle of "Mr. Smith".
- For [U]BreakIterator with type UBRK_SENTENCE, the locale key "ss" can now be used with value "standard" to specify that standard sentence break suppression data should be used, or with value "none" to indicate that no break suppression data should be used (the default).

New features in ICU 57:
* Fixed #147 - incorrect behavior of regex look-behinds

New features in ICU 58:
*  --

New features in ICU 59:
* better emoji support

New features in ICU 60:
* Unicode 10.0: 8,518 new characters, including four new scripts, 7,494 new Han characters, and 56 new emoji characters.

New features in ICU 61:
* --

**Comment by gagolews** [comment]
2016-05-18: The Unicode® Consortium has announced that it will host development of the ICU libraries. -- this perhaps may imply changes in the license

**Comment by krlmlr** [comment]
Somewhat related: Would you consider splitting the ICU library to a separate package? This would separate stringi updates from ICU updates, and also allow using ICU in RSQLite (rstats-db/RSQLite#167).

**Comment by gagolews** [comment]
Wanna help?

**Comment by krlmlr** [comment]
If I add ICU support to SQLite, that's the route I'd take. Of course, I wouldn't mind if at that point a separate ICU library package already existed ;-)

**Comment by gagolews** [comment]
@krlmlr And,yeah, sure, I considered that some time ago.
There were also ideas to put icudt in a separate pkg.
But I don't have time for that right now.
and `stringi` is kinda *sensitive* right now, too many pkgs depend on it (directly or indirectly) - so careful moves only

**Comment by gagolews** [comment]
Update to ICU 59 needs C++11. Solaris can stay ICU55. Need both icudt55 and icudt59 + separate sources
