### ISSUE TITLE
Escape a regular expression

### ISSUE THREAD

**Issue by hadley** [gagolews/stringi#200]
Sometimes it's useful be able to escape a regular expression so it behaves like the equivalent fixed match, i.e.:

``` R
colours <- c("red", "orange", "yellow", "green", "blue", "purple")
str_c(colours, collapse = "|")
```

That regular expression is safe for this input text (because it doesn't contain any metacharacters), but it's not in general.

**Comment by gagolews** [comment]
NOTE:

http://userguide.icu-project.org/strings/regexp:

\ 	 ✓ 	  	Quotes the following character. Characters that must be quoted to be treated as literals are * ? + [ ( ) { } ^ $ | \ .

\ 	  	 ✓ 	Quotes the following character. Characters that must be quoted to be treated as literals are [ ] \
Characters that may need to be quoted, depending on the context are - &

**Comment by gagolews** [comment]
I guess this is out of stringi's scope now.
