### ISSUE TITLE
configure.ac not included in distribution

### ISSUE THREAD

**Issue by pooryorick** [gagolews/stringi#205]
It would be much easier to customize the configure script as needed if configure.ac were included in the distribution.

**Comment by gagolews** [comment]
Well, It's right here, on  github. I don't add it to the tar.gz on CRAN as the CRAN team doesn't like "auxiliary" files, AFAIK.

**Comment by gagolews** [comment]
The policy has changed now

From BR:

> This concerns packages [...] stringi [...] which are not complying with the CRAN policy

> 'Source packages under an Open Source license must provide source or something which can easily be converted back to source (e.g., .rda files) for all components of the package (including for example PDF documentation, configure files produced by autoconf).'

> The absence of source components such as configure.ac makes it almost impossible for anyone else to correct the package, as we recently found for an abandoned package.
