### ISSUE TITLE
version 1.1 fails to build solely from local sources

### ISSUE THREAD

**Issue by sz-cgt** [gagolews/stringi#221]
Building `stringi` on a box without internet connectivity fails because `src/install.libs.R.in` doesn't realize `stringi` was built using the included copy of icu55

**Comment by gagolews** [comment]
This is true, see https://cran.r-project.org/web/packages/stringi/INSTALL and https://stackoverflow.com/questions/27553452/how-to-install-stringi-library-from-archive-and-install-the-local-icu52l-zip
