### ISSUE TITLE
Unable to install stringi package for R 3.3.1 on OSX El Capitan

### ISSUE THREAD

**Issue by bdanalytics** [gagolews/stringi#223]
Am trying to install the R stringi package on Mac OS X El Capitan with a homebrew installation of R in an R console

     > sessionInfo()
     R version 3.3.1 (2016-06-21)
     Platform: x86_64-apple-darwin15.5.0 (64-bit)
     Running under: OS X 10.11.5 (El Capitan)

     locale:
     [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

     attached base packages:
     [1] stats     graphics  grDevices utils     datasets  methods   base     

     loaded via a namespace (and not attached):
     [1] tools_3.3.1

     > install.packages("stringi", configure.vars="ICUDT_DIR=/usr/local/Cellar/icu4c/57.1/")
     Installing package into ‘/usr/local/lib/R/3.3/site-library’
     (as ‘lib’ is unspecified)
     trying URL 'https://cloud.r-project.org/src/contrib/stringi_1.1.1.tar.gz'
     Content type 'application/x-gzip' length 3644397 bytes (3.5 MB)
     ==================================================
     downloaded 3.5 MB

     * installing *source* package ‘stringi’ ...
     ** package ‘stringi’ successfully unpacked and MD5 sums checked
     checking for local ICUDT_DIR... /usr/local/Cellar/icu4c/57.1/
     checking for R_HOME... /usr/local/Cellar/r/3.3.1/R.framework/Resources
     checking for R... /usr/local/Cellar/r/3.3.1/R.framework/Resources/bin/R
     checking for R >= 3.1.0... yes
     checking for cat... /bin/cat
     checking for gcc... clang
     checking whether the C compiler works... yes
     checking for C compiler default output file name... a.out
     checking for suffix of executables... 
     checking whether we are cross compiling... no
     checking for suffix of object files... o
     checking whether we are using the GNU C compiler... yes
     checking whether clang accepts -g... yes
     checking for clang option to accept ISO C89... none needed
     checking how to run the C preprocessor... clang++ -E
     checking for grep that handles long lines and -e... /usr/bin/grep
     checking for egrep... /usr/bin/grep -E
     checking for ANSI C header files... rm: conftest.dSYM: is a directory
     rm: conftest.dSYM: is a directory
     yes
     checking for sys/types.h... yes
     checking for sys/stat.h... yes
     checking for stdlib.h... yes
     checking for string.h... yes
     checking for memory.h... yes
     checking for strings.h... yes
     checking for inttypes.h... yes
     checking for stdint.h... yes
     checking for unistd.h... yes
     checking elf.h usability... no
     checking elf.h presence... no
     checking for elf.h... no
     checking whether we are using the GNU C++ compiler... yes
     checking whether clang++ -std=c++11 accepts -g... yes
     checking whether the C++ compiler supports the long long type... yes
     checking whether the compiler implements namespaces... yes
     checking whether the compiler supports Standard Template Library... yes
     checking whether std::map is available... yes
     checking for pkg-config... /usr/local/bin/pkg-config
     **checking with pkg-config for ICU4C installed... no
     *** The pkg-config script did not detect ICU4C-devel libraries installed
     *** We will build ICU4C from sources**
     checking whether we may compile src/icu55/common/umapfile.c... yes
     checking whether we may compile src/icu55/common/putil.cpp... yes
     configure: creating ./config.status
     config.status: creating src/Makevars
     config.status: creating src/uconfig_local.h
     config.status: creating src/install.libs.R

     *** stringi configure summary:
         ICU_FOUND=0
         ICUDT_DIR=/usr/local/Cellar/icu4c/57.1/
         STRINGI_CXXSTD=CXX_STD=CXX11
         STRINGI_CFLAGS= 
         STRINGI_CPPFLAGS=-I. -Iicu55 -Iicu55/unicode -Iicu55/common -Iicu55/i18n -DU_STATIC_IMPLEMENTATION -DU_COMMON_IMPLEMENTATION -DU_I18N_IMPLEMENTATION           -DUCONFIG_USE_LOCAL  -UDEBUG -DNDEBUG
         STRINGI_CXXFLAGS= 
         STRINGI_LDFLAGS= 
         STRINGI_LIBS= 

     *** compiler settings used:
         CC=clang
         CPP=clang++ -E
         LD=clang++
         CFLAGS=-g -O2 
         CPPFLAGS=-I/usr/local/opt/gettext/include -I/usr/local/opt/readline/include -I/usr/local/opt/openssl/include -I/usr/local/include  -UDEBUG -DNDEBUG
         CXX=clang++ -std=c++11
         CXXFLAGS=-g -O2 
         LDFLAGS= 
         LIBS= 

     ** libs

A bunch of compiles occur & then:
    clang++ -std=c++11 -I/usr/local/Cellar/r/3.3.1/R.framework/Resources/include -DNDEBUG -I/usr/local/include -I/usr/local/opt/ -I/usr/local/opt/icu4c/include -I/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/jre/../include -I/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/jre/../include/darwin  -I/usr/local/opt/gettext/include -I/usr/local/opt/readline/include -I/usr/local/opt/openssl/include -I/usr/local/include    -fPIC  -g -O2 -c icu55/common/icuplug.cpp -o icu55/common/icuplug.o
    **In file included from icu55/common/icuplug.cpp:17:
    icu55/common/icuplugimp.h:75:12: error: unknown type name 'UPlugData'
U_INTERNAL UPlugData* U_EXPORT2**

    fatal error: too many errors emitted, stopping now [-ferror-limit=]
    20 errors generated.
    make: *** [icu55/common/icuplug.o] Error 1
    ERROR: compilation failed for package ‘stringi’

Checked if any other brew packages could / should be installed
    brew install icu4c
    Warning: icu4c-57.1 already installed

    brew install icu4dt
    Error: No available formula with the name "icu4dt" 
    ==> Searching for similarly named formulae...
    Error: No similarly named formulae found.
    ==> Searching taps...
    Error: No formulae found in taps.

Tried installing python polyglot & that seems to work:

    $CFLAGS=-I/usr/local/opt/icu4c/include LDFLAGS=-L/usr/local/opt/icu4c/lib pip install polyglot
    Collecting polyglot
    Requirement already satisfied (use --upgrade to upgrade): futures>=2.1.6 in     /usr/local/lib/python2.7/site-packages (from polyglot)
    Collecting pycld2>=0.3 (from polyglot)
    Requirement already satisfied (use --upgrade to upgrade): six>=1.7.3 in /usr/local/lib/python2.7/site-packages/six-1.10.0-py2.7.egg (from polyglot)
    Requirement already satisfied (use --upgrade to upgrade): wheel>=0.23.0 in /usr/local/lib/python2.7/site-packages (from polyglot)
    Requirement already satisfied (use --upgrade to upgrade): numpy>=1.6.1 in /usr/local/lib/python2.7/site-packages (from polyglot)
    Collecting morfessor>=2.0.2a1 (from polyglot)
    Collecting PyICU>=1.8 (from polyglot)
      Using cached PyICU-1.9.3.tar.gz
    Building wheels for collected packages: PyICU
      Running setup.py bdist_wheel for PyICU ... done
      Stored in directory: /Users/bbalaji-2012/Library/Caches/pip/wheels/c7/65/7e/955deab7c07708865ef4625cb4387e0672c5828e4137ce5987
    Successfully built PyICU
    Installing collected packages: pycld2, morfessor, PyICU, polyglot
    Successfully installed PyICU-1.9.3 morfessor-2.0.2a3 polyglot-16.7.4 pycld2-0.31

Tried  install.packages("stringi", configure.vars="ICUDT_DIR=/usr/local/Cellar/icu4c/57.1/lib") : Adding lib at the end of ICUDT_DIR and obtained the same crash results. 

Any suggestions ? Thanks in advance

**Comment by gagolews** [comment]
"with a homebrew installation of R" --- well... 

why don't you try with the "stock" icu (shipped with string), i.e., without `configure.vars="ICUDT_DIR=/usr/local/Cellar/icu4c/57.1/"`

**Comment by bdanalytics** [comment]
Tried that first a long time ago ...; crashes at exactly the same point:

    In file included from icu55/common/icuplug.cpp:17:
    icu55/common/icuplugimp.h:75:12: error: unknown type name 'UPlugData'
    U_INTERNAL UPlugData* U_EXPORT2

    In install.packages("stringi") :
      installation of package ‘stringi’ had non-zero exit status

Is pkg-config the culprit ? For some reason it does not return the recognized icu4c-devel libraries ?

    *** The pkg-config script did not detect ICU4C-devel libraries installed
    *** We will build ICU4C from sources

    lla /usr/local/Cellar/icu4c/57.1/lib
    total 123456
    drwxr-xr-x  36 <usrid>  admin      1224 Mar 23 17:14 ./
    drwxr-xr-x  11 <usrid>  admin       374 May 31 21:06 ../
    drwxr-xr-x   6 <usrid>  admin       204 Mar 23 17:14 icu/
    -r--r--r--   1 <usrid>  admin  25673824 May 31 21:06 libicudata.57.1.dylib
    lrwxr-xr-x   1 <usrid>  admin        21 Mar 23 17:14 libicudata.57.dylib@ -> libicudata.57.1.dylib
    -r--r--r--   1 <usrid>  admin  25669832 Mar 23 17:14 libicudata.a
    lrwxr-xr-x   1 <usrid>  admin        21 Mar 23 17:14 libicudata.dylib@ -> libicudata.57.1.dylib
    -r--r--r--   1 <usrid>  admin   2320400 May 31 21:06 libicui18n.57.1.dylib
    lrwxr-xr-x   1 <usrid>  admin        21 Mar 23 17:14 libicui18n.57.dylib@ -> libicui18n.57.1.dylib
    -r--r--r--   1 <usrid>  admin   4015784 Mar 23 17:14 libicui18n.a
    lrwxr-xr-x   1 <usrid>  admin        21 Mar 23 17:14 libicui18n.dylib@ -> libicui18n.57.1.dylib
    -r--r--r--   1 <usrid>  admin     58344 May 31 21:06 libicuio.57.1.dylib
    lrwxr-xr-x   1 <usrid>  admin        19 Mar 23 17:14 libicuio.57.dylib@ -> libicuio.57.1.dylib
    -r--r--r--   1 <usrid>  admin     65888 Mar 23 17:14 libicuio.a
    lrwxr-xr-x   1 <usrid>  admin        19 Mar 23 17:14 libicuio.dylib@ -> libicuio.57.1.dylib
    -r--r--r--   1 <usrid>  admin    301232 May 31 21:06 libicule.57.1.dylib
    lrwxr-xr-x   1 <usrid>  admin        19 Mar 23 17:14 libicule.57.dylib@ -> libicule.57.1.dylib
    -r--r--r--   1 <usrid>  admin    575192 Mar 23 17:14 libicule.a
    lrwxr-xr-x   1 <usrid>  admin        19 Mar 23 17:14 libicule.dylib@ -> libicule.57.1.dylib
    -r--r--r--   1 <usrid>  admin     46384 May 31 21:06 libiculx.57.1.dylib
    lrwxr-xr-x   1 <usrid>  admin        19 Mar 23 17:14 libiculx.57.dylib@ -> libiculx.57.1.dylib
    -r--r--r--   1 <usrid>  admin     59904 Mar 23 17:14 libiculx.a
    lrwxr-xr-x   1 <usrid>  admin        19 Mar 23 17:14 libiculx.dylib@ -> libiculx.57.1.dylib
    -r--r--r--   1 <usrid>  admin     65836 May 31 21:06 libicutest.57.1.dylib
    lrwxr-xr-x   1 <usrid>  admin        21 Mar 23 17:14 libicutest.57.dylib@ -> libicutest.57.1.dylib
    -r--r--r--   1 <usrid>  admin     76408 Mar 23 17:14 libicutest.a
    lrwxr-xr-x   1 <usrid>  admin        21 Mar 23 17:14 libicutest.dylib@ -> libicutest.57.1.dylib
    -r--r--r--   1 <usrid>  admin    178976 May 31 21:06 libicutu.57.1.dylib
    lrwxr-xr-x   1 <usrid>  admin        19 Mar 23 17:14 libicutu.57.dylib@ -> libicutu.57.1.dylib
    -r--r--r--   1 <usrid>  admin    237112 Mar 23 17:14 libicutu.a
    lrwxr-xr-x   1 <usrid>  admin        19 Mar 23 17:14 libicutu.dylib@ -> libicutu.57.1.dylib
    -r--r--r--   1 <usrid>  admin   1466884 May 31 21:06 libicuuc.57.1.dylib
    lrwxr-xr-x   1 <usrid>  admin        19 Mar 23 17:14 libicuuc.57.dylib@ -> libicuuc.57.1.dylib
    -r--r--r--   1 <usrid>  admin   2289944 Mar 23 17:14 libicuuc.a
    lrwxr-xr-x   1 <usrid>  admin        19 Mar 23 17:14 libicuuc.dylib@ -> libicuuc.57.1.dylib
    drwxr-xr-x   7 <usrid>  admin       238 May 31 21:06 pkgconfig/

    lla /usr/local/Cellar/icu4c/57.1/lib/pkgconfig
    total 40
    drwxr-xr-x   7 <usrid>  admin   238 May 31 21:06 ./
    drwxr-xr-x  36 <usrid>  admin  1224 Mar 23 17:14 ../
    -r--r--r--   1 <usrid>  admin  1148 May 31 21:06 icu-i18n.pc
    -r--r--r--   1 <usrid>  admin  1140 May 31 21:06 icu-io.pc
    -r--r--r--   1 <usrid>  admin  1130 May 31 21:06 icu-le.pc
    -r--r--r--   1 <usrid>  admin  1141 May 31 21:06 icu-lx.pc
    -r--r--r--   1 <usrid>  admin  1172 May 31 21:06 icu-uc.pc

Thanks a lot for your help

**Comment by gagolews** [comment]
Try playing with the compiler flags.

**Comment by bdanalytics** [comment]
As i suspected, pkg-config was the culprit !!! 
/usr/local/opt/icu4c/lib/pkgconfig was not in the paths that pkg-config was checking for the icu4c-devel libraries. Thus the following line in bash shell did the trick:

    export PKG_CONFIG_PATH="/usr/local/opt/icu4c/lib/pkgconfig"

After that a standard install.packages("stringi") in R console installed version 1.1.1

Would it be useful to add this environment variable to the R install.packages configure.vars documentation ?

**Comment by gagolews** [comment]
I already got that explained in `configure` as well as `INSTALL`. Anyway, I'm happy that you found the solution .


```
$ ./configure --help
`configure' configures stringi 1.1 to adapt to many kinds of systems.

Usage: ./configure [OPTION]... [VAR=VALUE]...

[...]

  PKG_CONFIG_PATH
              An optional list of directories to search for pkg-config's .pc
              files.
```

```
$ cat INSTALL 
                            Installing stringi
================================================================================

.......
Some influential environment variables:

* `ICUDT_DIR`: Optional directory from which an already downloaded ICU data
  archive (`icudt*.zip`) may be copied; either an absolute path or a
  path relative to `<package source dir>/src`; defaults to `icu55/data`.
* `PKG_CONFIG_PATH`: An optional list of directories to search for
  `pkg-config`s `.pc` files.
* `R_HOME`: Override default directory with R installation, e.g.,
  `/usr/lib64/R`. Note that `$R_HOME/bin/R` should point to the R executable.
* `CAT`: The `cat` command used for generating the list of source files
  to compile.
```
