### ISSUE TITLE
Non-capturing groups are returned

### ISSUE THREAD

**Issue by nacnudus** [gagolews/stringi#224]
``` {.r}
stri_extract_all("ABB", regex = "(?:A)B")
#> [[1]]
#> [1] "AB"
```

I expected it to return only "B".

**Comment by gagolews** [comment]
Non-capturing groups basically affect the results of `stri_match`, not `stri_extract` - this is a feature common to most of the regex engines.
Perhaps here you meant look aheads/behinds, see http://userguide.icu-project.org/strings/regexp
