### ISSUE TITLE
Installation on cluster

### ISSUE THREAD

**Issue by dajmcdon** [gagolews/stringi#225]
Hi,

I'm trying to install 'stringi' on a high performance cluster (I do not have root access). However, I continue to get the following error:

icudt has been found in a local repo
icudt fetch OK
decompressing downloaded archive
icudt has been installed successfully
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/path/to/dir/x86_64-unknown-linux-gnu-library/3.1/stringi/libs/stringi.so':
  /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /path/to/dir/R/x86_64-unknown-linux-gnu-library/3.1/stringi/libs/stringi.so)
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/path/to/dir/R/x86_64-unknown-linux-gnu-library/3.1/stringi’

After talking with one of the support people, the issue seems to be that CXXABI_1.3.8 is not in the /usr/lib64/ version of libstdc++, but it is installed on the cluster (another copy of libstdc++ in a different directory). Is there a way to point R to the correct place at this point? Something in the Makevars file perhaps? 

I'm running:
R version 3.1.1 (2014-07-10) -- "Sock it to Me"
Copyright (C) 2014 The R Foundation for Statistical Computing
Platform: x86_64-unknown-linux-gnu (64-bit)

Please let me know if there is any other information I can provide.

Thanks.

**Comment by gagolews** [comment]
Stackoverflow provides plethora of answers to that, see, e.g.,http://stackoverflow.com/questions/21333097/got-message-unable-to-load-shared-object-stats-so-when-r-starts

If I were you, I'd start with playing with `LD_LIBRARY_PATH` and `ldd`
