### ISSUE TITLE
Compile fails on R-devel

### ISSUE THREAD

**Issue by elbamos** [gagolews/stringi#228]
```
/usr/bin/ld: stri_brkiter.o: relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
stri_brkiter.o: could not read symbols: Bad value
collect2: error: ld returned 1 exit status
make: *** [stringi.so] Error 1
ERROR: compilation failed for package ‘stringi’
```

If you'd like to see the whole build:  https://travis-ci.org/elbamos/largeVis/jobs/158622690

**Comment by gagolews** [comment]
Clearly, your compiler flags are ill-configured. As the error msg suggests:

```
recompile with -fPIC
```

Try playing with the `CXXFLAGS` environmental variable
or check out https://cran.r-project.org/web/packages/stringi/INSTALL for info on how to pass `-fPIC` while installing stringi.

And BTW, in https://github.com/elbamos/largeVis/blob/master/.travis.yml you set custom build-specific env vars anyway

HTH

**Comment by elbamos** [comment]
@gagolews The compiler flags are the default for that installation of R.  

I'm sure I can find a way to pass `-fPIC` to the linker.  But, is it really intentional that `stringi` should not compile properly out-of-box on current `R-devel`?  It does compile properly out-of-box on current `R-release`, and it seems to me that this issue with `R-devel` is quite recent, in the last few weeks.

**Comment by gagolews** [comment]
OK, it's a R-devel, but I some maintainer set up those custom compiler flags manually (just like I often do on my own computer).

Anyway, thanks for this notification, I'll be monitoring this situation.

**Comment by gagolews** [comment]
BTW, this docker image runs on Ubuntu, try installing the `libicu-dev` package and see if it helps.

@note: https://cran.r-project.org/web/checks/check_results_stringi.html - r-devel build ok

**Comment by gagolews** [comment]
@elbamos , could you pls check if now your build succeeds?

**Comment by elbamos** [comment]
I just kicked it off:  https://github.com/elbamos/largeVis/tree/hotfix/travis

Is there a way you can link the travis results from that branch here?

**Comment by elbamos** [comment]
So the issue is unresolved.

**Comment by gagolews** [comment]
you should build against the devel branch of stringi

pls try instead of:

```
r_packages:
- stringi
```

using:

```
r_github_packages
   - stringi
```

**Comment by elbamos** [comment]
Ok I kicked it off again.
