### ISSUE TITLE
add local mirror for installing icudt not working for stringi 1.1.1 (ref #141)

### ISSUE THREAD

**Issue by bruceredmon** [gagolews/stringi#229]
\> install.packages("/tmp/RtmphNqmsh/downloaded_packages/stringi_1.1.1.tar.gz",configure.vars="ICUDT_DIR=/tmp/icudt55l.zip")

Installing package into ‘/usr/lib64/R/library’
(as ‘lib’ is unspecified)
inferring 'repos = NULL' from 'pkgs'
\* installing *source* package ‘stringi’ ...
\** package ‘stringi’ successfully unpacked and MD5 sums checked
checking for local ICUDT_DIR... /tmp/icudt55l.zip
checking for R_HOME... /usr/lib64/R
checking for R... /usr/lib64/R/bin/R
...
installing via 'install.libs.R' to /usr/lib64/R/library/stringi
downloading ICU data library (icudt)
the files will be extracted to: /usr/lib64/R/library/stringi/libs
no icudt in a local repo
trying URL 'http://static.rexamine.com/packages/icudt55l.zip'
Warning in download.file(paste(href, fname, sep = ""), outfname, mode = "wb") :
  unable to connect to 'static.rexamine.com' on port 80.
Error in download.file(paste(href, fname, sep = ""), outfname, mode = "wb"): cannot open URL 'http://static.rexamine.com/packages/icudt55l.zip'

trying URL 'http://www.mini.pw.edu.pl/~gagolews/stringi/icudt55l.zip'
Warning in download.file(paste(href, fname, sep = ""), outfname, mode = "wb") :
  unable to connect to 'www.mini.pw.edu.pl' on port 80.
Error in download.file(paste(href, fname, sep = ""), outfname, mode = "wb"): cannot open URL 'http://www.mini.pw.edu.pl/~gagolews/stringi/icudt55l.zip'

trying URL 'http://www.ibspan.waw.pl/~gagolews/stringi/icudt55l.zip'
Warning in download.file(paste(href, fname, sep = ""), outfname, mode = "wb") :
  unable to connect to 'www.ibspan.waw.pl' on port 80.
Error in download.file(paste(href, fname, sep = ""), outfname, mode = "wb"): cannot open URL 'http://www.ibspan.waw.pl/~gagolews/stringi/icudt55l.zip'

icudt download failed
Error in eval(expr, envir, enclos) : 
  icudt could not be downloaded. check your internet connectivity

**Comment by gagolews** [comment]
`/tmp/icudt55l.zip` does not look like a DIR to me.

**Comment by gagolews** [comment]
see https://raw.githubusercontent.com/gagolews/stringi/master/INSTALL

**Comment by bruceredmon** [comment]
Indeed.  Specifying as a directory works as designed.
