### ISSUE TITLE
Fail fast: download icudt55l.zip *before* building

### ISSUE THREAD

**Issue by jeroenooms** [gagolews/stringi#230]
One of the most common reasons installation fails is because `icudt55l.zip` cannot be downloaded. However this only happens at the very end, which is very frustrating. 

It would be great if the configure script would download the required resources before it starts building, and if this fails, don't even start the build.

**Comment by gagolews** [comment]
That's a nice idea. I can let `./configure` try to download icudt55l.zip first by calling `R`'s `download.file()`. Thanks!

**Comment by gagolews** [comment]
Almost done.
