### ISSUE TITLE
UTF-8-BOM

### ISSUE THREAD

**Issue by antaldaniel** [gagolews/stringi#233]
There is a prevailing issue among Central/Eastern European and some Asian users that they have a hard time working with UTF-8-BOM text.  It is very frequent that various web services, such as Google searches, return text to the user in some of these languages with BOM.  

> Since R 3.0.0 is accepted and read.table / read.csv  etc function can handle this with the fileEncoding = "UTF-8-BOM"  parameter.  [See Hadley's answer:  Read a UTF-8 text file with BOM](http://stackoverflow.com/questions/21624796/read-a-utf-8-text-file-with-bom)

Most of the answers I read here and there were educated guesses which software to use to open a saved file from R or RStudio, resave it and reopen it, which is not a very efficient and reproducible approach, but they are essentially right, because some software on Windows had been long able to work with this problem, such as OpenOffice Calc or Notepad. (The problem is widespread on Windows, but can appear on other OS, too.)

Is there a way to encorporate "UTF-8-BOM) into stri_econde?

**Comment by gagolews** [comment]
All BOMs should be handled correctly by default. Have you checked that and run into any problems?

**Comment by antaldaniel** [comment]
Yes, I'll try to make a reproducible example. The handling of BOM between Windows, R, Rstudio and stringi is a bit above my competence level, but I'll try.

**Comment by gagolews** [comment]
Closing as the discussion hasn't been active for a while.
