### ISSUE TITLE
Clarify locale in stri_opts_regex

### ISSUE THREAD

**Issue by hadley** [gagolews/stringi#235]
When you set `case_insensitive = TRUE` in `stri_opts_regex()`, what locale is used?

**Comment by gagolews** [comment]
The current default one, see `stri_locale_get()`.
However, regex ops in ICU are not very much locale-dependent

**Comment by hadley** [comment]
Is there any way to change the default? It makes me a little worried having an default that will differ from system to system - can you imagine how painful it would be to debug if this was the root cause for why your script worked on your computer, but not someone else's?

**Comment by gagolews** [comment]
Yes, it is `stri_locale_set()`, see `?"stringi-locale"`
Initially, locale is set to be compatible to the one used by your system, e.g., `LC_COLLATE` etc. - just like in `Sys.getlocale()`. And this locale (the one given by `stri_locale_get()` is the default to all the functions.

AFAIK, regex matching in ICU does not depend on the locale settings (why would it)

**Comment by hadley** [comment]
Case insensitive matches?

**Comment by gagolews** [comment]
good point, but ICU regexes are much dumber than `stri_detect_coll`...

**Comment by hadley** [comment]
Do they not use the locale? Maybe I should just test it.

**Comment by gagolews** [comment]
http://icu-project.org/apiref/icu4c/classicu_1_1RegexMatcher.html
http://icu-project.org/apiref/icu4c/classicu_1_1RegexPattern.html
http://icu-project.org/apiref/icu4c/uregex_8h.html

--- none of these mention the term *locale* at all

this is why there is no locale arg in `stri_*_regex`

**Comment by hadley** [comment]
Ok, so do you think it's reasonable to say that the regex engine uses the standard ("C") locale for case insensitive matches?  Is there a better way to refer to the standard case translation algorithm?

**Comment by gagolews** [comment]
I would play with the following prior to matching (in some scenarios):
1. `stri_trans_nfkd`
2. `stri_trans_nfc`
3. `stri_trans_toupper`
for both `pattern` and `searchstr`. Then a case sensitive search could be applied

perhaps `stri_trans_nfkc_casefold` could be worth inspecting too

**Comment by gagolews** [comment]
I would play with the following prior to matching (in some scenarios):

1. `stri_trans_nfkd`
2. `stri_trans_nfc`
3. `stri_trans_toupper`

for both `pattern` and `searchstr`. Then a case sensitive search could be applied

perhaps `stri_trans_nfkc_casefold` could be worth inspecting too

**Comment by hadley** [comment]
Got it - thanks!
