### ISSUE TITLE
Unicode helpers

### ISSUE THREAD

**Issue by hadley** [gagolews/stringi#236]
For teaching/debugging, it would be useful to have helpers to:

* List all the members of a unicode class
* List the properties of a single character

i.e. locally reproduce the effect of pages like <http://www.fileformat.info/info/unicode/category/Pc/list.htm> and <http://www.fileformat.info/info/unicode/char/200d/index.htm>.

**Comment by gagolews** [comment]
Duplicate of #4 and #5 (very old issues, I should resolve them long time ago...)
