### ISSUE TITLE
Fail configuration when suitable version if libicu should be available

### ISSUE THREAD

**Issue by jeroen** [gagolews/stringi#238]
As discussed in Poznan: `stringi` defaults to building the bundled ICU even when a suitable version of ICU might be available from the system. This can lead to unnecessary complications and build time. Often users are simply not aware that the reason things take so long to build is that they forgot to install `libicu-dev`. It would be better if `stringi` prefers the system ICU if available.

I think a better approach would be if `configure` fails and tell the user to install `libicu-dev` on the system. Alternatively the user could force to use the static icu with some configure flag.

Failing configure scripts when dependencies are missing is perfectly acceptable on CRAN. Finding system dependencies is the main purpose of R configure scripts. Other packages that requires system libs (`curl`, `xml2`, `gpg`, `sodium`, `RMySQL`, `openssl` to name a few) also fail configuration if a required library is missing.

How do we know if a suitable version of libicu is available? One way would be to look at

```
ldconfig -p | grep icui18n.so
```

And check if there is a file called `libicui18n.so.55` or `libicui18n.so.56` or so.

**Comment by jeroenooms** [comment]
This should also address https://github.com/gagolews/stringi/issues/220 where stringi can't find ICU if `pkg-config` has not been installed.

**Comment by gagolews** [comment]
I gave it a thought: This might happen some day in the future, but for now (see #231) you may set the `STRINGI_DISABLE_ICU_BUNDLE` (e.g., to `"1"`) in order to force the use of system ICU. That's pretty easy for all the build envs, including Travis CI.
