### ISSUE TITLE
stri_join does not parse € symbol correctly

### ISSUE THREAD

**Issue by dapper2dan** [gagolews/stringi#239]
Title says it all: When using a € symbol within `stri_join` it outputs the unicode code and not the symbol. I tried other symbols (e.g. ¥) and they work fine. So I assume its a bug and not a feature?!

```r
> library(stringi)

> # stri_join parses € symbol to unicode code
> stri_join("42", "€")
[1] "42\u0080"

> # I'd expect this
> paste0("42", "€")
[1] "42€"

> sessionInfo()
R version 3.3.1 (2016-06-21)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252    LC_MONETARY=German_Germany.1252
[4] LC_NUMERIC=C                    LC_TIME=German_Germany.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] stringi_1.1.2 pacman_0.4.1 

loaded via a namespace (and not attached):
[1] tools_3.3.1
```

**Comment by gagolews** [comment]
The problem is with the EURO currency sign you use: it is not really part of the official Latin-1 character set (This is why it is translated to http://www.fileformat.info/info/unicode/char/0080/index.htm). Therefore, you should input it as unicode http://www.fileformat.info/info/unicode/char/20ac/index.htm, i.e. `\u20ac`.

A copy-paste version: `€`.

**Comment by dapper2dan** [comment]
I get your point (that the use of 0080 is not official), but would urge you to reconsider, because Windows uses the 0080 for the EURO currency sign (see https://www.microsoft.com/typography/EuroSymbolFAQ.mspx "What is the symbol's Windows codepage location?" and "How do I access the euro symbol?". That page is actually linked on the 20ac fileformat page that you linked to above.) This is also still valid for Win10. In other words, there is no way to enter the 20ac symbol directly in Windows, so one would always have to enter \u20ac to get the EURO symbol with str_c. Your copy and paste version does not work btw, i.e. it gets converted to 0080 as well.

**Comment by gagolews** [comment]
Sorry, there's nothing I can do about that, it's on the ICU side, and the Unicode consortium know better how to handle such characters. Yet, I will be monitoring this situation, maybe this has already been fixed in ICU>55

**Comment by dapper2dan** [comment]
Ok, nothing we can do there then. But thanks anyway for considering/keeping an eye on it.
