### ISSUE TITLE
open r 3.2.2/redhat

### ISSUE THREAD

**Issue by wooopenr** [gagolews/stringi#243]
hello friends, 

i am trying to install "stringi" package on open r 3.2.2 (on linux redhat). however, its giving me error like;

cc1plus: warning: command line option "-std=gnu99" is valid for C/obj but not for  c++

i usually grab package from mran - download it - and then push it to site repository

do we have compatible "stringi" package for r 3.2.2 version anywhere? 

please advise ...

**Comment by wooopenr** [comment]
i also tried to get package from "https://github.com/gagolews/stringi" and install it but got below error, 

error in rawToChar(block[seq_len(ns)]) : 
embedded nul in string: 'pk\003\004\n\0\.........0stringi-master

**Comment by gagolews** [comment]
I don't have much experience with the Microsoft R/Open, The package seems to be supported, see https://mran.microsoft.com/package/stringi/

Do you have the GNU compiler collection installed on your redhat machine (e.g., `yum install gcc-c++`) ?

**Comment by gagolews** [comment]
BTW,  The current release is Microsoft R Open **3.3.2**, consider an upgrade.

**Comment by wooopenr** [comment]
thank you for your comment - have gcc-c++.x64_64 installed. 

this link, https://mran.microsoft.com/package/stringi/, itself give me that "-std=gnu99" error...

**Comment by gagolews** [comment]
I guess that the issue may be on the MS side, consider emailing their tech support (?)

**Comment by wooopenr** [comment]
not for "stringi" or any package though  - not sure but other packages are working fine...

**Comment by wooopenr** [comment]
checked with MS folks - tech support but they are giving same instruction that we followed - get "stringi-master" zip file - unzip it and then try to install it. But it is giving error like, 

**Error in rawToChar(block[seq_len(ns)]) : 
  embedded nul in string: 'PK\003\004\n\0\0\0\0\0EE'J\0\0\0\0\0\0\0\0\0\0\0\0\017\0\t\0stringi-master/UT\005\0\001b\032qXPK\003\004\n\0\0\0\b\0EE'JYJ\xc9\xfe\xdd\0\0\0\x84\001\0\0\034\0\t\0stringi-master/.'**

**Comment by gagolews** [comment]
You're trying to *install* a .zip file. Give `devtools::install_github` a try.

**Comment by wooopenr** [comment]
I got "devtools" package installed with many different dependencies...(sorry if I forgot to mention that we do not have internet connection to outside world from server...)
and I think that's the process we follow - get .tar package and then install it using rstudio client with syntax like, 
**> install.packages("/path.../stringi-master.tar", repos = NULL) and usually package gets install.** 
but for this package, get error. 
**Error in rawToChar(block[seq_len(ns)]) : 
  embedded nul in string: 'PK\003\004\n\0\0\0\0\0EE'J\0\0\0\0\0\0\0\0\0\0\0\0\017\0\t\0stringi-master/UT\005\0\001b\032qXPK\003\004\n\0\0\0\b\0EE'JYJ\xc9\xfe\xdd\0\0\0\x84\001\0\0\034\0\t\0stringi-master/.'**

**Comment by wooopenr** [comment]
any way to get latest version of stringi - may be 1.1.3 ?

**Comment by gagolews** [comment]
1. Clone the git repository
2. Run `R CMD build`, see https://stat.ethz.ch/R-manual/R-devel/library/utils/html/PkgUtils.html in order to generate a `.tar.gz` source
3. Run `R CMD INSTALL` 

For more info, refer to https://cran.r-project.org/doc/manuals/r-release/R-exts.html

**Comment by wooopenr** [comment]
thank you - its a great way to check everything, 

I did check for "string-master" and found below OK/ERROR but not sure where issues lies - we are running without internet connection - 

**# R CMD check stringi-master
* using log directory ‘/home/xxxx/stringi-master.Rcheck’
* using R version 3.2.2 (2015-08-14)
* using platform: x86_64-pc-linux-gnu (64-bit)
* using session charset: UTF-8
* checking for file ‘stringi-master/DESCRIPTION’ ... OK
* checking extension type ... Package
* this is package ‘stringi’ version ‘1.1.3’
* checking package namespace information ... OK
* checking package dependencies ...curl: (6) Couldn't resolve host 'mran.revolutionanalytics.com'
curl: (6) Couldn't resolve host 'mran.revolutionanalytics.com'
Warning in read.dcf(file = tmpf) :
  cannot open compressed file '/tmp/RtmpwM2ZbB/file5b4e49a374c5', probable reason 'No such file or directory'
Error in read.dcf(file = tmpf) : cannot open the connection
Execution halted**

**Comment by gagolews** [comment]
Closing as for the topis has been inactive for 2 months.
