### ISSUE TITLE
conencting R with Teradata using RODBC  

### ISSUE THREAD

**Issue by wooopenr** [gagolews/stringi#244]
I am trying to connect to Teradata using OpenR with RODBC package. I have Linux OS and Teradata driver installed properly. I created DSN by adding entry for Teradata source db in odbc.in file (under "/opt/teradata/client/ODBC_64"). However, when try below syntax to connect it - its not connecting, 

> ch <- odbcConnect(dsn="testDSN",uid="xxx",pwd="xxx")
or
> ch <- odbcDriverConnect("Driver=Teradata;DBCName=xxx; UID=xxx;PWD=xxx")**

it simply says 
 [RODBC] ERROR: state IM002, code 0, message [unixODBC][Driver Manager]Data source name not found, and no default driver specified

Any additional configuration needed?

**Comment by gagolews** [comment]
This has nothing to do with `stringi`.
