### ISSUE TITLE
str_replace encoding

### ISSUE THREAD

**Issue by danielsjf** [gagolews/stringi#245]
This issue is a slightly modified version of an earlier issue [in stringr](https://github.com/tidyverse/stringr/issues/143).

Using € signs has strange effects in combination with stri_replace.

```
text <- '€50$'
text # [1] "€50$"
stri_replace(text, '50', regex = '100') # [1] "\u0080100$"
stri_replace(text, '[$]', regex = '€') # [1] "\u008050\u0080"
```

It seems that stringi changes the encoding:

```
Encoding(text) # 'latin1'
Encoding(stri_replace(text, '50',  regex = '100')) # 'UTF-8'
```

However, resetting the encoding does not solve my problem:

```
replacement <- str_replace(text, '50', '100')
Encoding(replacement)
Encoding(replacement) <- 'latin1'
Encoding(replacement)
replacement
```

As @gagolews already indicated, playing with Encoding doesn't change the real encoding. However, some further experiments showed that even in the byte representations, there are differences.

```
# euro sign from definition (http://www.fileformat.info/info/unicode/char/20aC/index.htm)
> euro_sign_utf8_def <- rawToChar(as.raw(c('0xE2', '0x82', '0xAC')))
> euro_sign_utf8_def
[1] "â‚¬"
> Encoding(euro_sign_utf8_def) <- 'UTF-8'
> euro_sign_utf8_def
[1] "€"

# euro sign from text
> euro_sign_text <- '€'
> euro_sign_text
[1] "€"

# euro sign from string replace conversion (from text)
> euro_sign_str_rep_t <- stringi::stri_replace(euro_sign_text, ' ', regex = ' ')
> euro_sign_str_rep_t
[1] "\u0080"

# euro sign from string replace conversion (from definition)
> euro_sign_str_rep_d <- stringi::stri_replace(euro_sign_utf8_def, ' ', regex = ' ')
> euro_sign_str_rep_d
[1] "€"

> charToRaw(euro_sign_utf8_def)
[1] e2 82 ac
> charToRaw(euro_sign_text)
[1] 80
> charToRaw(euro_sign_str_rep_t)
[1] c2 80
> charToRaw(euro_sign_str_rep_d)
[1] e2 82 ac
```

Where only two of the three byte representations are actually printed as a euro sign in RStudio (R terminal doesn't even show the euro sign).

**Comment by gagolews** [comment]
ISO/IEC 8859-1 does not officially support the EURO sign. Thus, you rely on an undocumented behavior here.

Stringi converts each input to UTF-8, and this is by design, see `?"stringi-encoding"` for discussion. UTF-8 is well-supported by R and it is a universal super-set of all the other encodings.

If fact, the conversion is seamless and you shouldn't bother with this. If you want to convert from/to `UTF-8` to anything else, see `stri_convert`.
