### ISSUE TITLE
Replacing all accents

### ISSUE THREAD

**Issue by skanskan** [gagolews/stringi#246]
Is there any stringr or stringi function or simple way to replace all accents/diactritics from a string with the plain version of the letter?

For example
soñar -> sonar
camión -> camion
égoïste -> egoiste

I'm looking for a single command to do it, instead of having a large list of possible changes.

**Comment by gagolews** [comment]
Yep, take a look at `stringi::stri_trans_general`.

**Comment by trinker** [comment]
@gagolews nice thanks for this
