### ISSUE TITLE
multiple string - multiple pattern extractions

### ISSUE THREAD

**Issue by ripkrizbi** [gagolews/stringi#247]
Hi, 

the manual for stri_extract_*_fixed states it is vectorized over bot string and pattern. However, if I try:

```
> stri_extract_all_fixed(c("abaBAba", "bbbAAAba"), c("Aba", "bAA", "aba"))

[[1]]
[1] "Aba"

[[2]]
[1] "bAA"

[[3]]
[1] "aba"

Warning message:
In stri_extract_all_fixed(c("abaBAba", "bbbAAAba"), c("Aba", "bAA",  :
  longer object length is not a multiple of shorter object length
```

I get a complaint that the length of a pattern vector is not a multiple of the string vector. What I hoped for was a cross-product of all matches , i.e. running all patterns against each string. Can you suggest on how best to achieve that without lapply as this tends to get very slow in my case (some 20k strings and 2k patterns).

Many thanks!

**Comment by gagolews** [comment]
Nope, this must be slow, it is a cross product. Yet, note that `(for each pattern) (for each string) extract(string, pattern)` shall be much faster than  `(for each string) (for each pattern) extract(string, pattern)`

In R, it is usual to apply `outer()` for such patterns
