### ISSUE TITLE
If-Then-Else Conditionals (Feature Request)

### ISSUE THREAD

**Issue by fmgithub2017** [gagolews/stringi#251]
Is there any plan to add the If-Then-Else Conditionals (​http://www.regular-expressions.info/conditional.html) ?

It is a very important regular expression feature but it is still missing in R (stringi package). It would be really of great value implementing that.

Thank you very much for the support.

**Comment by gagolews** [comment]
Great idea, but this is ICU-related, we did not implement the regex engine from scratch. Ask at http://site.icu-project.org/bugs

**Comment by fmgithub2017** [comment]
I have asked ICU-project, let's wait and see now, thanks for the reply.

**Comment by gagolews** [comment]
Could you pls paste the ICU bug tracker ticket link here? Thx!

**Comment by fmgithub2017** [comment]
Of course my friend, I don't know if I filled the ticket 100% correctly: but here it is: 
http://bugs.icu-project.org/trac/ticket/13023
