### ISSUE TITLE
[stri_sub] negative length not working?

### ISSUE THREAD

**Issue by mr-majkel** [gagolews/stringi#252]
Hi,

I'm not sure if I have misunderstood the help page for `stri_sub()`, but I think that feeding negative length doesn't work as supposed to, i.e. I can't get the n chars counting backwards.

According to help page:
> Negative length means counting backwards.

Example:
```
s <- "Lorem ipsum dolor sit amet, consectetur adipisicing elit."

# Both calls return empty string
stri_sub(s, from = 5, length = -5)
stri_sub(s, from = -1, length = -4)
```

**Comment by gagolews** [comment]
Thanks for pointing this out.

In the underlying C++ code, we have:

```
if (length_tab) {
         if (cur_to <= 0) {
            SET_STRING_ELT(ret, i, R_BlankString);
            continue;
         }
```

which means that if `length <= 0`, then, the result is always an empty string.
Thus, there's a bug in the function's manual only. Fixing.
