### ISSUE TITLE
package compilation fails in R 3.1.1

### ISSUE THREAD

**Issue by mgagliol** [gagolews/stringi#261]
With the following message: could not find function "dir.exists"

> *installing *source* package ‘stringi’ ...
> ** package ‘stringi’ successfully unpacked and MD5 sums checked
> checking for local ICUDT_DIR... icu55/data
> checking for R_HOME... /usr/lib/R
> checking for R... /usr/lib/R/bin/R
> checking for R >= 3.1.0... yes
> checking for cat... /bin/cat
> checking for gcc... gcc -std=gnu99
> checking whether the C compiler works... yes
> checking for C compiler default output file name... a.out
> checking for suffix of executables... 
> checking whether we are cross compiling... no
> checking for suffix of object files... o
> checking whether we are using the GNU C compiler... yes
> checking whether gcc -std=gnu99 accepts -g... yes
> checking for gcc -std=gnu99 option to accept ISO C89... none needed
> checking how to run the C preprocessor... g++ -E
> checking for grep that handles long lines and -e... /bin/grep
> checking for egrep... /bin/grep -E
> checking for ANSI C header files... yes
> checking for sys/types.h... yes
> checking for sys/stat.h... yes
> checking for stdlib.h... yes
> checking for string.h... yes
> checking for memory.h... yes
> checking for strings.h... yes
> checking for inttypes.h... yes
> checking for stdint.h... yes
> checking for unistd.h... yes
> checking elf.h usability... yes
> checking elf.h presence... yes
> checking for elf.h... yes
> checking whether we are using the GNU C++ compiler... yes
> checking whether g++ -std=c++11 accepts -g... yes
> checking whether the C++ compiler supports the long long type... yes
> checking whether the compiler implements namespaces... yes
> checking whether the compiler supports Standard Template Library... yes
> checking whether std::map is available... yes
> checking for pkg-config... no
> *** pkg-config could not be found
> checking whether we may compile src/icu55/common/umapfile.c... yes
> checking whether we may compile src/icu55/common/putil.cpp... yes
> checking whether we can fetch icudt... downloading ICU data library (icudt)
> output path: icu55/data/icudt55l.zip
> Error in stri_download_icudt("icu55/data") : 
>  could not find function "dir.exists"
> Calls: identical -> stri_download_icudt
> Execution halted
> *** icudt could not be downloaded. stopping.
> ERROR: configuration failed for package ‘stringi’`

**Comment by gagolews** [comment]
This has already been fixed in #254
