### ISSUE TITLE
Lower-level C++ api

### ISSUE THREAD

**Issue by dselivanov** [gagolews/stringi#264]
Hi @gagolews. Despite that at textworkshop17 I told that it I think it is useless to have lower level C++ api for `stringi`, now I think it can help a lot (especially with memory fragmentation). Internally both `tokenizers`, `text2vec` work with `vector<string>` or `<vector<vector<string>>>`. So obvious fast win would be to have option in `stringi` to return external pointer to `<vector<vector<string>>>` instead of R's list of character vectors.

This will allow to:
1. avoid conversion from C++ strings to R's strings
1. reduce memory fragmentation
1. easily introduce thread parallelism since we won't touch R api and work only with objects out of R's heap

What do you think? will it be hard to add?

**Comment by gagolews** [comment]
This is a good idea. I will think about the details and let you know.

**Comment by gagolews** [comment]
I guess this would require a complete rewrite of the library. Maybe some day (stringi v2), perhaps with a more language-agnostic design (to allow e.g., a Python version of stringi).
