### ISSUE TITLE
Equivalent of encodeString

### ISSUE THREAD

**Issue by hadley** [gagolews/stringi#265]
The purpose of `encodeString` is to encode non-printable characters. But something seems wrong with R's approach:

```R
> encodeString(emo::ji("smile"))
[1] "\\U0001f604"
> encodeString(emo::ji("phone"))
[1] "☎️"
```

Could stringi provide a more robust alternative?

**Comment by gagolews** [comment]
Have you checked `stringi::stri_escape_unicode`?

**Comment by gagolews** [comment]
BTW, I plan to upgrade ICU to v59 in the near future so that stringi will start supporting emojis introduced in Unicode >= 9.0. Emojis were requested by many @ Ken's London Text Workshop

**Comment by hadley** [comment]
Yeah, it's currently worse than `encodeString()`:

```R
> stringi::stri_escape_unicode(emo::ji("phone"))
[1] "\\u260e\\ufe0f"
```

I assume this is because you don't have the emoji data yet.

**Comment by gagolews** [comment]
This might be the case. Let's get back to this issue in the (near) future then.

**Comment by hadley** [comment]
`stri_width()` has problems for presumably the same reasons:

```R
> table(stringi::stri_width(emo:::emoji_name))

   1    2    3    4 
1067  341   13   11 
```

(All the width four emoji are the family "ligatures" like 👨‍👦‍👦 )

**Comment by gagolews** [comment]
For `stri_width`, I actually hard-code the widths based on pre-defined code ranges. I guess all emojis should be of width=2, am I right?

**Comment by hadley** [comment]
I think they should all be width 1

**Comment by hadley** [comment]
Assuming that you already have support for the combining mark.

**Comment by gagolews** [comment]
Where can I get the `emo` package from?

**Comment by hadley** [comment]
https://github.com/hadley/emo

**Comment by gagolews** [comment]
btw,As soon as I update the ICU (and thus the Unicode Character Database), access to emojis by name will be much the same like here:

```
> stri_trans_general("latin small letter a", "name-any")
[1] "latin small letter a"
> stri_trans_general("\\N{latin small letter a}", "name-any")
[1] "a"
```

**Comment by hadley** [comment]
That'll be great! (although the keywords will probably still be helpful)

**Comment by gagolews** [comment]
sure thing!

**Comment by gagolews** [comment]
the github version of stringi already has support of emojis, thanks to the update to icu

```
> stri_trans_general("\U0001F604", "Name")
[1] "\\N{SMILING FACE WITH OPEN MOUTH AND SMILING EYES}"
> stri_trans_general("\\N{SMILING FACE WITH OPEN MOUTH AND SMILING EYES}", "name-any")
[1] "😄"
```

**Comment by gagolews** [comment]
So actually the black-telephone example you provided is:

```
stri_trans_general("\u260e\ufe0f", "name")
[1] "\\N{BLACK TELEPHONE}\\N{VARIATION SELECTOR-16}"
```

**Comment by gagolews** [comment]
`stri_width` has now support for emojis.

**Comment by gagolews** [comment]
What constitutes a printable character is, to the best of my knowledge, not covered by Unicode standards — to some extent it depends on the display (available fonts etc.).

So this is currently out of scope in stringi.

**Comment by hadley** [comment]
Thanks!
