### ISSUE TITLE
Solaris install does not work with C++11 support

### ISSUE THREAD

**Issue by gaborcsardi** [gagolews/stringi#275]
At least not with Solaris 10 and Oracle Developer Studio 12.5 or g++ 5.2.0. 

I wonder if it would make sense to turn off C++11 support by default on this platform. Or give a more helpful message when configure fails.

Is there any situation when the package installs cleanly on Solaris with C++11 support turned on?

**Comment by gagolews** [comment]
Not really, no. Yet, it works on the CRAN machines, therefore I'm not touching the config.
