### ISSUE TITLE
Handling of special katakana letters

### ISSUE THREAD

**Issue by koheiw** [gagolews/stringi#276]
I can process Asia language easily thanks to **stringi**, but I found a potential inconsistency between `stri_extract_all_boundaries()` and `stri_detect_regex()` with a Japanese special katakana letter ㋐, which is a katakana ア in a circle. I consider ㋐ just a symbol but it is both symbol and katakana according to ICU's definiton. 
```r
stri_detect_regex(c('㋐'), "^[\\p{L}]$") # FALSE
stri_detect_regex(c('㋐'), "^[\\p{S}]$") # TRUE
stri_detect_regex(c('㋐'), "^[\\p{Katakana}]$") # TRUE
```
Probably due to the its membership in the symbol class, `stri_extract_all_boundaries()` does not skip the letter:
```r
stri_extract_all_boundaries('㋐', skip_word_kana = TRUE) # returns ㋐
stri_extract_all_boundaries('㋐', skip_word_none = TRUE) # returns NULL
```
I know this is a tricky case, but I submit this issue in a hope that **stringi** to become even better with Asian languages. Double-bite character sets are notoriously difficult to deal with, but you might find this page useful: http://www.localizingjapan.com/blog/2012/01/20/regular-expressions-for-japanese-text/

I also think it is a good idea to allow users to define what are the words in `stri_*_all_boundaries()` so that you will be free from this kind of problem.

**Comment by gagolews** [comment]
Interesting! Did you test the stringi package behavior when it is compiled against the latest version of the icu4c library? I wonder it it's just stringi or the Unicode database in ICU. http://site.icu-project.org/download

**Comment by koheiw** [comment]
I tried to use ICU59 data to build **stringi**, but it wasn't easy for me. I will try again.

**Comment by gagolews** [comment]
In the most recent version of UNICODE the character

```
stri_trans_general("\u32d0", "Name")
[1] "\\N{CIRCLED KATAKANA A}"
```

belongs to the `\p{So}` (other, symbol) class. I can't do anything about it, perhaps the Unicode consortium knows better.

But if you apply the NKFD transform, you get:

```
stri_trans_general(stri_trans_general("\u32d0", "nfkd"), "Name")
[1] "\\N{KATAKANA LETTER A}"
```


Hope this helps
