### ISSUE TITLE
installation error on suse linux 

### ISSUE THREAD

**Issue by rushikeshbrahmankar** [gagolews/stringi#277]
Hello Experts,
We are trying to install stringi on our R server ( 3.2 ) .
But getting below error: 
/usr/lib64/gcc/x86_64-suse-linux/4.3/../../../../lib64/crt1.o: In function `_start':
/usr/src/packages/BUILD/glibc-2.11.3/csu/../sysdeps/x86_64/elf/start.S:109: undefined reference to `main'
collect2: ld returned 1 exit status
make: *** [stringi.so] Error 1
ERROR: compilation failed for package ‘stringi’

Command tried for installation are as follow:
install.packages("/home/ruser/stringi/stringi_1.1.6.tar.gz")
install.packages("/home/ruser/stringi/stringi_1.1.6.tar.gz", configure.args="--disable-cxx11")
install.packages("stringi")
install.packages("stringi", configure.args="--disable-pkg-config")

Also tired with earlier version of R , but no success.
Can you please help in this..

Regards,
Rushikesh

**Comment by gagolews** [comment]
Hi, I don't have enough data: this is not a complete output from the install process.

**Comment by gagolews** [comment]
Closing as no response given in n months, n > 6
