### ISSUE TITLE
Downloading "icudt55l.zip" may fail in Server context

### ISSUE THREAD

**Issue by XD-DENG** [gagolews/stringi#282]
I understand the file `icudt55l.zip` will be downloaded from one of the three URLs provided in file `install.R`.

But if I'm installing this package on a production server which may not have internet access, this may cause trouble. The solution I came out with was to download `icudt55l.zip` separately, host is as *http://localhost/icudt55l.zip*, AND change the URL in the install.R in the source code.

This will work, but a bit troublesome. Will the author consider to include this file in the package itself?

**Comment by gagolews** [comment]
This problem has already been addressed in several github Issues. Please search within the Issues' history for the answer to your concern. HTH

**Comment by cderv** [comment]
As I answered this in another thread, I post it here for future reference if anyone search for it. 

You can consult the **INSTALL** recommandation on [github](https://github.com/gagolews/stringi/blob/master/INSTALL) or on [CRAN](https://cran.r-project.org/web/packages/stringi/INSTALL). It will explain everything if you need to compile with ICU. 

In your case you have downloaded the zip ICU bundle separately. Know that you don't have to modify any script to point to the location during installation. Use `install.packages("stringi", configure.vars="ICUDT_DIR=<icudt_dir>")` or set `ICUDT_DIR` as an environment variable before installation.

> ICUDT_DIR Optional directory from which an already downloaded ICU data
archive (icudt*.zip) may be copied; either an absolute path or a
path relative to /src; defaults to
icu55/data.he zip file. You can provide this info during the install without modifying any script. Use `install.packages("stringi", configure.vars="ICUDT_DIR=<icudt_dir>")` or set `ICUDT_DIR` as an environment variable before installation.

There are others solutions too: 

* You can also download the github repo as a zip bundle, then unzip and install from a source directory with `devtools::install`. As the repo included a distribution of `ICU` in `src/ICU55/data`, it will work. 

* You can build you own package `tar.gz` that includes the ICU zip file and use this source bundle to install it with `devtools::install_local` for example or just `install.packages("stringi_custom.tar.gz")`

All this is explained in the `INSTALL` file. You should have a look at it.
