### ISSUE TITLE
the questions of installation stringi

### ISSUE THREAD

**Issue by crystal0721** [gagolews/stringi#283]
I am checking an R package called  stringi，while there are some questions as follows when installing：
      Error: package or namespace load failed for ‘stringi’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/PUBLIC/software/RNA/R/R-3.4.1/lib64/R/library/stringi/libs/stringi.so':
  libicui18n.so.52: cannot open shared object file: No such file or directory
Error: loading failed
Execution halted
ERROR: loading failed

  would some one tell me how to solve these，thank you very much。

**Comment by gagolews** [comment]
Try reinstalling the stringi package and let me know if this helped.

**Comment by wzrzt** [comment]
I meet the same error too. After I installed icu4c 60.2 from source downloaded from 
http://site.icu-project.org/download/60#TOC-ICU4C-Download
I want to solve the problem that you mentioned in former issue that ICU bug with Chinese characters.  
So I try to upgrade libicu-dev from 5.5 to 60.2 on my ubuntu. 
On my mac, after brew install icu4c, stringi work fine with Chinese characters.  
```
installing via 'install.libs.R' to /opt/microsoft/ropen/3.4.1/lib64/R/library/stringi
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
Error: package or namespace load failed for ‘stringi’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/opt/microsoft/ropen/3.4.1/lib64/R/library/stringi/libs/stringi.so':
  libicui18n.so.60: cannot open shared object file: No such file or directory
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/opt/microsoft/ropen/3.4.1/lib64/R/library/stringi’
* restoring previous ‘/opt/microsoft/ropen/3.4.1/lib64/R/library/stringi’

The downloaded source packages are in
	‘/tmp/RtmpRR5AYM/downloaded_packages’
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
Warning message:
In install.packages("stringi", repos = "http://cran.rstudio.com/",  :
  installation of package ‘stringi’ had non-zero exit status
```

**Comment by wzrzt** [comment]
And when installing stringi, It found ICU4C 60.2. 
<img width="946" alt="stringierror" src="https://user-images.githubusercontent.com/12440644/35454817-83c73e34-030a-11e8-9513-d70ec14b8508.png">

**Comment by gagolews** [comment]
This is not particularly related to stringi, but your ill-configured dynlib search path... `libicui18n.so.60: cannot open shared object file: No such file or directory` try changing the location of the `libicu*.so*` files or changing `LD_LIBRARY_PATH` (among others)

why don't you give `Sys.setenv(LD_LIBRARY_PATH="/path/to/blah")` a try (for example)

**Comment by wzrzt** [comment]
Thank you very much. I tried it on another ubuntu and no problem appears. So I reinstalled libicu-dev on my ubuntu with the parameter "--fix-broken" and then the problem is gone.
