### ISSUE TITLE
Warn if coerce list->character vector

### ISSUE THREAD

**Issue by mespe** [gagolews/stringi#285]
### Reproducible example

```
a = strsplit("hello", "")
stri_count_regex(a, "c")
```
returns 1

```
stri_count_regex(a[[1]], "c") 
```
returns 0 0 0 0 0

### Desired behavior

Fail with error that stri_count_regex() expects a character vector.

### sys.info

R version 3.4.2
stringi version: stringi_1.1.5

**Comment by gagolews** [comment]
It is a feature.
`stri_count` accepts a character vector argument. List is not of such a type, so it will be converted to a string. The result will be:

```
> stringi:::stri_prepare_arg_string(a)
[1] "c(\"h\", \"e\", \"l\", \"l\", \"o\")"
```

so there's one `c` in the above string.

In the second example we are matching the pattern 5 times (to each letter). None of the letters is equal to `c`, so there are 5 zeros.

The behavior is well-documented and explained in the manual, see, e.g., `?"stringi-arguments"`

**Comment by mespe** [comment]
Thanks for letting me know you consider this a feature.

We found the documentation lacking, honestly. Furthermore, the fact that the call to R's as.character() is happening in C code rather than in any of the exported R functions makes it rather difficult to diagnose what is actually happening with this function. Not many users will be able to drop into gdb to figure this out.

You might consider adding a warning given the known issues surrounding silent coercion, and given that your functions are rarely called from stringi but rather from other packages. For example, to diagnose our bug, we had to go from stringr -> stringi -> R code -> C code. 

Thanks,

**Comment by gagolews** [comment]
Yeah, I guess a warning could do the trick here.

**Comment by gagolews** [comment]
```
> a = strsplit("hello", "")
> stri_count_regex(a, "c")
[1] 1
Warning message:
In stri_count_regex(a, "c") : argument is not an atomic vector; coercing
```

"trivial" lists don't yield any warning
```
> stri_enc_toutf8(list(1, 2, 3, 4))
[1] "1" "2" "3" "4"
```

but:

```
> stri_enc_toutf8(list(1, 2, 3, 5:6))
[1] "1"   "2"   "3"   "5:6"
Warning message:
In stri_enc_toutf8(list(1, 2, 3, 5:6)) :
  argument is not an atomic vector; coercing
> stri_enc_toutf8(list(1, 2, 3, NULL))
[1] "1"    "2"    "3"    "NULL"
Warning message:
In stri_enc_toutf8(list(1, 2, 3, NULL)) :
  argument is not an atomic vector; coercing
> 
```
