### ISSUE TITLE
Work around bug in `enc2utf8` / `translateCharUTF8` on Windows

### ISSUE THREAD

**Issue by patperry** [gagolews/stringi#287]
R's handling of native text is buggy on Windows. Specifically, R marks all Windows-1252 text as Latin-1. This causes problems when converting from marked "latin1" strings to "UTF-8": bytes in the range 0x80 to 0x9F get translated as U+0080 to U+009F. See, for example, the input string `"You don‘t get “your” money’s worth"`:

<img width="544" alt="screen shot 2017-11-08 at 2 39 48 pm" src="https://user-images.githubusercontent.com/43450/32571115-516f1092-c494-11e7-8f0c-1d2de56bb2a8.png">

More context: https://stat.ethz.ch/pipermail/r-devel/2017-September/074908.html

You can work around this bug by interpreting `CE_LATIN1` as Windows-1252 on Windows. Feel free to copy code from https://github.com/patperry/r-utf8/blob/master/src/util.c#L59

**Comment by gagolews** [comment]
Hi, I've worked that already in #270

**Comment by patperry** [comment]
great to hear! sorry for not checking the devel version before posting

**Comment by gagolews** [comment]
no worries!
 I'll be filing a CRAN update of stringi today
