### ISSUE TITLE
stri_match doesn't return correct number of columns when input is empty

### ISSUE THREAD

**Issue by hadley** [gagolews/stringi#288]
```R
dim(stringi::stri_match_first_regex(character(), "(x)"))
#> [1] 0 1
dim(stringi::stri_match_first_regex(character(), "(x)(y)"))
#> [1] 0 1
```

In an ideal world the number of columns would be one plus the number of groups. 

Part of https://github.com/tidyverse/tidyr/issues/313

**Comment by barryrowlingson** [comment]
This might also manifest when the argument is a single NA - was about to file this as a separate issue bit it looks similar enough:

Match a vector of length 2 with one NA in it - get two rows  and 2 columns (one for the regex, one for the capture group), as expected:

```
> stri_match_first_regex(c("A",NA),"(.)")
     [,1] [,2]
[1,] "A"  "A" 
[2,] NA   NA 
```

Match an NA, returns single-column:

```
> stri_match_first_regex(NA,"(.)")
     [,1]
[1,] NA  
```

Can't see documentation for this, and I'd expect the result from my second example to be the same as the second row of the first example...

**Comment by gagolews** [comment]
Sorry, @hadley, I've this issue got lost in my spambox. Fix pending.
