### ISSUE TITLE
Should str_c etc have na.rm = TRUE?

### ISSUE THREAD

**Issue by hadley** [gagolews/stringi#289]
Since it treats `NA`s like other summary functions.

**Comment by gagolews** [comment]
Hmm... `paste()` behaves more like a vectorized arithmetic operator, say, `+`, and not an aggregation function, say `sum()`

So I don't think this function should get rid of any strings

Maybe you mean the `stri_flatten()` function?

**Comment by hadley** [comment]
Except when `collapse` is non-NULL.  And `pmin()` and `pmax()` have `na.rm` arguments

**Comment by gagolews** [comment]
Thanks for pointing out that

```
> pmax(c(NA, 1), c(5, 5))
[1] NA  5
> pmax(c(NA, 1), c(5, 5), na.rm=TRUE)
[1] 5 5
```

**Comment by gagolews** [comment]
I'm adding this to `stri_flatten`

```
> stri_flatten(c(NA, "", "A", "", "B", NA, "C"), collapse=",", na_empty=TRUE, omit_empty=TRUE)
[1] "A,B,C"
> stri_flatten(c(NA, "", "A", "", "B", NA, "C"), collapse=",", na_empty=TRUE, omit_empty=FALSE)
[1] ",,A,,B,,C"
> stri_flatten(c(NA, "", "A", "", "B", NA, "C"), collapse=",", na_empty=FALSE, omit_empty=TRUE)
[1] NA
```

**Comment by gagolews** [comment]
And I added `stri_remove_empty` and `stri_na2empty` funs

**Comment by AndreMikulec** [comment]
Thanks,
My earlier concept had a somewhat similar idea.
"
Safe concatenation/comparison operator #292 
"
The original idea was because if I do I concatination 
```r
... string ... + if(){   } + ... string ...
```
and "if()" is not TRUE, then, if(){   } silently returns a NULL,
and that NULL wreaks havoc in string concatination.
