### ISSUE TITLE
Package installation failure in 1.1.6

### ISSUE THREAD

**Issue by chris-park** [gagolews/stringi#290]
Hi,

Installation of `stringi` 1.1.6 fails in a remote server with no network access, as the package attempts to download the `icudt` zip file from one of the three `icudt_mirrors` (see `install.R`). I think including a static copy of the zip file and including it within the package  for a self-contained install (maybe a flag?) might be nice for people who work in environments like mine.

I also noticed that 1.1.5 installed just fine  - I haven't checked the diff yet but I'll have a look later. This is just to flag it up while it's still fresh in my memory, and in case you have a quick fix.

**Comment by gagolews** [comment]
Check out https://stackoverflow.com/questions/31942322/how-to-install-stringi-from-local-file-absolutely-no-internet-access

**Comment by gagolews** [comment]
Did that help?
