### ISSUE TITLE
stri_unescape_unicode - invalid escape sequence detected for "\\"

### ISSUE THREAD

**Issue by FelixErnst** [gagolews/stringi#293]
Hi

```
> stri_unescape_unicode(c("\\"))
Warning message:
In stri_unescape_unicode("\\") :
  invalid escape sequence detected. Setting NA
```

In the man page for stri_unescape_unicode "\\\\" is explicitly mentioned. Therefore, shouldn't this result in "\\"?

Is this a bug or am I using the function wrongly?
Thanks for any help.

**Comment by gagolews** [comment]
In order to input `\\` in R, you should type `\\\\`. It's not a bug, it's a feature.
