### ISSUE TITLE
Windows 10 R 3.2.4 Issue: 'stringi' 1.1.5 is being loaded, but >= 1.1.6 is required

### ISSUE THREAD

**Issue by charlesutton78** [gagolews/stringi#298]
Hello. I'm new to all this so provide some guidance on best way to post.

My issue is 'stringi' 1.1.5 is being loaded, but >= 1.1.6 is required which is preventing stringr from working. I can't seem to force stringi to update beyond 1.1.5 although. I've provided command, error, and sessionInfo.

I encountered this while trying to follow David Langer's Intro to Data Science series (https://www.youtube.com/watch?v=32o0DnuRjfg&t=3606s). This line of code (misses <- data.combined[which(str_detect(data.combined$Name, "Miss.")),]) needs str_detect which comes from stingr is my understanding.

Command:

library(stringr)

Error:

Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  namespace ‘stringi’ 1.1.5 is being loaded, but >= 1.1.6 is required
In addition: Warning message:
package ‘stringr’ was built under R version 3.5.0 
Error: package or namespace load failed for ‘stringr’

Here's my session info. Let me know what else is needed

Error Received

Session Info:

> sessionInfo()
R version 3.2.4 Revised (2016-03-16 r70336)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] ggplot2_2.2.1

loaded via a namespace (and not attached):
Error in x[["Version"]] : subscript out of bounds
In addition: Warning messages:
1: In FUN(X[[i]], ...) :
  DESCRIPTION file of package 'scales' is missing or broken
2: In FUN(X[[i]], ...) :
  DESCRIPTION file of package 'lazyeval' is missing or broken
3: In FUN(X[[i]], ...) :
  DESCRIPTION file of package 'tibble' is missing or broken
4: In FUN(X[[i]], ...) :
  DESCRIPTION file of package 'Rcpp' is missing or broken
5: In FUN(X[[i]], ...) :
  DESCRIPTION file of package 'digest' is missing or broken

**Comment by charlesutton78** [comment]
Thanks Marek. Did exactly this in RGui 32 bit. Message I get is below. Then when I try to run stringr i get the other message below. The issue is with stringr not being able to launch without a version of stringi greater than 1.1.6. 

BTW - I've also tried a manual install from the CRAN website that had 1.1.7 available, but when I unpacked into my win-library and run in RStudio, error message is about .dll not being able to be found although I see the file in the source folder.

Message after "stringi" install:

Installing package into ‘C:/Users/Charles Sutton/Documents/R/win-library/3.2’
(as ‘lib’ is unspecified)
--- Please select a CRAN mirror for use in this session ---

  There is a binary version available but the source version is later:
        binary source needs_compilation
stringi  1.1.5  1.2.2              TRUE

  Binaries will be installed
trying URL 'https://cran.cnr.berkeley.edu/bin/windows/contrib/3.2/stringi_1.1.5.zip'
Content type 'application/zip' length 14220135 bytes (13.6 MB)
downloaded 13.6 MB

package ‘stringi’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
        C:\Users\Charles Sutton\AppData\Local\Temp\Rtmp2jzuk2\downloaded_packages

Message after trying to load "stringr"

> library("stringr")
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  namespace ‘stringi’ 1.1.5 is being loaded, but >= 1.1.6 is required
In addition: Warning message:
package ‘stringr’ was built under R version 3.5.0 
Error: package or namespace load failed for ‘stringr’

Session Info:

sionInfo()
R version 3.2.4 Revised (2016-03-16 r70336)
Platform: i386-w64-mingw32/i386 (32-bit)
Running under: Windows 10 x64 (build 16299)

locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] tools_3.2.4

**Comment by gagolews** [comment]
Hi, could you try with the latest R version? 3.2 is not supported anymore

**Comment by gagolews** [comment]
BTW, compilation of stringi_1.2.2 failed on Windows, I'll be filing an update soon (~3 days). Stay tuned.

**Comment by charlesutton78** [comment]
I will check latest version of R. Thanks for the stringi_1.2.2 Windows feedback. I'll let you know once I've done latest update of R and you let me know when the stringi_1.2.2. Really appreciate your help getting me up to speed on my data science journey.

**Comment by charlesutton78** [comment]
Updating R to 3.5 seemed to fix the issue. Thanks @gagolews.
