### ISSUE TITLE
stri_sub() and stri_sub<-() should accept lists

### ISSUE THREAD

**Issue by gagolews** [gagolews/stringi#30]
```
> x <- "ala"; stri_sub(x, c(2,1), c(2,1)) <- c("Y", "Z")
> x
[1] "aYa" "Zla"
```

someday we may wish to add a function that is not vectorized w.r.t. to the first element,
so that we obtain `"ZYa"` (from/to/length should be sorted increasingly)

OR

the above setting will be strange (non-vectorized? OMG!), so we may accept lists of integer vectors as from/to/length

**Comment by gagolews** [comment]
@hadley's suggestion/question:

```

x <- c("a b c")
stri_sub(x, c(1, 3), c(1, 3)) <- c("A", "B")
x
# [1] "A b c" "a B c"

Is there an easy way to get "A B c"  ?
```

**Comment by gagolews** [comment]
`vectorize_all` arg to stri_sub???

**Comment by gagolews** [comment]
@markdanese's example:
```
# toy data and split matrix
x <- c("abcdefgh", "ijklmnop")
split <- matrix(1:8, ncol = 2, byrow = TRUE)
```  

`stri_sub(x, split)`
gives: 
`[1] "ab" "kl" "ef" "op"`  

but I was hoping for this:
```
[[1]]
[1] "ab" "cd" "ef" "gh"
[[2]]
[1] "ij" "kl" "mn" "op"
```

or even better, this:
```
     [,1] [,2] [,3] [,4]
[1,] "ab" "cd" "ef" "gh"
[2,] "ij" "kl" "mn" "op"
```

The last piece is accomplished by `do.call(rbind, lapply(x, stri_sub, split))` but I was hoping it might be faster if it were all done in c++.

**Comment by gagolews** [comment]
Note: we should be able to imitate a call to `stri_replace(...)` with `stri_subXXX(stri_locate(...)) <- ...` and a call to `stri_extract(...)` with `stri_sub(stri_locate(...))`

**Comment by gagolews** [comment]
Also, `stri_paste` accepting lists could be handy.

**Comment by gagolews** [comment]
@hadley's example in #234:


```
library(stringi)
x <- "abcdefgh"
str_sub(x, c(1, 3), c(1, 3))  <- c("X", "Y")
x
#> [1] "Xbcdefgh" "abYdefgh"
```

Ideally it would return "XbYdefgh"

**Comment by hadley** [comment]
Ooops, I guess I keep forgetting about this issue!

**Comment by magic-lantern** [comment]
It's been quite some time since the last comment. Is there a work around for this that people have come up with?

**Comment by gagolews** [comment]
Finally I've had time for this. DONE.


Example 1:

```
> stri_sub_replace_all("a b c", c(1, 3, 5), c(1, 3, 5), value=c("A", "B", "C"))
[1] "A B C"
```


Example 2:

```
> x <- c("12 3456 789", "abc", "", NA, "667")
> stri_sub_all(x, stri_locate_all_regex(x, "[0-9]+", omit_no_match=TRUE)) <- "***"
> print(x)
[1] "*** *** ***" "abc"         ""            NA            "***"  
```

Example 3 (@markdanese):

```
> x <- c("abcdefgh", "ijklmnop")
> split <- matrix(1:8, ncol = 2, byrow = TRUE)
> split
     [,1] [,2]
[1,]    1    2
[2,]    3    4
[3,]    5    6
[4,]    7    8
> stri_sub_all(x, split)
[[1]]
[1] "ab" "cd" "ef" "gh"

[[2]]
[1] "ij" "kl" "mn" "op"
> stri_list2matrix(stri_sub_all(x, split), byrow=TRUE)
     [,1] [,2] [,3] [,4]
[1,] "ab" "cd" "ef" "gh"
[2,] "ij" "kl" "mn" "op"
```

**Comment by hadley** [comment]
Nice work - thanks!

**Comment by markdanese** [comment]
thanks!  looking forward to testing it out
