### ISSUE TITLE
Stringi install error on windows 

### ISSUE THREAD

**Issue by Jammcgro123** [gagolews/stringi#304]
Hi there,
I am trying to install package stringi to R version 3.5.0 but i am facing difficulties in doing so.
Below i show how i am trying to install and and the error message i recieve.

 packageurl<-"https://cran.r-project.org/src/contrib/Archive/stringi/stringi_1.1.6.tar.gz"
> install.packages(packageurl, repos=NULL, type="source")
trying URL 'https://cran.r-project.org/src/contrib/Archive/stringi/stringi_1.1.6.tar.gz'
Content type 'application/x-gzip' length 3647049 bytes (3.5 MB)
downloaded 3.5 MB

* installing *source* package 'stringi' ...
** package 'stringi' successfully unpacked and MD5 sums checked
** libs

*** arch - i386
c:/Rtools/mingw_32/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-35~1.0/include" -DNDEBUG -I. -Iicu55/ -Iicu55/unicode -Iicu55/common -Iicu55/i18n -DU_STATIC_IMPLEMENTATION -DU_COMMON_IMPLEMENTATION -DU_I18N_IMPLEMENTATION -DUCONFIG_USE_LOCAL -DU_TOOLUTIL_IMPLEMENTATION -DNDEBUG         -O2 -Wall  -mtune=generic -c stri_ICU_settings.cpp -o stri_ICU_settings.o
/bin/sh: c:/Rtools/mingw_32/bin/g++: No such file or directory
make: *** [stri_ICU_settings.o] Error 127
ERROR: compilation failed for package 'stringi'
* removing 'C:/Program Files/R/R-3.5.0/library/stringi'
In R CMD INSTALL
Warning message:
In install.packages(packageurl, repos = NULL, type = "source") :
  installation of package ‘C:/Users/ADMINI~1.QUB/AppData/Local/Temp/2/RtmpU1EMiE/downloaded_packages/stringi_1.1.6.tar.gz’ had non-zero exit status

does anyone have a resolution to this?

**Comment by gagolews** [comment]
Do you have Rtools installed? see https://cran.r-project.org/bin/windows/Rtools/

**Comment by vempi** [comment]
**I have exactly same above issues. I already install Rtools. But it still remains errors.**

`installing via 'install.libs.R' to C:/Users/vempi/Documents/R/win-library/3.5/stringi
downloading the ICU data library (icudt)
output path: icu61/data/icudt61l.zip
trying URL 'https://raw.githubusercontent.com/gagolews/stringi/master/src/icu61/data/icudt61l.zip'
Content type 'application/zip' length 10791080 bytes (10.3 MB)
==================================================
downloaded 10.3 MB

icudt fetch successful
decompressing icudt archive icu61/data/icudt61l.zip to: C:/Users/vempi/Documents/R/win-library/3.5/stringi/libs
icudt has been installed successfully

*** arch - x64
Warning in file(con, "r") :
  cannot open file 'C:/PROGRA~1/R/R-35~1.0/etc/x64/Makeconf': No such file or directory
Error in file(con, "r") : cannot open the connection
* removing 'C:/Users/vempi/Documents/R/win-library/3.5/stringi'
In R CMD INSTALL

The downloaded source packages are in
        ‘C:\tmp\RtmpQrg721\downloaded_packages’
Warning message:
In install.packages(NULL, .libPaths()[1L], dependencies = NA, type = type) :
  installation of package ‘stringi’ had non-zero exit status`

**Comment by vempi** [comment]
**I have the same issue with installing stringi.
I already installed Rtools, but it still remains error.**

installing via 'install.libs.R' to C:/Users/vempi/Documents/R/win-library/3.5/stringi
downloading the ICU data library (icudt)
output path: icu61/data/icudt61l.zip
trying URL 'https://raw.githubusercontent.com/gagolews/stringi/master/src/icu61/data/icudt61l.zip'
Content type 'application/zip' length 10791080 bytes (10.3 MB)
==================================================
downloaded 10.3 MB

icudt fetch successful
decompressing icudt archive icu61/data/icudt61l.zip to: C:/Users/vempi/Documents/R/win-library/3.5/stringi/libs
icudt has been installed successfully

*** arch - x64
Warning in file(con, "r") :
  cannot open file 'C:/PROGRA~1/R/R-35~1.0/etc/x64/Makeconf': No such file or directory
Error in file(con, "r") : cannot open the connection
* removing 'C:/Users/vempi/Documents/R/win-library/3.5/stringi'
In R CMD INSTALL

The downloaded source packages are in
        ‘C:\tmp\RtmpQrg721\downloaded_packages’
Warning message:
In install.packages(NULL, .libPaths()[1L], dependencies = NA, type = type) :
  installation of package ‘stringi’ had non-zero exit status

**Comment by gagolews** [comment]
`'C:/PROGRA~1/R/R-35~1.0/etc/x64/Makeconf': No such file or directory` -- you got an ill-configured Rtools chain, presumably

**Comment by jrwalker-projects** [comment]
Hello,
I'm trying to install stringi 1.2.3 using R 3.5.0, RTools 3.5.0 and RStudio 1.1.442 on platform "x86_64-w64-mingw32". I encounter a problem that might be similar to Jammcgro123 where the compile stops with 

c:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-35~1.0/include" -DNDEBUG -I. -Iicu61/ -Iicu61/unicode -Iicu61/common -Iicu61/i18n -DU_STATIC_IMPLEMENTATION -DU_COMMON_IMPLEMENTATION -DU_I18N_IMPLEMENTATION -DUCONFIG_USE_LOCAL -DU_TOOLUTIL_IMPLEMENTATION -DNDEBUG -DWINVER=0x0600 -D_WIN32_WINNT=0x0600 -DU_USE_STRTOD_L=0         -O2 -Wall  -mtune=generic -c icu61/i18n/tmutamt.cpp -o icu61/i18n/tmutamt.o
g++.exe: error: CreateProcess: No such file or directory
make: *** [C:/PROGRA~1/R/R-35~1.0/etc/x64/Makeconf:215: icu61/i18n/**tmutamt.o**] Error 1
ERROR: compilation failed for package 'stringi'

**Comment by jrwalker-projects** [comment]
Thanks for the quick reply, earlier post was to show the error as the full compile is large. g++ ran many times prior to failing on tmutamt.o so i'll include how it starts. Still not sure why it fails on tmutamt.o
> install.packages("stringi")
Installing package into ‘C:/Users/thewa/Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)

  There is a binary version available but the source version is later:
        binary source needs_compilation
stringi  1.1.7  1.2.3              TRUE

installing the source package ‘stringi’

trying URL 'https://cran.rstudio.com/src/contrib/stringi_1.2.3.tar.gz'
Content type 'application/x-gzip' length 7270993 bytes (6.9 MB)
downloaded 6.9 MB

* installing *source* package 'stringi' ...
** package 'stringi' successfully unpacked and MD5 sums checked
** libs

*** arch - i386
c:/Rtools/mingw_32/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-35~1.0/include" -DNDEBUG -I. -Iicu61/ -Iicu61/unicode -Iicu61/common -Iicu61/i18n -DU_STATIC_IMPLEMENTATION -DU_COMMON_IMPLEMENTATION -DU_I18N_IMPLEMENTATION -DUCONFIG_USE_LOCAL -DU_TOOLUTIL_IMPLEMENTATION -DNDEBUG -DWINVER=0x0600 -D_WIN32_WINNT=0x0600 -DU_USE_STRTOD_L=0         -O2 -Wall  -mtune=generic -c stri_pad.cpp -o stri_pad.o
c:/Rtools/mingw_32/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-35~1.0/include" -DNDEBUG -I. -Iicu61/ -Iicu61/unicode -Iicu61/common -Iicu61/i18n -DU_STATIC_IMPLEMENTATION -DU_COMMON_IMPLEMENTATION -DU_I18N_IMPLEMENTATION -DUCONFIG_USE_LOCAL -DU_TOOLUTIL_IMPLEMENTATION -DNDEBUG -DWINVER=0x0600 -D_WIN32_WINNT=0x0600 -DU_USE_STRTOD_L=0         -O2 -Wall  -mtune=generic -c stri_container_utf16.cpp -o stri_container_utf16.o
c:/Rtools/mingw_32/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-35~1.0/include" -DNDEBUG -I. -Iicu61/ -Iicu61/unicode -Iicu61/common -Iicu61/i18n -DU_STATIC_IMPLEMENTATION -DU_COMMON_IMPLEMENTATION -DU_I18N_IMPLEMENTATION -DUCONFIG_USE_LOCAL -DU_TOOLUTIL_IMPLEMENTATION -DNDEBUG -DWINVER=0x0600 -D_WIN32_WINNT=0x0600 -DU_USE_STRTOD_L=0         -O2 -Wall  -mtune=generic -c stri_search_regex_split.cpp -o stri_search_regex_split.o
and so on for a large number of files.
Thanks for any help.

**Comment by gagolews** [comment]
As a temporary workaround,  you can try:

```
install.packages("https://github.com/gagolews/stringi/raw/master/devel/winbuilder/stringi_1.2.3.zip")
```

I created a binary version for R 3.5 using https://win-builder.r-project.org/

The win build fails on the CRAN machines  (https://cran.r-project.org/web/checks/check_results_stringi.html) with R-release and R-oldrel, but R-devel is fine. I asked the CRAN team of the possible reason why icudt download fails there, so far with no response.

**Comment by maproctor** [comment]
I was having this problem due to a default install on C: when I had put the required files elsewhere.

**Comment by kambanane** [comment]
I get this error:

[Error: package ‘stringi’ is not installed for 'arch = x64'
](url)

Any idea what I should do?

**Comment by kambanane** [comment]
I attempted this:

    install.packages("https://github.com/gagolews/stringi/raw/master/devel/winbuilder/stringi_1.2.3.zip")

and got this error:

Installing package into ‘C:/Users/anfangen/Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘https://github.com/gagolews/stringi/raw/master/devel/winbuilder/stringi_1.2.3.zip’ is not available (for R version 3.5.1)

And cannot use stringi, which has prevented me from using my existing code. How can I resolve this?

**Comment by yutannihilation** [comment]
If you set `repos` option in your `.Rprofile` or elsewhere, you need to specify `repos = NULL` explicitly, since the default value of `repos` of `install.packages()` is `getOption("repos")`.

Besides, the URL seems wrong... 🙄 Now zip file is here: https://github.com/gagolews/stringi/blob/master/devel/winbuilder/3.5/stringi_1.2.4.zip

So, you can do this:

``` r
install.packages(
    "https://github.com/gagolews/stringi/raw/master/devel/winbuilder/3.5/stringi_1.2.4.zip",
    repos = NULL,
)
```

c.f. `?install.packages`:

> If `repos = NULL`, a character vector of file paths of `‘.zip’` files containing binary builds of packages. (`http://` and `file://` URLs are also accepted and the files will be downloaded and installed from local copies.)

**Comment by younusa** [comment]
@yutannihilation WOW! THANK  YOU!  I was working on this issue for over 5 hours and you solved the mystery. Thank you so much.

**Comment by moscowbaby** [comment]
Excuse me, I tried to instal as bellow but I got this error

> install.packages(
+     "https://github.com/gagolews/stringi/raw/master/devel/winbuilder/3.5/stringi_1.2.4.zip",
+     repos = NULL,
+ )
Installing package into ‘C:/Users/Minh Nguyen/Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)
trying URL 'https://github.com/gagolews/stringi/raw/master/devel/winbuilder/3.5/stringi_1.2.4.zip'
Warning in install.packages :
  InternetOpenUrl failed: 'The operation timed out'
Error in download.file(p, destfile, method, mode = "wb", ...) : 
  cannot open URL 'https://github.com/gagolews/stringi/raw/master/devel/winbuilder/3.5/stringi_1.2.4.zip'

**Comment by moscowbaby** [comment]
> > InternetOpenUrl failed: 'The operation timed out'
> 
> I have no idea, but it seems you have a network problem. Maybe you can download the zip file via web browser and install it locally with the path to the downloaded file.
> 
> ```r
> install.packages(
>     "/path/to/stringi_1.2.4.zip",
>     repos = NULL
> )
> ```

Thank you very much, it works!
