### ISSUE TITLE
Stringi loading version 1.1.5 on new install of R 3.5.2

### ISSUE THREAD

**Issue by Emma-Elcombe** [gagolews/stringi#307]
Hey, 
I just purcahsed a new Windows laptop and have just installed R (3.2.5) and RStudio on it. 
I'm trying to install dplyr, however it is having dependancy issues which lead back to 'stringr' not installing correctly because it requires 'stringi' version 1.1.7 or above, and when I run Install.Packages("stringi") it loads version 1.1.5.

Thanks for your help
Emma

> install.packages("stringi")
Installing package into �C:/Users/Cat Meow/Documents/R/win-library/3.2�
(as �lib� is unspecified)

  There is a binary version available but the source version is later:
        binary source needs_compilation
stringi  1.1.5  1.2.2              TRUE

  Binaries will be installed
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.2/stringi_1.1.5.zip'
Content type 'application/zip' length 14220135 bytes (13.6 MB)
downloaded 13.6 MB

package ‘stringi’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\Cat Meow\AppData\Local\Temp\RtmpO2rekq\downloaded_packages

> install.packages("stringr")
Installing package into �C:/Users/Cat Meow/Documents/R/win-library/3.2�
(as �lib� is unspecified)
also installing the dependencies �glue�, �stringi�

  There are binary versions available but the source versions are
  later:
        binary source needs_compilation
glue     1.0.0  1.2.0              TRUE
stringi  1.1.5  1.2.2              TRUE
stringr  1.2.0  1.3.1             FALSE

  Binaries will be installed
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.2/glue_1.0.0.zip'
Content type 'application/zip' length 34947 bytes (34 KB)
downloaded 34 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.2/stringi_1.1.5.zip'
Content type 'application/zip' length 14220135 bytes (13.6 MB)
downloaded 13.6 MB

package ‘glue’ successfully unpacked and MD5 sums checked
package ‘stringi’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\Cat Meow\AppData\Local\Temp\RtmpO2rekq\downloaded_packages
installing the source package �stringr�

trying URL 'https://cran.rstudio.com/src/contrib/stringr_1.3.1.tar.gz'
Content type 'application/x-gzip' length 119156 bytes (116 KB)
downloaded 116 KB

* installing *source* package 'stringr' ...
** package 'stringr' successfully unpacked and MD5 sums checked
** R
** data
*** moving datasets to lazyload DB
** inst
** preparing package for lazy loading
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  namespace 'stringi' 1.1.5 is being loaded, but >= 1.1.7 is required
ERROR: lazy loading failed for package 'stringr'
* removing 'C:/Users/Cat Meow/Documents/R/win-library/3.2/stringr'
Warning in install.packages :
  running command '"C:/PROGRA~1/R/R-32~1.5/bin/x64/R" CMD INSTALL -l "C:\Users\Cat Meow\Documents\R\win-library\3.2" C:\Users\CATMEO~1\AppData\Local\Temp\RtmpO2rekq/downloaded_packages/stringr_1.3.1.tar.gz' had status 1
Warning in install.packages :
  installation of package ‘stringr’ had non-zero exit status

The downloaded source packages are in
	‘C:\Users\Cat Meow\AppData\Local\Temp\RtmpO2rekq\downloaded_packages’

**Comment by gagolews** [comment]
Try with the most recent version of R.
