### ISSUE TITLE
stri_trans_general("Ёё","russian-latin/bgn") yields "Ëyë"

### ISSUE THREAD

**Issue by victorn1** [gagolews/stringi#308]
>\> stri_trans_general("Ёё","russian-latin/bgn")
[1] "Ëyë"

The letters "ё" are not held correctly for "russian-latin/bgn" transcoding. Please add conversion of "ё" to latin "e", not to unicode "ё".

(R 3.5.0 i386, RStudio, Windows 7)

**Comment by gagolews** [comment]
This is defined by the ICU lib, not part of stringi.
