### ISSUE TITLE
Edge case which survives "empty search patterns are not supported"

### ISSUE THREAD

**Issue by tdeenes** [gagolews/stringi#309]
Base R does not save you from using an empty search pattern, which must be an unintended scenario in 99.9% of the use cases:
```
grepl("", "This will be always TRUE for a not-NA & not-0-length character string")
```

stringi seemingly tries to warn you:
```
stri_detect_regex("This will be always true for a not-NA & not-0-length character string", "")
```

...but not perfectly:
```
stri_detect_regex("This will be always true for a not-NA & not-0-length character string", "|")
```

I ran into this error when I mistakenly forgot an `|` at the end of a search pattern, e.g.:
```
stri_detect_regex("This will be always true for a not-NA & not-0-length character string", "^That|")
```

I think it would be nice to check if a regex search pattern consists of a trailing or closing or doubled `|` character. I also understand that this check would take some time if the search pattern is a long character vector, so maybe this check should be made optional.

**Comment by gagolews** [comment]
Sorry, out of scope of stringi, this should be implemented on the ICU side.
