### ISSUE TITLE
nchar now handles NAs properly, doc doesn't reflect this

### ISSUE THREAD

**Issue by moodymudskipper** [gagolews/stringi#310]
from `?stri_isempty`

> Missing values are handled properly, as opposed to the built-in nzchar function.

from `?stri_numbytes`

> Missing values are handled properly, as opposed to the built-in nchar(str, "bytes") function
> call

from `?stri_length`

> Missing values are handled properly, as opposed to the built-in nchar function. For ‘byte‘ encodings
> we get, as usual, an error.

from `?stri_width`'s examples : 

```
nchar(stri_trans_nfkd("\u0105"), "width") # provides incorrect information
stri_width(stri_trans_nfkd("\u0105"))
```

Though they return the same.

**Comment by gagolews** [comment]
Thanks for pointing this out.
