### ISSUE TITLE
downloading stringi in workspace without internet 

### ISSUE THREAD

**Issue by stilldre08** [gagolews/stringi#311]
I'm trying to download stringi on a computer with no internet access. 
I followed the instructions on 'Installing Stringi' regarding my situation and I was able to download 
stringi ver 0.1.0
However, I need a version that's over 1.1.7 and I would appreciate it if I could get instructions on how to do so.

**Comment by gagolews** [comment]
see https://stackoverflow.com/questions/31942322

btw, stringi_1.2.3 is now on CRAN
