### ISSUE TITLE
stringi 1.1.7

### ISSUE THREAD

**Issue by vicad** [gagolews/stringi#312]
Hello, 

I am having this issue with downloading swirl on R.
> library(swirl)
Error: package or namespace load failed for ‘swirl’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 namespace ‘stringi’ 1.1.6 is being loaded, but >= 1.1.7 is required

I then tried to install stringi 1.1.7 but could not open the link to get it. 
Object not found!

The requested URL was not found on this server. The link on the referring page seems to be wrong or outdated. Please inform the author of that page about the error.

"If you think this is a server error, please contact the webmaster.

Error 404

cran.r-project.org
Apache/2.4.10 (Debian)"

Can I get help with downloading it.

Thanks. 👍

**Comment by gagolews** [comment]
stringi_1.2.3 have been released very recently. Windows builds should be available soon.
