### ISSUE TITLE
test U_CHARSET_IS_UTF8 in configure when using pkg-build

### ISSUE THREAD

**Issue by gagolews** [gagolews/stringi#314]
Seems like Manjaro's (might be the case of other distribs too) system icu was build with `U_CHARSET_IS_UTF8` on

`./configure` should check that and, if this is the case, and build icu from sources

**Comment by gagolews** [comment]
building icu from sources is not enought if `libR` is linked against system icu anyway, should enable renaming?

**Comment by QuLogic** [comment]
Does this break something in particular? The change is not specific to Manjaro; ICU itself has flipped the flag for all Linux systems with version 61: https://github.com/unicode-org/icu/commit/d7482c9720b4f71dd9dad030ec7a1c10bf1ccec2
