### ISSUE TITLE
"embedded nul in string" when using stri_rand_shuffle

### ISSUE THREAD

**Issue by brainprint** [gagolews/stringi#319]
Hi,

First, thank you for your package.

Running a stri_rand_shuffle() for a long character vector I got this error.

```
Error in stri_rand_shuffle(iNames) : 
  embedded nul in string: something \0 something
```

A toy example is

```
library(charlatan)
library(stringi)

kN <- 1e2
iNames <- ch_name(kN)
print(stri_enc_isascii(iNames)) # All are ASCII
nNames <- stri_rand_shuffle(iNames)
```

The problem happens for a vector size about 100 or higher, but not for 10.

Not sure if it would be useful, but from `?Quotes`:

```
## nul characters (for terminating strings in C) are not allowed (parse errors)
## Not run: 
  "foo\0bar"     # Error: nul character not allowed (line 1)
  "foo\u0000bar" # same error
```

My R is 3.5.1, Mac + RStudio. If more info would be required, please, let me know.

**Comment by gagolews** [comment]
Thanks for noticing that, fix on the way.
