### ISSUE TITLE
Issue while updating Stringi 1.1.7 to stringi 1.2.4

### ISSUE THREAD

**Issue by iamrksahu** [gagolews/stringi#321]
I have installed the R version 3.5.1 and when i try to update all the installed packages, all successfully gets updated except stringi. the version of stringi installed is 1.1.7 and when i check the updated version, it says stringi 1.2.4 is available. But unfortunately due to some reason it does not update. Below is the response

install.packages("stringi")
Installing package into ‘C:/Users/Rxxxx/Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)

  There is a binary version available but the source version is later:
        binary source needs_compilation
stringi  1.1.7  1.2.4              TRUE

  Binaries will be installed
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.5/stringi_1.1.7.zip'
Content type 'application/zip' length 14368013 bytes (13.7 MB)
downloaded 13.7 MB

package ‘stringi’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\Rxxxx\AppData\Local\Temp\RtmpsPTZn2\downloaded_packages

Help me with it. I tried to check the closed issues but could not fix it.

**Comment by gagolews** [comment]
Please do check the previous github issues for similar topics, especially #320 and references therein.
