### ISSUE TITLE
Require bash for configure

### ISSUE THREAD

**Issue by xiamaz** [gagolews/stringi#325]
The current autoconf generate configure file uses `#!/bin/sh` as the shebang, although the generated configure script will fail when run with `dash` symlinked to sh, which enforces POSIX sh much more strictly. Changing the shebang to /bin/bash fixes the issue.

**Comment by gagolews** [comment]
I don't think it's a good idea.

> In particular bash extensions must not be used, and not all R platforms have a bash command, let alone one at /bin/bash. 

see https://cran.r-project.org/doc/manuals/r-release/R-exts.html

**Comment by xiamaz** [comment]
But the autoconf script does not work using `dash` as the standard shell. If it is related to issues in POSIX compatibility, this should be considered a bug.

**Comment by gagolews** [comment]
this is generated by `autoconf`, possible solution is https://stackoverflow.com/questions/161064

I'll stick to what *Writing R Extensions* say about the location of bash
