### ISSUE TITLE
Stringi gives error

### ISSUE THREAD

**Issue by kambanane** [gagolews/stringi#326]
Hello, 

I get this error when trying to load stringi:

Error: package ‘stringi’ is not installed for 'arch = x64'

Running: version.string R version 3.5.1 (2018-07-02)
platform       x86_64-w64-mingw32          
arch           x86_64                      
os             mingw32                     
system         x86_64, mingw32

I am not sure what to do, but now I cannot run my code. I tried to simply get the functions and include it in my code, but there are a number of dependencies that I also cannot get. 

Any help would be appreciated.

**Comment by kambanane** [comment]
Worse yet, for some reason I can't even uninstall stringi. Despite it being listed as an installed app, when I attempt to remove it, it claims it isn't there. 

Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called ‘stringi’

So now, I cannot publish any RMarkdown docs because it throws an error. 

What am I to do with all of this? My workday appears to have been compromised by a single package, unfortunately.

**Comment by kambanane** [comment]
SOLVED: Installed from the .zip and all is fine.

**Comment by gagolews** [comment]
Sorry, on vacations now, the related issue was #313
