### ISSUE TITLE
stri_split_regex() - not working for \\p{Z} ??

### ISSUE THREAD

**Issue by kbenoit** [gagolews/stringi#327]
Maybe I'm daft here, but why does the first one not work?
```r
> stringi::stri_split_regex("one\ntwo\tthree", "\\p{Z}+")
[[1]]
[1] "one\ntwo\tthree"

> stringi::stri_split_regex("one\ntwo\tthree", "\\p{WHITE_SPACE}+")
[[1]]
[1] "one"   "two"   "three"
```

**Comment by gagolews** [comment]
Hi Ken, see Table 12 in http://www.unicode.org/reports/tr44/tr44-21.html

http://www.fileformat.info/info/unicode/char/000A/index.htm

newline is `\p{Cc}`

**Comment by gagolews** [comment]
http://www.fileformat.info/info/unicode/char/000A/index.htm
