### ISSUE TITLE
Need icudt61b.zip for big-endian

### ISSUE THREAD

**Issue by ginggs** [gagolews/stringi#334]
I've just run into #314 since  Debian and Ubuntu are moving to ICU 63.1.

On little-endian architectures, building against the bundled icu61 is successful, however it fails on big-endian systems because the data cannot be found.

**Comment by xnox** [comment]
I got icu 61.1 sources (it has the same checksum for the icudt61l.dat as the one already shipped)

Changed to `#   define U_CHARSET_IS_UTF8 0`

Rebuilt everything, with `--with-data-packaging=archive`

Created a zip of the resulting .dat with a license file.

Please see attached.

**Comment by xnox** [comment]
[icudt61b.zip](https://github.com/gagolews/stringi/files/2585391/icudt61b.zip)

[icudt61b.zip.asc.txt](https://github.com/gagolews/stringi/files/2585393/icudt61b.zip.asc.txt)

**Comment by gagolews** [comment]
Thanks! Fix on the way.
