### ISSUE TITLE
libicu-dev not found on Debian

### ISSUE THREAD

**Issue by jeroen** [gagolews/stringi#340]
Latest Debian 'testing' (Buster) with `libicu-dev` and `pkg-config` installed gives:

```
*** stringi configure summary:
    ICU_FOUND=0
    ICUDT_DIR=icu61/data
    ICU_BUNDLE_VERSION=61
    ICUDT_ENDIANNESS=little
    STRINGI_CXXSTD=CXX_STD=CXX11
    STRINGI_CFLAGS=   -fpic
```

**Comment by gagolews** [comment]
Could you pls provide the full `./configure` output? I shall be fixing that this week

**Comment by gagolews** [comment]
@jeroen (hi there by the way!) now with #335 fixed, it's possible that it's not an issue anymore

can you re-check now?

**Comment by jeroen** [comment]
You are right it works now in the github version.
