### ISSUE TITLE
unable to install stringi

### ISSUE THREAD

**Issue by march3032** [gagolews/stringi#351]
I want to play sparkR on my own server,and when i install stringi dependencies by "R CMD INSTALL stringi_1.4.3.tar.gz" there comes a error like this :
checking whether std::map is available... yes
checking for pkg-config... (cached) /usr/bin/pkg-config
checking with pkg-config for the system ICU4C... no
*** pkg-config did not detect ICU4C-devel libraries installed
*** Trying with "standard" fallback flags
checking whether we may build an ICU4C-based project... no
*** The available ICU4C cannot be used
checking whether we may compile src/icu55/common/umapfile.c... yes
checking whether we may compile src/icu55/common/putil.cpp... yes
checking whether we can fetch icudt... downloading the ICU data library (icudt)
output path: icu55/data/icudt55l.zip
trying URL 'http://www.ibspan.waw.pl/~gagolews/stringi/icudt55l.zip'
Error in download.file(paste(href, fname, sep = ""), icudtzipfname, mode = "wb"): cannot open URL 'http://www.ibspan.waw.pl/~gagolews/stringi/icudt55l.zip'

Error in download.file(paste(href, fname, sep = ""), icudtzipfname, mode = "wb"): unsupported URL scheme

Error in download.file(paste(href, fname, sep = ""), icudtzipfname, mode = "wb"): unsupported URL scheme

trying URL 'http://raw.githubusercontent.com/gagolews/stringi/master/src/icu61/data/icudt55l.zip'
Error in download.file(paste(href, fname, sep = ""), icudtzipfname, mode = "wb"): cannot open URL 'http://raw.githubusercontent.com/gagolews/stringi/master/src/icu61/data/icudt55l.zip'

trying URL 'http://raw.githubusercontent.com/gagolews/stringi/master/src/icu55/data/icudt55l.zip'
Error in download.file(paste(href, fname, sep = ""), icudtzipfname, mode = "wb"): cannot open URL 'http://raw.githubusercontent.com/gagolews/stringi/master/src/icu55/data/icudt55l.zip'

trying URL 'http://www.gagolewski.com/software/stringi/icudt55l.zip'
Error in download.file(paste(href, fname, sep = ""), icudtzipfname, mode = "wb"): cannot open URL 'http://www.gagolewski.com/software/stringi/icudt55l.zip'

icudt download failed
Error: Stopping on error
In addition: Warning messages:
1: In download.file(paste(href, fname, sep = ""), icudtzipfname, mode = "wb") :
  unable to resolve 'www.ibspan.waw.pl'
2: In download.file(paste(href, fname, sep = ""), icudtzipfname, mode = "wb") :
  unable to resolve 'raw.githubusercontent.com'
3: In download.file(paste(href, fname, sep = ""), icudtzipfname, mode = "wb") :
  unable to resolve 'raw.githubusercontent.com'
4: In download.file(paste(href, fname, sep = ""), icudtzipfname, mode = "wb") :
  unable to resolve 'www.gagolewski.com'
Execution halted
*** icudt download failed. stopping.
ERROR: configuration failed for package ‘stringi’
* removing ‘/usr/local/lib64/R/library/stringi’
what should i do ,  my server can not visit internet , so i'm confused

**Comment by gagolews** [comment]
This issue has had been addressed many times, see, e.g., https://stackoverflow.com/questions/31942322/how-to-install-stringi-from-local-file-absolutely-no-internet-access

**Comment by march3032** [comment]
> This issue has had been addressed many times, see, e.g., https://stackoverflow.com/questions/31942322/how-to-install-stringi-from-local-file-absolutely-no-internet-access

thanku very much~
