### ISSUE TITLE
unexpected behavior: stri_detect_fixed

### ISSUE THREAD

**Issue by ucb** [gagolews/stringi#356]
` stri_detect_fixed(c("stringi R", "REXAMINE", "123"), c('R', '0'))`
`[1]  TRUE FALSE FALSE`
Why isn't the second string matched to "R"?

I also get wrong dimensionality:
`  nums=c("zero","one","two","three","four","five","six","seven","eight","nine",         "ten","eleven","twelve","thirteen","fourteen","fifteen","sixteen","seventeen","eighteen","nineteen",
         "twenty","thirty","forty","fifty","sixty","seventy","eighty","ninety",
         "hundred","thousand","million","billion","trillion")`
`stri_detect_fixed(c("thousand","Thousand","Thousands"),nums,opts_fixed=stri_opts_fixed(case_insensitive=TRUE))`
` [1] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE  TRUE FALSE FALSE FALSE`

I am expecting output of length 3, as above, but I get the length of the pattern and the string vector is matched to pattern instead.

**Comment by gagolews** [comment]
Because of the recycling rule + vectorisation.

paste() (among many others) has the same behaviour:

```
paste(c("stringi R", "REXAMINE", "123"), c('R', '0'))
[1] "stringi R R" "REXAMINE 0"  "123 R"     
```

See `?"stringi-arguments"` for more info.

**Comment by ucb** [comment]
I know how paste works but from the function description you assume particular behavior: `Description: These functions determine, for each string in str, if there is at least one match to a corresponding pattern.`

So does one need to do to get the advertised functionality to work?

I.e. to get a vector of length(str) with T if at least one pattern fits, and F otherwise.

**Comment by gagolews** [comment]
you could try  a regex (`stri_detect_regex`),  if you seek *some* match, e.g., `R|0`

HTH
