### ISSUE TITLE
unable to load shared object 

### ISSUE THREAD

**Issue by Enlitech** [gagolews/stringi#357]
I got the following error when installing the stringi package. 

I am wondering why... 

** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for ‘stringi’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/Users/Junchao/anaconda3/lib/R/library/00LOCK-stringi/00new/stringi/libs/stringi.dylib':
  dlopen(/Users/Junchao/anaconda3/lib/R/library/00LOCK-stringi/00new/stringi/libs/stringi.dylib, 6): Symbol not found: __ZN6icu_558ByteSink15GetAppendBufferEiiPciPi
  Referenced from: /Users/Junchao/anaconda3/lib/R/library/00LOCK-stringi/00new/stringi/libs/stringi.dylib
  Expected in: flat namespace
 in /Users/Junchao/anaconda3/lib/R/library/00LOCK-stringi/00new/stringi/libs/stringi.dylib
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/Users/Junchao/anaconda3/lib/R/library/stringi’

**Comment by gagolews** [comment]
Could you try restarting R and reinstalling `stringi`? If this doesn't help, I think I will need a full output from the build stack.

**Comment by Enlitech** [comment]
Thanks for reply. I finally managed to circumvent this problem. 

I had to install stringi from conda channel, like: 

conda install -c r r-stringi. 

instead of installing it in R

> Could you try restarting R and reinstalling `stringi`? If this doesn't help, I think I will need a full output from the build stack.

**Comment by colinbrislawn** [comment]
I also solved this issue by fixing my channels:

```
conda config --add channels conda-forge
conda config --add channels defaults
conda config --add channels r
conda config --add channels bioconda
```
Then I removed the environment and reinstalled.
