### ISSUE TITLE
A pattern feature for stri_sort and stri_order?

### ISSUE THREAD

**Issue by iago-pssjd** [gagolews/stringi#358]
It's just an idea. Let's see an example:
```
> stringi::stri_sort(c("a_1","a_2","b_1","b_2"))
[1] "a_1" "a_2" "b_1" "b_2"
> stringi::stri_sort(c("a_1","a_2","b_1","b_2"), numeric = T)
[1] "a_1" "a_2" "b_1" "b_2"
```
But I may expect from the last instruction the output ` "a_1" "b_1" "a_2" "b_2"`.
Well, maybe not, but if I had a `pattern` option to do
```
stringi::stri_sort(c("a_1","a_2","b_1","b_2"), numeric = T, pattern = "_[0-9]")
```
which would sort by the substrings captured by the pattern and I would get my expected output.

Would be such an option possible? I raise it since meanwhile, it is a bit cumbersome to produce such an output, at least in certain situations.

Thank you for the package.

**Comment by gagolews** [comment]
Yeah, nah, interesting, but stringi is supposed to be a little bit lower-level.
You can emulate it manually (with sub/extract, order, join I guess).
