### ISSUE TITLE
str_cmp_eq(): unexpected behavior when using with tibble

### ISSUE THREAD

**Issue by ziahydari** [gagolews/stringi#359]
Greetings: I will upload four code snippets to demonstrate unexpected behavior of str_cmp_eq() with tibble and related functions.  

SNIPPET ONE:  fails, although I would have expected it to work
SNIPPET TWO:  works
SNIPPET THREE:  throws erroneous output although I would have expected it to stop.
SNIPPET FOUR:  works

```
## SNIPPET ONE
df <- tibble(Name1=c("Smith, Peter", "Wozoski, Mike"), Name3=c("Smith, Mike", "Wozoski, Mike"))
df <- df %>% add_column(namesEqual=stri_cmp_eq(Name1, Name3))
df %>% select(Name1)

## SNIPPET TWO
df <- tibble(Name1=c("Smith, Peter", "Wozoski, Mike"), Name3=c("Smith, Mike", "Wozoski, Mike"))
df <- df %>% add_column(namesEqual=stri_cmp_eq(df$Name1, df$Name3))
df

## SNIPPET THREE
df <- tibble(Name1=c("Smith, Peter", "Wozoski, Mike"), Name3=c("Smith, Mike", "Wozoski, Mike"))
df <- df %>% add_column(namesEqual=stri_cmp_eq(df[1], df[2]))
df

## SNIPPET FOUR
df <- tibble(Name1=c("Smith, Peter", "Wozoski, Mike"), Name3=c("Smith, Mike", "Wozoski, Mike"))
attach(df)
namesEqualTemp <- stri_cmp_eq(Name1, Name3)
detach(df)
df <- df %>% 
  add_column(namesEqual=namesEqualTemp)
df

```

**Comment by gagolews** [comment]
`df[1]` is not a synonym for `df$Name1`, `df[[1]]` is.
`df[1]` returns a data frame with one column, whereas `df[[1]]` -- extracts the column as a vector

**Comment by gagolews** [comment]
For first example, you'll get `object 'Name1' not found`.

**Comment by gagolews** [comment]
(this issue is not related to stringi)

**Comment by ziahydari** [comment]
Many thanks for your reply.  

For (1), I now see why ... add_column() man page says: 

> However, unlike in dplyr verbs, columns in .data are not available for the expressions. Use dplyr::mutate() if you need to add a column based on existing data.
