### ISSUE TITLE
Inconsistent behaviour of stri_split_boundaries for emojis

### ISSUE THREAD

**Issue by JBGruber** [gagolews/stringi#361]
First of all, thank you @gagolews and the other contributors for this amazing package which makes string hacking in `R` a delight!

Now the issue: I noticed that `stri_split_boundaries` shows inconsistent behaviour on different systems when splitting emojis. Here is a small reprex:

```
stringi::stri_split_boundaries("👌🏻", type = "character")[[1]]
```
The string here consists of one emoji characters: "OK hand: light skin tone". On my Ubuntu machine, this is detected correctly. However, on travis and [rstudio.cloud/](https://rstudio.cloud/) the string is split into two parts: "OK hand" and "light skin tone". 

I know that both could be considered correct as the emoji technically consists of two Unicode characters. But I didn't expect different behaviours on different machines. Is there a way to prevent this or is this a bug?

**Comment by gagolews** [comment]
Yes! Stringi has been developed with reproducibility in mind. However,  the main bottleneck is the ICU library here. Different versions of ICU might yield different results, e.g., the support for emojis has been added very recently so it is likely that you use a newer version than the one in the cloud.

On Linux/UNIX, to assure reproducibility, it is best to disable the use of the system ICU via a call to

```
install.packages("stringi", configure.args="--disable-pkg-config")
```

Windows and OS X binary builds on CRAN use exactly that by the way.

See https://cran.r-project.org/web/packages/stringi/INSTALL for more details.

HTH

**Comment by JBGruber** [comment]
Thanks a lot! Quick, short and correct answer!
