### ISSUE TITLE
Ubuntu Trusty no longer supported

### ISSUE THREAD

**Issue by javierluraschi** [gagolews/stringi#366]
Looks like https://github.com/gagolews/stringi/commit/476e086519c1699be2be51a35ddfd1ca96b6702c started using `icu_52::RegexMatcher::find(UErrorCode&)`; however, this function requires ICU55: https://unicode-org.github.io/icu-docs/apidoc/released/icu4c/classicu_1_1RegexMatcher.html#aa31dd2acd711c1875b2402f5c940f67d

At the very least, https://github.com/gagolews/stringi/blob/master/DESCRIPTION#L18 should be updated.

See for instance: https://travis-ci.org/sparklyr/sparklyr/jobs/635014707?utm_medium=notification&utm_source=github_status with Travis output.

```
stri_search_regex_count.cpp:92:48: error: no matching function for call to ‘icu_52::RegexMatcher::find(UErrorCode&)’
          int m_res = (bool)matcher->find(status);
                                                ^
stri_search_regex_count.cpp:92:48: note: candidates are:
In file included from stri_container_regex.h:37:0,
                 from stri_search_regex_count.cpp:35:
/usr/include/x86_64-linux-gnu/unicode/regex.h:810:19: note: virtual UBool icu_52::RegexMatcher::find()
     virtual UBool find();
                   ^
/usr/include/x86_64-linux-gnu/unicode/regex.h:810:19: note:   candidate expects 0 arguments, 1 provided
/usr/include/x86_64-linux-gnu/unicode/regex.h:822:19: note: virtual UBool icu_52::RegexMatcher::find(int64_t, UErrorCode&)
     virtual UBool find(int64_t start, UErrorCode &status);
                   ^
/usr/include/x86_64-linux-gnu/unicode/regex.h:822:19: note:   candidate expects 2 arguments, 1 provided
```

**Comment by gagolews** [comment]
You're absolutely right, thanks!!!!
