### ISSUE TITLE
Struggling to get working with AWS Lambda deployment

### ISSUE THREAD

**Issue by 4rutnv3g** [gagolews/stringi#374]
Hi there

I am in the process of deploying some R code to AWS Lambda. I have been able to set up a runtime with a number of external packages, but attempting to load `stringi` is causing the following error:
    `unable to load shared object '/opt/R/library/stringi/libs/stringi.so':
  libicui18n.so.60: cannot open shared object file: No such file or directory`
I am hoping maybe you can point me to the part of the package that interacts with the file `libicui18n.so.60` so that I can attempt a workaround?

Many thanks

**Comment by gagolews** [comment]
Do you have `libicu-dev` (debian/ubuntu) or `libicu-devel` (redhat/centos/fedora) installed?
Also, try re-installing stringi.

**Comment by 4rutnv3g** [comment]
Thanks for replying so quickly.

There is very little OS-level control afforded when using AWS Lambda but [this](https://gist.github.com/vladgolubev/1dac4ed47a5febf110c668074c6b671c) page indicates that the package `libicu.x86_64` is available, but not libicu-devel (I believe amazonlinux is evolved from redhat/centos). If necessary it may be possible to include it in the deployment package.

The package is added to the Lambda function by uploading its site-library folder in a zip archive so it is effectively installed each time the function is run.

I understand this is not an issue directly caused by stringi so I greatly appreciate the efforts you have taken to assist me.

**Comment by gagolews** [comment]
Maybe this will help? https://stackoverflow.com/questions/31942322/how-to-install-stringi-from-local-file-absolutely-no-internet-access

**Comment by gagolews** [comment]
closing as inactive for a long time
