### ISSUE TITLE
Breaking change: `stri_c()` now returns an empty string when input is empty and `collapse` is set.

### ISSUE THREAD

**Issue by markusdumke** [gagolews/stringi#375]
I noticed that my code broke after upgrading `stringi` to 1.4.6. 
It is due to the new behaviour of `stri_c `with `collapse` argument and zero length inputs as I have been relying on the fact that the return has length 0 as well.

This is declared as a new feature, but I think it should be declared as a Breaking Change, so users are warned.

**Comment by gagolews** [comment]
Thanks, right, I'll update the `NEWS` file.
