### ISSUE TITLE
Compilation errors Ubuntu 16.04 R3.6

### ISSUE THREAD

**Issue by slagtermaarten** [gagolews/stringi#378]
Hi, thanks for developing this package! I've tried all the installation commands listed here: #296, but to no avail. Am I missing something?

> install.packages('stringi')
trying URL 'https://cran.rstudio.com/src/contrib/stringi_1.4.6.tar.gz'
Content type 'application/x-gzip' length 7284354 bytes (6.9 MB)
==================================================
downloaded 6.9 MB

* installing *source* package ‘stringi’ ...
** package ‘stringi’ successfully unpacked and MD5 sums checked
** using staged installation
checking for R_HOME... /home/m.slagter/conda/envs/r36/lib/R
checking for R... /home/m.slagter/conda/envs/r36/lib/R/bin/R
checking for endianness... little
checking for R >= 3.1.0 for C++11 use... yes
checking for R < 3.4.0 for CXX1X flag use... no
checking for cat... /bin/cat
checking for local ICUDT_DIR... icu61/data
checking for gcc... x86_64-conda_cos6-linux-gnu-cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether x86_64-conda_cos6-linux-gnu-cc accepts -g... yes
checking for x86_64-conda_cos6-linux-gnu-cc option to accept ISO C89... none needed
checking how to run the C preprocessor... x86_64-conda_cos6-linux-gnu-cc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking elf.h usability... yes
checking elf.h presence... yes
checking for elf.h... yes
checking whether we are using the GNU C++ compiler... yes
checking whether x86_64-conda_cos6-linux-gnu-c++ -std=gnu++11 accepts -g... yes
checking whether the C++ compiler supports the long long type... yes
checking whether the compiler implements namespaces... yes
checking whether the compiler supports Standard Template Library... yes
checking whether std::map is available... yes
checking for pkg-config... /usr/bin/pkg-config
checking with pkg-config for the system ICU4C... 55.1
checking for ICU4C >= 55... yes
checking for additional required CPPFLAGS, LDFLAGS, and LIBS... done
checking whether we may build an ICU4C-based project... yes
checking programmatically for sufficient U_ICU_VERSION_MAJOR_NUM... yes
checking programmatically if U_CHARSET_IS_UTF8 is defined and set... no
checking for available ICU data library (ucnv, uloc, utrans)... yes
checking for available ICU data library (ucol)... yes
configure: creating ./config.status
config.status: creating src/Makevars
config.status: creating src/uconfig_local.h
config.status: creating src/install.libs.R

*** stringi configure summary:
    ICU_FOUND=1
    STRINGI_CXXSTD=CXX_STD=CXX11
    STRINGI_CFLAGS=   -fpic
    STRINGI_CPPFLAGS=-I. -I/usr/include/x86_64-linux-gnu   -UDEBUG -DNDEBUG -DU_HAVE_ELF_H
    STRINGI_CXXFLAGS=   -fpic
    STRINGI_LDFLAGS=-L/usr/lib/x86_64-linux-gnu
    STRINGI_LIBS=-licui18n -licuuc -licudata

*** compiler settings used:
    CC=x86_64-conda_cos6-linux-gnu-cc
    LD=x86_64-conda_cos6-linux-gnu-c++ -std=gnu++11
    CFLAGS=-march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/m.slagter/conda/envs/r36/include -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/r-base_1580939145230/work=/usr/local/src/conda/r-base-3.6.2 -fdebug-prefix-map=/home/m.slagter/conda/envs/r36=/usr/local/src/conda-prefix -fpic
    CPPFLAGS=-DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/m.slagter/conda/envs/r36/include -I/home/m.slagter/conda/envs/r36/include -Wl,-rpath-link,/home/m.slagter/conda/envs/r36/lib   -UDEBUG -DNDEBUG
    CXX=x86_64-conda_cos6-linux-gnu-c++ -std=gnu++11
    CXXFLAGS=-fvisibility-inlines-hidden -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/m.slagter/conda/envs/r36/include -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/r-base_1580939145230/work=/usr/local/src/conda/r-base-3.6.2 -fdebug-prefix-map=/home/m.slagter/conda/envs/r36=/usr/local/src/conda-prefix -fpic
    LDFLAGS=
    LIBS=

** libs
x86_64-conda_cos6-linux-gnu-c++ -std=gnu++11 -I"/home/m.slagter/conda/envs/r36/lib/R/include" -DNDEBUG -I. -I/usr/include/x86_64-linux-gnu   -UDEBUG -DNDEBUG -DU_HAVE_ELF_H  -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/m.slagter/conda/envs/r36/include -I/home/m.slagter/conda/envs/r36/include -Wl,-rpath-link,/home/m.slagter/conda/envs/r36/lib -fpic -fpic  -fvisibility-inlines-hidden  -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/m.slagter/conda/envs/r36/include -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/r-base_1580939145230/work=/usr/local/src/conda/r-base-3.6.2 -fdebug-prefix-map=/home/m.slagter/conda/envs/r36=/usr/local/src/conda-prefix  -c stri_brkiter.cpp -o stri_brkiter.o
In file included from /DATA/users/m.slagter/conda.bu/envs/r36/x86_64-conda_cos6-linux-gnu/sysroot/usr/include/math.h:71:0,
                 from /DATA/users/m.slagter/conda.bu/envs/r36/x86_64-conda_cos6-linux-gnu/include/c++/7.3.0/cmath:45,
                 from /home/m.slagter/conda/envs/r36/lib/R/include/R.h:50,
                 from stri_external.h:67,
                 from stri_stringi.h:36,
                 from stri_brkiter.cpp:32:
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:63:16: error: expected constructor, destructor, or type conversion before '(' token
 __MATHCALL_VEC (cos,, (_Mdouble_ __x));
                ^
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:65:16: error: expected constructor, destructor, or type conversion before '(' token
 __MATHCALL_VEC (sin,, (_Mdouble_ __x));
                ^
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:81:22: error: 'sincos' has not been declared
 __MATHDECL_VEC (void,sincos,,
                      ^~~~~~
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:81:29: error: expected identifier before ',' token
 __MATHDECL_VEC (void,sincos,,
                             ^
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:82:3: error: expected identifier before '(' token
   (_Mdouble_ __x, _Mdouble_ *__sinx, _Mdouble_ *__cosx));
   ^
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:82:57: error: expected constructor, destructor, or type conversion before ';' token
   (_Mdouble_ __x, _Mdouble_ *__sinx, _Mdouble_ *__cosx));
                                                         ^
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:100:16: error: expected constructor, destructor, or type conversion before '(' token
 __MATHCALL_VEC (exp,, (_Mdouble_ __x));
                ^
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:109:16: error: expected constructor, destructor, or type conversion before '(' token
 __MATHCALL_VEC (log,, (_Mdouble_ __x));
                ^
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:153:16: error: expected constructor, destructor, or type conversion before '(' token
 __MATHCALL_VEC (pow,, (_Mdouble_ __x, _Mdouble_ __y));
                ^
In file included from /DATA/users/m.slagter/conda.bu/envs/r36/x86_64-conda_cos6-linux-gnu/sysroot/usr/include/math.h:94:0,
                 from /DATA/users/m.slagter/conda.bu/envs/r36/x86_64-conda_cos6-linux-gnu/include/c++/7.3.0/cmath:45,
                 from /home/m.slagter/conda/envs/r36/lib/R/include/R.h:50,
                 from stri_external.h:67,
                 from stri_stringi.h:36,
                 from stri_brkiter.cpp:32:
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:63:16: error: expected constructor, destructor, or type conversion before '(' token
 __MATHCALL_VEC (cos,, (_Mdouble_ __x));
                ^
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:65:16: error: expected constructor, destructor, or type conversion before '(' token
 __MATHCALL_VEC (sin,, (_Mdouble_ __x));
                ^
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:81:22: error: 'sincos' has not been declared
 __MATHDECL_VEC (void,sincos,,
                      ^~~~~~
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:81:29: error: expected identifier before ',' token
 __MATHDECL_VEC (void,sincos,,
                             ^
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:82:3: error: expected identifier before '(' token
   (_Mdouble_ __x, _Mdouble_ *__sinx, _Mdouble_ *__cosx));
   ^
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:82:57: error: expected constructor, destructor, or type conversion before ';' token
   (_Mdouble_ __x, _Mdouble_ *__sinx, _Mdouble_ *__cosx));
                                                         ^
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:100:16: error: expected constructor, destructor, or type conversion before '(' token
 __MATHCALL_VEC (exp,, (_Mdouble_ __x));
                ^
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:109:16: error: expected constructor, destructor, or type conversion before '(' token
 __MATHCALL_VEC (log,, (_Mdouble_ __x));
                ^
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:153:16: error: expected constructor, destructor, or type conversion before '(' token
 __MATHCALL_VEC (pow,, (_Mdouble_ __x, _Mdouble_ __y));
                ^
In file included from /DATA/users/m.slagter/conda.bu/envs/r36/x86_64-conda_cos6-linux-gnu/sysroot/usr/include/math.h:141:0,
                 from /DATA/users/m.slagter/conda.bu/envs/r36/x86_64-conda_cos6-linux-gnu/include/c++/7.3.0/cmath:45,
                 from /home/m.slagter/conda/envs/r36/lib/R/include/R.h:50,
                 from stri_external.h:67,
                 from stri_stringi.h:36,
                 from stri_brkiter.cpp:32:
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:63:16: error: expected constructor, destructor, or type conversion before '(' token
 __MATHCALL_VEC (cos,, (_Mdouble_ __x));
                ^
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:65:16: error: expected constructor, destructor, or type conversion before '(' token
 __MATHCALL_VEC (sin,, (_Mdouble_ __x));
                ^
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:81:22: error: 'sincos' has not been declared
 __MATHDECL_VEC (void,sincos,,
                      ^~~~~~
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:81:29: error: expected identifier before ',' token
 __MATHDECL_VEC (void,sincos,,
                             ^
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:82:3: error: expected identifier before '(' token
   (_Mdouble_ __x, _Mdouble_ *__sinx, _Mdouble_ *__cosx));
   ^
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:82:57: error: expected constructor, destructor, or type conversion before ';' token
   (_Mdouble_ __x, _Mdouble_ *__sinx, _Mdouble_ *__cosx));
                                                         ^
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:100:16: error: expected constructor, destructor, or type conversion before '(' token
 __MATHCALL_VEC (exp,, (_Mdouble_ __x));
                ^
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:109:16: error: expected constructor, destructor, or type conversion before '(' token
 __MATHCALL_VEC (log,, (_Mdouble_ __x));
                ^
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:153:16: error: expected constructor, destructor, or type conversion before '(' token
 __MATHCALL_VEC (pow,, (_Mdouble_ __x, _Mdouble_ __y));
                ^
In file included from /home/m.slagter/conda/envs/r36/lib/R/include/R.h:50:0,
                 from stri_external.h:67,
                 from stri_stringi.h:36,
                 from stri_brkiter.cpp:32:
/DATA/users/m.slagter/conda.bu/envs/r36/x86_64-conda_cos6-linux-gnu/include/c++/7.3.0/cmath:180:11: error: '::cos' has not been declared
   using ::cos;
           ^~~
/DATA/users/m.slagter/conda.bu/envs/r36/x86_64-conda_cos6-linux-gnu/include/c++/7.3.0/cmath:218:11: error: '::exp' has not been declared
   using ::exp;
           ^~~
/DATA/users/m.slagter/conda.bu/envs/r36/x86_64-conda_cos6-linux-gnu/include/c++/7.3.0/cmath:334:11: error: '::log' has not been declared
   using ::log;
           ^~~
/DATA/users/m.slagter/conda.bu/envs/r36/x86_64-conda_cos6-linux-gnu/include/c++/7.3.0/cmath:384:11: error: '::pow' has not been declared
   using ::pow;
           ^~~
/DATA/users/m.slagter/conda.bu/envs/r36/x86_64-conda_cos6-linux-gnu/include/c++/7.3.0/cmath:421:11: error: '::sin' has not been declared
   using ::sin;
           ^~~
make: *** [/home/m.slagter/conda/envs/r36/lib/R/etc/Makeconf:176: stri_brkiter.o] Error 1
ERROR: compilation failed for package ‘stringi’
* removing ‘/DATA/users/m.slagter/conda.bu/envs/r36/lib/R/library/stringi’
* restoring previous ‘/DATA/users/m.slagter/conda.bu/envs/r36/lib/R/library/stringi’

The downloaded source packages are in
        ‘/tmp/RtmpIaXvdM/downloaded_packages’
Warning message:
In install.packages("stringi") :
  installation of package ‘stringi’ had non-zero exit status

**Comment by gagolews** [comment]
Most likely, your build chain is broken. Anaconda seems to be ill-configured. I reckon you are unable to build other packages too (e.g., Rcpp), so this is not stringi-related issues

I recommend you edit the Makeconf file `/path_to_anaconda/lib/R/etc/Makeconf`, e.g., `/opt/anaconda3/lib/R/etc/Makeconf`
and replace all occurrences of `x86_64-conda_cos6-linux-gnu-cc` with `gcc` as well as `x86_64-conda_cos6-linux-gnu-c++` with `g++`

**Comment by slagtermaarten** [comment]
Thanks for your help!

I checked the Makeconf file and it didn't list x86_64-conda_cos6-linux-gnu-cc nor x86_64-conda_cos6-linux-gnu-c++. 
I reinstalled conda, made a new environment with R3.6 in it and tried to install Rcpp, which went fine. But stringi once again gave problems:
>   install.packages('stringi')
trying URL 'https://cran.rstudio.com/src/contrib/stringi_1.4.6.tar.gz'
Content type 'application/x-gzip' length 7284354 bytes (6.9 MB)
==================================================
downloaded 6.9 MB

* installing *source* package ‘stringi’ ...
** package ‘stringi’ successfully unpacked and MD5 sums checked
** using staged installation
checking for R_HOME... /DATA/users/m.slagter/miniconda3/envs/r36/lib/R
checking for R... /DATA/users/m.slagter/miniconda3/envs/r36/lib/R/bin/R
checking for endianness... little
checking for R >= 3.1.0 for C++11 use... yes
checking for R < 3.4.0 for CXX1X flag use... no
checking for cat... /bin/cat
checking for local ICUDT_DIR... icu61/data
checking for gcc... x86_64-conda_cos6-linux-gnu-cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether x86_64-conda_cos6-linux-gnu-cc accepts -g... yes
checking for x86_64-conda_cos6-linux-gnu-cc option to accept ISO C89... none needed
checking how to run the C preprocessor... /DATA/users/m.slagter/miniconda3/envs/r36/bin/x86_64-conda_cos6-linux-gnu-cpp
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking elf.h usability... yes
checking elf.h presence... yes
checking for elf.h... yes
checking whether we are using the GNU C++ compiler... yes
checking whether x86_64-conda_cos6-linux-gnu-c++ -std=gnu++11 accepts -g... yes
checking whether the C++ compiler supports the long long type... yes
checking whether the compiler implements namespaces... yes
checking whether the compiler supports Standard Template Library... yes
checking whether std::map is available... yes
checking for pkg-config... /usr/bin/pkg-config
checking with pkg-config for the system ICU4C... 55.1
checking for ICU4C >= 55... yes
checking for additional required CPPFLAGS, LDFLAGS, and LIBS... done
checking whether we may build an ICU4C-based project... yes
checking programmatically for sufficient U_ICU_VERSION_MAJOR_NUM... yes
checking programmatically if U_CHARSET_IS_UTF8 is defined and set... no
checking for available ICU data library (ucnv, uloc, utrans)... yes
checking for available ICU data library (ucol)... yes
configure: creating ./config.status
config.status: creating src/Makevars
config.status: creating src/uconfig_local.h
config.status: creating src/install.libs.R

*** stringi configure summary:
    ICU_FOUND=1
    STRINGI_CXXSTD=CXX_STD=CXX11
    STRINGI_CFLAGS=   -fpic
    STRINGI_CPPFLAGS=-I. -I/usr/include/x86_64-linux-gnu   -UDEBUG -DNDEBUG -DU_HAVE_ELF_H
    STRINGI_CXXFLAGS=   -fpic
    STRINGI_LDFLAGS=-L/usr/lib/x86_64-linux-gnu
    STRINGI_LIBS=-licui18n -licuuc -licudata

*** compiler settings used:
    CC=x86_64-conda_cos6-linux-gnu-cc
    LD=x86_64-conda_cos6-linux-gnu-c++ -std=gnu++11
    CFLAGS=-march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /DATA/users/m.slagter/miniconda3/envs/r36/include -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/r-base_1587480512619/work=/usr/local/src/conda/r-base-3.6.3 -fdebug-prefix-map=/DATA/users/m.slagter/miniconda3/envs/r36=/usr/local/src/conda-prefix -fpic
    CPPFLAGS=-DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /DATA/users/m.slagter/miniconda3/envs/r36/include -I/DATA/users/m.slagter/miniconda3/envs/r36/include -Wl,-rpath-link,/DATA/users/m.slagter/miniconda3/envs/r36/lib   -UDEBUG -DNDEBUG
    CXX=x86_64-conda_cos6-linux-gnu-c++ -std=gnu++11
    CXXFLAGS=-fvisibility-inlines-hidden -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /DATA/users/m.slagter/miniconda3/envs/r36/include -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/r-base_1587480512619/work=/usr/local/src/conda/r-base-3.6.3 -fdebug-prefix-map=/DATA/users/m.slagter/miniconda3/envs/r36=/usr/local/src/conda-prefix -fpic
    LDFLAGS=
    LIBS=

** libs
x86_64-conda_cos6-linux-gnu-c++ -std=gnu++11 -I"/DATA/users/m.slagter/miniconda3/envs/r36/lib/R/include" -DNDEBUG -I. -I/usr/include/x86_64-linux-gnu   -UDEBUG -DNDEBUG -DU_HAVE_ELF_H  -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /DATA/users/m.slagter/miniconda3/envs/r36/include -I/DATA/users/m.slagter/miniconda3/envs/r36/include -Wl,-rpath-link,/DATA/users/m.slagter/miniconda3/envs/r36/lib -fpic -fpic  -fvisibility-inlines-hidden  -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /DATA/users/m.slagter/miniconda3/envs/r36/include -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/r-base_1587480512619/work=/usr/local/src/conda/r-base-3.6.3 -fdebug-prefix-map=/DATA/users/m.slagter/miniconda3/envs/r36=/usr/local/src/conda-prefix  -c stri_brkiter.cpp -o stri_brkiter.o
In file included from /DATA/users/m.slagter/miniconda3/envs/r36/x86_64-conda_cos6-linux-gnu/sysroot/usr/include/math.h:71:0,
                 from /DATA/users/m.slagter/miniconda3/envs/r36/x86_64-conda_cos6-linux-gnu/include/c++/7.3.0/cmath:45,
                 from /DATA/users/m.slagter/miniconda3/envs/r36/lib/R/include/R.h:50,
                 from stri_external.h:67,
                 from stri_stringi.h:36,
                 from stri_brkiter.cpp:32:
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:63:16: error: expected constructor, destructor, or type conversion before '(' token
 __MATHCALL_VEC (cos,, (_Mdouble_ __x));
                ^
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:65:16: error: expected constructor, destructor, or type conversion before '(' token
 __MATHCALL_VEC (sin,, (_Mdouble_ __x));
                ^
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:81:22: error: 'sincos' has not been declared
 __MATHDECL_VEC (void,sincos,,
                      ^~~~~~
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:81:29: error: expected identifier before ',' token
 __MATHDECL_VEC (void,sincos,,
                             ^
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:82:3: error: expected identifier before '(' token
   (_Mdouble_ __x, _Mdouble_ *__sinx, _Mdouble_ *__cosx));
   ^
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:82:57: error: expected constructor, destructor, or type conversion before ';' token
   (_Mdouble_ __x, _Mdouble_ *__sinx, _Mdouble_ *__cosx));
                                                         ^
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:100:16: error: expected constructor, destructor, or type conversion before '(' token
 __MATHCALL_VEC (exp,, (_Mdouble_ __x));
                ^
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:109:16: error: expected constructor, destructor, or type conversion before '(' token
 __MATHCALL_VEC (log,, (_Mdouble_ __x));
                ^
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:153:16: error: expected constructor, destructor, or type conversion before '(' token
 __MATHCALL_VEC (pow,, (_Mdouble_ __x, _Mdouble_ __y));
                ^
In file included from /DATA/users/m.slagter/miniconda3/envs/r36/x86_64-conda_cos6-linux-gnu/sysroot/usr/include/math.h:94:0,
                 from /DATA/users/m.slagter/miniconda3/envs/r36/x86_64-conda_cos6-linux-gnu/include/c++/7.3.0/cmath:45,
                 from /DATA/users/m.slagter/miniconda3/envs/r36/lib/R/include/R.h:50,
                 from stri_external.h:67,
                 from stri_stringi.h:36,
                 from stri_brkiter.cpp:32:
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:63:16: error: expected constructor, destructor, or type conversion before '(' token
 __MATHCALL_VEC (cos,, (_Mdouble_ __x));
                ^
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:65:16: error: expected constructor, destructor, or type conversion before '(' token
 __MATHCALL_VEC (sin,, (_Mdouble_ __x));
                ^
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:81:22: error: 'sincos' has not been declared
 __MATHDECL_VEC (void,sincos,,
                      ^~~~~~
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:81:29: error: expected identifier before ',' token
 __MATHDECL_VEC (void,sincos,,
                             ^
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:82:3: error: expected identifier before '(' token
   (_Mdouble_ __x, _Mdouble_ *__sinx, _Mdouble_ *__cosx));
   ^
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:82:57: error: expected constructor, destructor, or type conversion before ';' token
   (_Mdouble_ __x, _Mdouble_ *__sinx, _Mdouble_ *__cosx));
                                                         ^
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:100:16: error: expected constructor, destructor, or type conversion before '(' token
 __MATHCALL_VEC (exp,, (_Mdouble_ __x));
                ^
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:109:16: error: expected constructor, destructor, or type conversion before '(' token
 __MATHCALL_VEC (log,, (_Mdouble_ __x));
                ^
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:153:16: error: expected constructor, destructor, or type conversion before '(' token
 __MATHCALL_VEC (pow,, (_Mdouble_ __x, _Mdouble_ __y));
                ^
In file included from /DATA/users/m.slagter/miniconda3/envs/r36/x86_64-conda_cos6-linux-gnu/sysroot/usr/include/math.h:141:0,
                 from /DATA/users/m.slagter/miniconda3/envs/r36/x86_64-conda_cos6-linux-gnu/include/c++/7.3.0/cmath:45,
                 from /DATA/users/m.slagter/miniconda3/envs/r36/lib/R/include/R.h:50,
                 from stri_external.h:67,
                 from stri_stringi.h:36,
                 from stri_brkiter.cpp:32:
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:63:16: error: expected constructor, destructor, or type conversion before '(' token
 __MATHCALL_VEC (cos,, (_Mdouble_ __x));
                ^
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:65:16: error: expected constructor, destructor, or type conversion before '(' token
 __MATHCALL_VEC (sin,, (_Mdouble_ __x));
                ^
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:81:22: error: 'sincos' has not been declared
 __MATHDECL_VEC (void,sincos,,
                      ^~~~~~
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:81:29: error: expected identifier before ',' token
 __MATHDECL_VEC (void,sincos,,
                             ^
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:82:3: error: expected identifier before '(' token
   (_Mdouble_ __x, _Mdouble_ *__sinx, _Mdouble_ *__cosx));
   ^
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:82:57: error: expected constructor, destructor, or type conversion before ';' token
   (_Mdouble_ __x, _Mdouble_ *__sinx, _Mdouble_ *__cosx));
                                                         ^
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:100:16: error: expected constructor, destructor, or type conversion before '(' token
 __MATHCALL_VEC (exp,, (_Mdouble_ __x));
                ^
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:109:16: error: expected constructor, destructor, or type conversion before '(' token
 __MATHCALL_VEC (log,, (_Mdouble_ __x));
                ^
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:153:16: error: expected constructor, destructor, or type conversion before '(' token
 __MATHCALL_VEC (pow,, (_Mdouble_ __x, _Mdouble_ __y));
                ^
In file included from /DATA/users/m.slagter/miniconda3/envs/r36/lib/R/include/R.h:50:0,
                 from stri_external.h:67,
                 from stri_stringi.h:36,
                 from stri_brkiter.cpp:32:
/DATA/users/m.slagter/miniconda3/envs/r36/x86_64-conda_cos6-linux-gnu/include/c++/7.3.0/cmath:180:11: error: '::cos' has not been declared
   using ::cos;
           ^~~
/DATA/users/m.slagter/miniconda3/envs/r36/x86_64-conda_cos6-linux-gnu/include/c++/7.3.0/cmath:218:11: error: '::exp' has not been declared
   using ::exp;
           ^~~
/DATA/users/m.slagter/miniconda3/envs/r36/x86_64-conda_cos6-linux-gnu/include/c++/7.3.0/cmath:334:11: error: '::log' has not been declared
   using ::log;
           ^~~
/DATA/users/m.slagter/miniconda3/envs/r36/x86_64-conda_cos6-linux-gnu/include/c++/7.3.0/cmath:384:11: error: '::pow' has not been declared
   using ::pow;
           ^~~
/DATA/users/m.slagter/miniconda3/envs/r36/x86_64-conda_cos6-linux-gnu/include/c++/7.3.0/cmath:421:11: error: '::sin' has not been declared
   using ::sin;
           ^~~
make: *** [/DATA/users/m.slagter/miniconda3/envs/r36/lib/R/etc/Makeconf:176: stri_brkiter.o] Error 1
ERROR: compilation failed for package ‘stringi’
* removing ‘/DATA/users/m.slagter/miniconda3/envs/r36/lib/R/library/stringi’
* restoring previous ‘/DATA/users/m.slagter/miniconda3/envs/r36/lib/R/library/stringi’

The downloaded source packages are in
        ‘/tmp/RtmpVkqaTi/downloaded_packages’
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
Warning message:
In install.packages("stringi") :
  installation of package ‘stringi’ had non-zero exit status

**Comment by slagtermaarten** [comment]
Luckily, I can use the precompiled stringi as well.

**Comment by gagolews** [comment]
How about `/DATA/users/m.slagter/miniconda3/envs/r36/lib/R/etc/Makeconf` ?

**Comment by slagtermaarten** [comment]
Yes! Once again, thanks for your help. Weird that these two sets of compilers disagree on syntax definitions that seem quite elementary to me (someone who has only done a little with C/C++)...

After having changed the file, I now get this in R 3.6

> install.packages('stringi')
trying URL 'https://cran.rstudio.com/src/contrib/stringi_1.4.6.tar.gz'
Content type 'application/x-gzip' length 7284354 bytes (6.9 MB)
==================================================
downloaded 6.9 MB

* installing *source* package ‘stringi’ ...
** package ‘stringi’ successfully unpacked and MD5 sums checked
** using staged installation
checking for R_HOME... /DATA/users/m.slagter/miniconda3/envs/r36/lib/R
checking for R... /DATA/users/m.slagter/miniconda3/envs/r36/lib/R/bin/R
checking for endianness... little
checking for R >= 3.1.0 for C++11 use... yes
checking for R < 3.4.0 for CXX1X flag use... no
checking for cat... /bin/cat
checking for local ICUDT_DIR... icu61/data
checking for gcc... gcc
checking whether the C compiler works... no
configure: error: in `/tmp/Rtmp9BPDT3/R.INSTALL6d731fbee20d/stringi':
configure: error: C compiler cannot create executables
See `config.log' for more details
ERROR: configuration failed for package ‘stringi’
* removing ‘/DATA/users/m.slagter/miniconda3/envs/r36/lib/R/library/stringi’
* restoring previous ‘/DATA/users/m.slagter/miniconda3/envs/r36/lib/R/library/stringi’

The downloaded source packages are in
        ‘/tmp/Rtmp7HGSf7/downloaded_packages’
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
Warning message:
In install.packages("stringi") :
  installation of package ‘stringi’ had non-zero exit status

**Comment by gagolews** [comment]
The next question is whether you have gcc/g++ installed, and so on, and so forth...

Anyway, this is not really related to stringi, but your local system config...
