### ISSUE TITLE
Error in dyn.load while installing stringi

### ISSUE THREAD

**Issue by rtgdk** [gagolews/stringi#379]
Getting dyn.load error while installing stringi :

> Error in dyn.load(file%!(PACKER_COMMA) DLLpath = DLLpath%!(PACKER_COMMA) ...) :
Unable to load shared object '/usr/lib/a-4.2.0-r-3.3.2/lib/R/library/stringi/libs/stringi.so':
/usr/lib/a-4.2.0-r-3.3.2/lib/R/library/stringi/libs/stringi.so: undefined symbol: _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEC1Ev

But, when I installed gcc before stringi through conda `conda install -y -c anaconda gcc`, installation passed. I want to remove gcc from the conda environment. Can you help me with installing stringi without gcc? Or help me with debugging whether stringi really needs gcc? 

Also, by the logs, the only difference I see in the installation is at :
> checking whether we may build an ICU4C-based project... no

Posting both the logs on gist: https://gist.github.com/rtgdk/9875e8190ffedb6ffd41caf98e790490
(Keeping Issue description minimal)

**Comment by gagolews** [comment]
You definitely need a compiler to build any R package that includes some C/C++/Fortran code...
