### ISSUE TITLE
Using stringi like a simple parser?

### ISSUE THREAD

**Issue by billdenney** [gagolews/stringi#380]
Hi @gagolews, thank you for stringi!

I'm wanting to make a function that works similarly to `Hmisc::latexTranslate()` to escape strings for use in LaTeX.  (I'm rewriting it because I want some options to just do minimal escaping vs more detailed replacement.)  For that, I was hoping to be able to do something simple with `stri_replace_all_fixed()` where I was hoping that it could work more like a lexer and then replace tokens (performing all matching before performing any replacement).  That isn't how `stri_replace_all_fixed()` works, and I now understand that.

Is there any part of `stringi` that will allow matching everything more like tokens and then replacing the tokens?  To make this concrete, I'd like the following to output the string `"\\textbackslash{}\\~{}"` (extra backslashes are to indicate how the string would look in quotes in R not that I want the double-backslash).

I know that for this simple example, I could reorder the replacements vector, but my real example cannot simply reorder the inputs.  I also know that I could do a two-stage replacement where I replace the original values with strings that are unique and not in the input (maybe from Unicode Private Use Area code points) and then do a second stage where I replace those new unique strings with the desired output.  But, if there is a better, simpler solution, I'd rather use that.

``` r
library(stringi)
replacements <-
  c(
    "~"="\\~{}",
    "\\"="\\textbackslash{}"
  )

stri_replace_all_fixed(str="\\~", pattern=names(replacements), replacement=replacements, vectorize_all=FALSE)
#> [1] "\\textbackslash{}\\textbackslash{}~{}"
```

<sup>Created on 2020-05-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by gagolews** [comment]
Unfortunately, it seems like this requires a bit more elaborated approach than just few simple calls to stringi funcitons, which don't go beyond finite-state automatas.

If I were you, I'd attack it with some custom C/C++ code. That'd be the most effective.

**Comment by billdenney** [comment]
Perfectly fair.  Thanks for confirming this.

**Comment by billdenney** [comment]
In case someone else comes across this and wants to use stringi as a simple parser, here is the code that I wrote to do it.  Given the simplicity of this code, I'm probably going to use it for my tool.

```
token_replace <- function(x, pattern, replacement, ..., fixed=FALSE) {
  if (missing(replacement)) {
    replacement <- unname(pattern)
    pattern <- names(pattern)
    if (is.null(replacement) || ("" %in% replacement)) {
      stop("`pattern` must all be named if `replacement` is missing.")
    }
  }
  if (length(pattern) != length(replacement)) {
    stop("`pattern` and `replacement` must have the same length.")
  }
  # Use a Unicode Private Use Area
  if (length(replacement) > (0xFFFFD - 0xF0000)) {
    stop("A maximum of ", 0xFFFFD - 0xF0000, " `pattern`/`replacement` values may be used due to the use of the Unicode Private Use Area.")
  }
  intermediate_replacement <-
    intToUtf8(seq(0xF0000, length.out=length(replacement)), multiple=TRUE)
  stri_replace_fun <-
    if (fixed) {
      stringi::stri_replace_all_fixed
    } else {
      stringi::stri_replace_all_regex
    }
  tokenized <-
    stri_replace_fun(
        str=x,
        pattern=pattern,
        replacement=intermediate_replacement,
        ...,
        vectorize_all=FALSE
      )
  final <-
    stringi::stri_replace_all_fixed(
      str=tokenized,
      pattern=intermediate_replacement,
      replacement=replacement,
      vectorize_all=FALSE
    )
  final
}
```
