### ISSUE TITLE
stringi.so not found in docker container when building from rocker/r-ver:4.0.0

### ISSUE THREAD

**Issue by rplati** [gagolews/stringi#383]
As of 25.5.2020 I get the following error message when trying to start a docker container calling `library(stringr)`.
```
Error: package or namespace load failed for ‘stringi’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/usr/local/lib/R/site-library/stringi/libs/stringi.so':
  libicui18n.so.60: cannot open shared object file: No such file or directory
```

I was able to confirm that the error concerns stringi with the following minimal example:

Dockerfile
```
FROM rocker/r-ver:4.0.0
RUN install2.r --error stringi
COPY / /
ENTRYPOINT ["Rscript", "start.R"]
```

start.R
```
library(stringi)
```

No error appears in the log when building the docker image. The same docker image worked fine prior to 22.5.2020. The issue does not seem to concern older versions of R (no error when starting from `rocker/r-ver:3.6.3`).

**Comment by gagolews** [comment]
You should contact the maintainer of that container.
