### ISSUE TITLE
stringi installation error

### ISSUE THREAD

**Issue by raman91** [gagolews/stringi#385]
Hi, 

I am installing stringi library on R, but i am getting an error:

make: *** [/home/user/miniconda3/lib/R/etc/Makeconf:171: stri_brkiter.o] Error 1
ERROR: compilation failed for package ‘stringi’

Please help to resolve the issue.

Thanks

**Comment by theandyb** [comment]
I was running into a similar issue installing stringi from R installed via conda. It might be helpful to post more details from the error messages (which would have appeared above what you pasted)
