### ISSUE TITLE
How to overwrite STRINGI_CXXFLAGS?

### ISSUE THREAD

**Issue by vspinu** [gagolews/stringi#387]
I am adding `STRINGI_CXXFLAGS = -g0 -O3 -fpic` to ~/.R/Makevars and I still see that stringi is compiled with the `-g -O2`.

What is the right way to overwrite the flags on a site basis? 

Thanks!

**Comment by gagolews** [comment]
Refer to the `INSTALL` file for more details.

**Comment by vspinu** [comment]
Actually the standard R flags `CXX11FLAGS` kick in. Something must have been wrong with my setup before. 

Regarding INSTALL, those instructions are useful for explicit package installation. What I need is a way to setup the system (docker) such that in case the end user want to install stringi the flags would kick in automatically. 

In any case, problem solve. Thanks!
