### ISSUE TITLE
Unexpected Extended ASCII Translation

### ISSUE THREAD

**Issue by billdenney** [gagolews/stringi#388]
Related to sfirke/janitor#389

When trying to translate extended ASCII to printable ASCII (as expected with the `stri_enc_toascii()` function), I expected the superscript 2 character to convert to either "2" (or perhaps preferably "^2"), but it was converted to something else.

Is there another function or method in stringi that will translate or transliterate extended ASCII to printable ASCII?

``` r
"\xb2"
#> [1] "²"
stringi::stri_enc_toascii("\xb2")
#> [1] "\032"
```

<sup>Created on 2020-07-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by gagolews** [comment]
Sure:

```r
> stringi::stri_trans_general("²", "nfkd;nfc;Latin-ASCII")
[1] "2"
```

Fun fact: the ASCII `\032` is the SUBSTITUTE CHARACTER, a kind of NA, but for individual code points.

**Comment by billdenney** [comment]
Thanks!  I read for a bit about nfd, nfc, nfkd, and nfkc, and I'm not sure that I understand more, but I do understand that these appear to be what is needed for this case.

**Comment by gagolews** [comment]
This one gives a good overview IMO https://www.unicode.org/reports/tr15/

**Comment by billdenney** [comment]
Thanks to the pointer for the overview of the normalizers and for the info about character 32.
