### ISSUE TITLE
nfkd and nfc do not show up in stringi::stri_trans_list()

### ISSUE THREAD

**Issue by billdenney** [gagolews/stringi#389]
Related to #376, #388, and sfirke/janitor#389.

Due to some issues you may recall with system-specific differences in available transliterators previously discussed, I have been checking for transliterators being available with `stringi::stri_trans_list()` in `janitor`.  When I just added the "nfkd" and "nfc" translations to the list used within `janitor` they are not showing as available on the system (but they are, in fact, available).  Is it expected behavior that "nfc", "nfd", "nfkc", and "nfkd" are not in the list of available transliterators?

I do understand that they are a different class of transliterator than the others, but for this one specific case, it would be helpful to have them in the list.  If they are not going to be added to the list, that's okay, and I can easily work around it in janitor.

**Comment by gagolews** [comment]
`nfc` is just an abbreviated version of `Any-NFC` I guess.

According to http://userguide.icu-project.org/transforms/general, which is referenced in `stri_trans_list()`, *If the source is not given, then the source is "Any", the set of all characters.*

**Comment by billdenney** [comment]
Thanks for the quick response there and sorry for missing that one.  (And generally, thanks for the quick responses across the board!)
