### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by kwojtusik** [gagolews/stringi#403]
Hello,

I am having trouble installing stringi. A different package I need is dependent on it, and when I try to install that package it errors out on installing stringi. I have tried installing it manually and run into this error: 

`trying URL 'https://cran.rstudio.com/bin/macosx/contrib/4.0/stringi_1.5.3.tgz'
Warning in install.packages :
  cannot open URL 'https://cran.rstudio.com/bin/macosx/contrib/4.0/stringi_1.5.3.tgz': HTTP status was '404 Not Found'
Error in download.file(url, destfile, method, mode = "wb", ...) : 
  cannot open URL 'https://cran.rstudio.com/bin/macosx/contrib/4.0/stringi_1.5.3.tgz'
Warning in install.packages :
  download of package ‘stringi’ failed`

I am not very proficient with R, so I am unsure if this is due to something I am doing or not. Thank you for any help.

-Kris

**Comment by gagolews** [comment]
Try again, the file should be there now.

**Comment by kwojtusik** [comment]
Its works now. Thank you!
