### ISSUE TITLE
R and RStudio Server Pro

### ISSUE THREAD

**Issue by hermod69** [gagolews/stringi#409]
Hi.

We are having some problems with installing stringi. When installing stringi, it ask for some exernal files outside cran.
As far I can see, this files is zip file like icudt61l.zip. I think the this files is for Windows.

We run R and RStudio Server Pro on RedHat and we have a local cran repo. No servers have internett access. Therfore, installing stringi will fail since the zipfile is not in cran.

Is it possible to remove the dependencies or reconfigure the package?

Regards,
Hermod

**Comment by gagolews** [comment]
Hi, refer to the `INSTALL` file or to https://stackoverflow.com/questions/31942322 (among others).
