### ISSUE TITLE
cannot install source 1.5.3 version 

### ISSUE THREAD

**Issue by jimoreira** [gagolews/stringi#410]
i have no trubles to install the binary version, but the source one cannot. 
I'm trying to install the latest because a dependency for package "aomisc"

part of th error: 
`Warning in file.copy(libfile, dest, overwrite = TRUE) :
  problema al copiar .\stringi.dll  a C:\Users\javie\Documents\R\win-library\3.6\00LOCK-stringi\00new\stringi\libs\x64\stringi.dll: No such file or directory`
the final part:
`Error: package or namespace load failed for 'stringi' in library.dynam(lib, package, package.lib):
 DLL 'stringi' not found: maybe not installed for this architecture?`

Session info ------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.6.1 (2019-07-05)
 os       Windows >= 8 x64            
 system   x86_64, mingw32             
 ui       RStudio                     
 language (EN)                        
 collate  Spanish_Spain.1252          
 ctype    Spanish_Spain.1252          
 tz       America/Montevideo          
 date     2020-12-05                  

- Packages ----------------------------------------------------------------------------------------
 package     * version date       lib source        
 assertthat    0.2.1   2019-03-21 [1] CRAN (R 3.5.3)
 callr         3.5.1   2020-10-13 [1] CRAN (R 3.6.3)
 cli           2.2.0   2020-11-20 [1] CRAN (R 3.6.3)
 crayon        1.3.4   2017-09-16 [1] CRAN (R 3.5.1)
 desc          1.2.0   2018-05-01 [1] CRAN (R 3.5.2)
 devtools    * 2.3.2   2020-09-18 [1] CRAN (R 3.6.3)
 digest        0.6.27  2020-10-24 [1] CRAN (R 3.6.3)
 ellipsis      0.3.1   2020-05-15 [1] CRAN (R 3.6.3)
 fansi         0.4.1   2020-01-08 [1] CRAN (R 3.6.3)
 fs            1.5.0   2020-07-31 [1] CRAN (R 3.6.3)
 glue          1.4.2   2020-08-27 [1] CRAN (R 3.6.3)
 magrittr      2.0.1   2020-11-17 [1] CRAN (R 3.6.3)
 memoise       1.1.0   2017-04-21 [1] CRAN (R 3.5.2)
 pkgbuild      1.1.0   2020-07-13 [1] CRAN (R 3.6.3)
 pkgload       1.1.0   2020-05-29 [1] CRAN (R 3.6.3)
 prettyunits   1.1.1   2020-01-24 [1] CRAN (R 3.6.3)
 processx      3.4.5   2020-11-30 [1] CRAN (R 3.6.3)
 ps            1.4.0   2020-10-07 [1] CRAN (R 3.6.3)
 R6            2.5.0   2020-10-28 [1] CRAN (R 3.6.3)
 remotes       2.2.0   2020-07-21 [1] CRAN (R 3.6.3)
 rlang         0.4.9   2020-11-26 [1] CRAN (R 3.6.3)
 rprojroot     2.0.2   2020-11-15 [1] CRAN (R 3.6.3)
 rstudioapi    0.13    2020-11-12 [1] CRAN (R 3.6.3)
 sessioninfo   1.1.1   2018-11-05 [1] CRAN (R 3.5.2)
 testthat      3.0.0   2020-10-31 [1] CRAN (R 3.6.3)
 usethis     * 1.6.3   2020-09-17 [1] CRAN (R 3.6.3)
 withr         2.3.0   2020-09-22 [1] CRAN (R 3.6.3)
 yaml          2.2.0   2018-07-25 [1] CRAN (R 3.5.1)

[1] C:/Users/javie/Documents/R/win-library/3.6
[2] C:/Program Files/R/R-3.6.1/library

if you have any ideas? 
thank you very much!

**Comment by gagolews** [comment]
Have you tried restarting R and/or reinstalling stringi?

**Comment by jimoreira** [comment]
Yes i have,  both. 
Thanks for your help

**Comment by gagolews** [comment]
How about an upgrading R to the most recent version? R 3.6.1 is pretty outdated.

**Comment by jimoreira** [comment]
You are right, just didn't want to make a bigger mess yet..but...i should take a deep breath an get on with it. 
Thanks for your help

**Comment by gagolews** [comment]
(closing as inactive for > 1 year)
