### ISSUE TITLE
stringi_trans_general issue when read from any file

### ISSUE THREAD

**Issue by rrudra46** [gagolews/stringi#411]
I want to achieve something like:
stri_trans_general('Man\u00e9', 'latin-ascii')   -->  "Mané"
but after the contents are read from a file.

An example is as below:
x = read.table("file.txt")
where the file contains this: Man\u00e9
But on stri_trans_general(x, 'latin-ascii'), I achieve this: "Man\\u00e9"

**Comment by gagolews** [comment]
A call to stringi::stri_unescape_unicode() should do the trick, I reckon.

**Comment by rrudra46** [comment]
It worked. Thanks. 👍
