### ISSUE TITLE
search_locate_bound.R is emtpy in master.zip for offline environment installations

### ISSUE THREAD

**Issue by tedmoorman** [gagolews/stringi#418]
I've downloaded multiple times from [the archive](https://github.com/gagolews/stringi/archive/master.zip) to install in an offline environment. search_locate_bound.R is emtpy in the zip file.

**Comment by gagolews** [comment]
Hmmm... the file is definitely not empty (https://github.com/gagolews/stringi/blob/master/R/search_locate_bound.R), and master.zip is auto-generated by github, so there might be something wrong on the gh side?

I recommend you simply try again.

**Comment by tedmoorman** [comment]
I guess the issue is on the github side then. I used the link you referenced to populate the file after unzipping. Then I rezipped and installed without any problems.

**Comment by gagolews** [comment]
Please close this issue if you think your problem is fixed then. :)

**Comment by tedmoorman** [comment]
Will do. 
Still looking for a fix to #419 , unfortunately.
