### ISSUE TITLE
Feature request: make available previous versions of stringi for offline installations

### ISSUE THREAD

**Issue by tedmoorman** [gagolews/stringi#419]
For those of us working in an offline environment, it would be helpful to have access to previous versions of the stringi master.zip file for offline installations. Some packages depend upon stringi functions no longer used in the current version.

If unclear, this is the part of the install instructions I'm referring to:
```
Moreover, if you have **absolutely no internet access** on the machines
you try to install *stringi* on, try fetching the latest development version
of the package. It is already shipped with the `ICU` data archives.
You can build a distributable source package that includes all the required
ICU data files (for off-line use) by omitting some relevant lines in
the `.Rbuildignore` file. The following command sequence should do the trick:

    wget https://github.com/gagolews/stringi/archive/master.zip -O stringi.zip
    unzip stringi.zip
    sed -i '/\/icu..\/data/d' stringi-master/.Rbuildignore
    R CMD build stringi-master
```

**Comment by tedmoorman** [comment]
Unfortunately, when downloading [the v.1.3.1 zip file](https://github.com/gagolews/stringi/archive/refs/tags/v1.3.1.zip), it appears to be missing a lot. I don't see any of the R files or that directory. Maybe this is related to the github issues mentioned in #418?

**Comment by gagolews** [comment]
Yes, this is probably the case.///
