### ISSUE TITLE
What is a character?

### ISSUE THREAD

**Issue by hadley** [gagolews/stringi#422]
I was surprised by this result:

``` r
library(stringi)
stri_split_boundaries("check", 
  opts_brkiter = stri_opts_brkiter("character", locale = "cs_CZ")
)
#> [[1]]
#> [1] "c" "h" "e" "c" "k"
```

<sup>Created on 2021-04-29 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

Because "ch" is a letter in the Czech alphabet (https://en.wikipedia.org/wiki/Czech_orthography) so I thought it would be treated as a single character here.

**Comment by hadley** [comment]
Oh maybe this because "character" really means "grapheme cluster"? And presumably when you're typing in Czech, you can still select "c" and "h" independently.

**Comment by hadley** [comment]
Hmmm, but http://www.unicode.org/reports/tr29/#Grapheme_Cluster_Boundaries includes the Slovak "ch" as an example of a "tailored grapheme cluster". Ah, but later it says

> The Unicode definitions of grapheme clusters are defaults: not meant to exclude the use of more sophisticated definitions of tailored grapheme clusters where appropriate. Such definitions may more precisely match the user expectations within individual languages for given processes. For example, “ch” may be considered a grapheme cluster in Slovak, for processes such as collation. The default definitions are, however, designed to provide a much more accurate match to overall user expectations for what the user perceives of as characters than is provided by individual Unicode code points.

**Comment by gagolews** [comment]
Exactly, https://www.unicode.org/reports/tr29/#Grapheme_Cluster_Boundaries puts more emphasis on graphemes as entrities-comprised-of-many-code-points-that-are-displayed-as-if-they-were-a-single-character.

The Slovak digraph *ch* or even the diphtong *ae* in Danish or Norwegian will be treated as two separate graphemes by the `character` break iterator (but custom break iterators can be specified too if they are needed).

In Polish we have something similar: sz, cz, ch, dż, dz, dź, rz are digraphs but I would be very surprised to see *chrząszcz* being decomposed as *ch-rz-ą-sz-cz*. There are examples where they are pronounced as 2 separate letters, *marznę* is *mar-znę* etc. Good luck learning Slavic languages btw. :wink:
