### ISSUE TITLE
stri_width some codepoints need fixing (grave accent, eszett, etc.) 

### ISSUE THREAD

**Issue by hughjonesd** [gagolews/stringi#429]
I'm not sure if this is a bug or even anyone's fault, but the recent stringi update broke my "huxtable" package on CRAN by changing the behaviour of `stri_pad_right` and friends - presumably because of linking to the new  ICU4C library. Did anyone do a reverse dependency check? It would have been nice to get warning of this. huxtable uses stringi via stringr, so that may be relevant.

**Comment by dankearney** [comment]
I noticed that one of my projects which uses stringi as a dependency is also failing with 1.6.1.

**Comment by hughjonesd** [comment]
One underlying issue is that `nchar(..., type = "width")` and `stringi::stri_width("`")` now give different answers. (Maybe they always could, just that now it's obvious.)

R 4.0.3, stringi version 1.6.1:

```r
> nchar("`", type = "w")
[1] 1
> stringi::stri_width("`")
[1] 0
```

stringi 1.5.3:

```r
> nchar("`", type = "w")
[1] 1
> stringi::stri_width("`")
[1] 1
```

**Comment by gagolews** [comment]
Yes, 1.6.1 was a huge update and unfortunately this will cause a couple of packages to break.
Once all issues are identified (which will take 1-2 more weeks), I will submit an updated version to CRAN asap.

Thank you for digging into the problem, in this case it is indeed caused by the new `stri_width` which now has a few obvious flaws, including the grave accent being classified as of width 0 (however, it is an accent, maybe it should be of width 0 after all).

Fix is on the way.

**Comment by gagolews** [comment]
@dankearney "I noticed that one of my projects which uses stringi as a dependency is also failing with 1.6.1." — could you please be more specific? Which package? Which tests are failing, is it due to the issues with padding/string width?
Thank you for contributing to the testing of stringi.

**Comment by gagolews** [comment]
[note to self] Don't set width of GC=Sk to 0

[note to self] Don't set width of U_EA_AMBIGUOUS to 2

**Comment by gagolews** [comment]
This is now fixed. All characters <= U+CCFF of width 0 are the same as in 1.5.3.
However, v1.6.2 now more eagerly classifies characters as of width 2, including emojis and other symbols.
This should not be a problem in you package, though.

**Comment by hughjonesd** [comment]
That's ace. Is it likely to hit CRAN before May 23? My package gets archived then, and it'll take some time for tests to start working with your update, so want to be careful.

**Comment by gagolews** [comment]
Absolutely; no worries.

**Comment by gagolews** [comment]
I've now submitted v1.6.2  to CRAN. :crossed_fingers:
