### ISSUE TITLE
md5sum mismatch for icudt

### ISSUE THREAD

**Issue by tyner** [gagolews/stringi#430]
I am trying to install version 1.6.1 from source on an Amazon Linux EMR node (which ships with an unsupported version 50.2 of ICU4C) . I copied icu4c-69_1-data-bin-l.zip to a directory and ran

```r
 install.packages("stringi", configure.vars = "ICUDT_DIR=/path/to/the/directory", configure.args = "--disable-pkg-config")
```
but it says

> checking whether we are using the GNU C++ compiler... yes
> checking whether g++ -m64 -std=gnu++11 accepts -g... yes
> checking whether the C++ compiler supports the long long type... yes
> checking whether the compiler implements namespaces... yes
> checking whether the compiler supports Standard Template Library... yes
> checking whether std::map is available... yes
> *** System ICU4C has been disabled.
> checking whether we may compile src/icu69/common/putil.cpp... yes
> checking whether we may compile src/icu69/i18n/number_affixutils.cpp... yes
> checking whether the ICU data library can be downloaded... md5sum mismatch for icudt
> Error: Stopping on error
> Execution halted
> *** *********************************************************************
> *** stringi cannot be built.
> *** Failed to download the ICU data library (icudt). Stopping now.
> *** For build environments that have no internet access,
> *** see the INSTALL file for a workaround.
> *** *********************************************************************

Any idea what I'm doing wrong? Here is my sessionInfo(),

> R version 3.4.1 (2017-06-30)
> Platform: x86_64-redhat-linux-gnu (64-bit)
> Running under: Amazon Linux AMI 2018.03
> 
> Matrix products: default
> BLAS/LAPACK: /usr/lib64/R/lib/libRblas.so
> 
> locale:
>  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
>  [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
>  [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
>  [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
>  [9] LC_ADDRESS=C               LC_TELEPHONE=C
> [11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base
> 
> loaded via a namespace (and not attached):
> [1] compiler_3.4.1 tools_3.4.1

Thanks,
Ben

**Comment by gagolews** [comment]
Did you copy the file to src/icu69/data ?

What is the result of a call to `md5sum icu4c-*` ?

**Comment by gagolews** [comment]
Did you use the files from https://github.com/gagolews/stringi/tree/master/src/icu69/data or from the unicode-org/icu repository?

**Comment by gagolews** [comment]
I get:

```
gagolews@dionysus:~/R/stringi/src/icu69/data$ md5sum icu4c-69_1-data-bin-*
e86eba75d1f39be63713569dc0dc9524  icu4c-69_1-data-bin-b.zip
58ecd3e72e9d96ea2876dd89627afeb8  icu4c-69_1-data-bin-l.zip
```

**Comment by tyner** [comment]
I had originally downloaded from https://raw.githubusercontent.com/gagolews/stringi/master/src/icu69/data/icu4c-69_1-data-bin-l.zip using Google Chrome, however the resulting md5sum did not match. I've re-downloaded using wget and now the md5sum matches and installation is successful. Lesson learned, and sorry for the false alarm.
