### ISSUE TITLE
Release date for r-release Windows binary for version 1.6.2?

### ISSUE THREAD

**Issue by AlexPars** [gagolews/stringi#436]
Would you have a release date for the r-release Windows binary for version 1.6.2?

Currently the CRAN webpage shows the following:

Windows&nbsp;binaries: | r-devel: stringi_1.6.2.zip, r-devel-UCRT: stringi_1.6.2.zip, r-release: stringi_1.6.1.zip
-- | --

Best regards,

Alex

**Comment by gagolews** [comment]
Unfortunately I have no control over the CRAN servers, I have notified their maintains of the build errors and am waiting for a response.

Note that you can always compile the source packages yourself, using https://cran.r-project.org/bin/windows/Rtools/.

**Comment by AlexPars** [comment]
Thank you. Indeed I had to compile from source.

I am using checkpoint package to manage the package versions for a specific date, and while compile from source works, it adds more complexity to package management

**Comment by gagolews** [comment]
I will leave the issue open until it get resolved.

**Comment by AlexPars** [comment]
It appears that the issue is due to stringi.1.6.2 being saved as corresponding to R 4.1, while version stringi.1.6.1.zip being saved as corresponding to R 4.1

https://cran.r-project.org/bin/windows/contrib/4.2/stringi_1.6.2.zip

https://cran.r-project.org/bin/windows/contrib/4.1/stringi_1.6.1.zip

**Comment by gagolews** [comment]
I think it's merely a function of 1.6.2 not building properly therein...

**Comment by gagolews** [comment]
This has now been fixed. :tada:

**Comment by bersbersbers** [comment]
I think it's about the same now for 1.7.3:
```
r-devel: stringi_1.7.3.zip, r-devel-UCRT: stringi_1.7.2.zip, r-release: stringi_1.6.2.zip, r-oldrel: stringi_1.6.2.zip
```

Also:
```
* installing *source* package 'stringi' ...
** package 'stringi' successfully unpacked and MD5 sums checked
ERROR: cannot remove earlier installation, is it in use?
* removing 'd:/Rcompile/CRANpkg/lib/4.1/stringi'
* restoring previous 'd:/Rcompile/CRANpkg/lib/4.1/stringi'
Warning in file.copy(lp, dirname(pkgdir), recursive = TRUE, copy.date = TRUE) :
  problem copying d:\Rcompile\CRANpkg\lib\4.1\00LOCK-stringi\stringi\libs\icudt69l.dat to d:\Rcompile\CRANpkg\lib\4.1\stringi\libs\icudt69l.dat: Invalid argument
Warning in file.copy(lp, dirname(pkgdir), recursive = TRUE, copy.date = TRUE) :
  problem copying d:\Rcompile\CRANpkg\lib\4.1\00LOCK-stringi\stringi\libs\x64\stringi.dll to d:\Rcompile\CRANpkg\lib\4.1\stringi\libs\x64\stringi.dll: Permission denied
```

https://www.r-project.org/nosvn/R.check/r-release-windows-ix86+x86_64/stringi-00install.html

Seems to be an issue on CRAN servers indeed.

**Comment by gagolews** [comment]
Exactly. :/
