### ISSUE TITLE
CC: seems hardcoded to gcc

### ISSUE THREAD

**Issue by CdeMills** [gagolews/stringi#447]
Hello,
I'm using clang to compile R modules under CentOS_8 linux. To this end, I created a '~/.R/Makevars' file with
CC=clang
CXX=clang++
During the configure stage, clang is detected and used as C compiler. But the compilation starts with a library, and this one is compiled with gcc. Meaning the top level 'CC' does not seem transmitted. Could you check ?
TIA
Pascal Dupuis

**Comment by gagolews** [comment]
No, the flags are not hardcoded.

Stringi uses C++11, so try playing with `CXX11`, `CXX11FLAGS`, and `CXX11STD`.

See sec. 2.7.3 in https://cran.r-project.org/doc/manuals/r-devel/R-admin.html

**Comment by CdeMills** [comment]
Hello,
that made it work. Thanks for the tip.
Regards
Pascal
