### ISSUE TITLE
stri_join and NAs

### ISSUE THREAD

**Issue by graywh** [gagolews/stringi#451]
As it is, both `stringr::str_c` and `stringi::stri_join` have "infectious" NAs.  But is there a non-infectious option?

In other words, I would like to have `stri_join(c('foo','bar'), c(NA,'baz'), sep=',', na.rm=TRUE) == c('foo','bar,baz')`.

Is there another function that already does this that I'm just not seeing?

**Comment by gagolews** [comment]
For more information on this behaviour, please refer to Sec. 3.4 in https://stringi.gagolewski.com/_static/vignette/stringi.pdf.
