### ISSUE TITLE
Syntax error in regex pattern.

### ISSUE THREAD

**Issue by ycphs** [gagolews/stringi#455]
A regex expression to get the content in brackets 

```
stri_extract_all_regex(V2, "(?<=\\()+.+?(\\))")
```
resulted in the following error:

> Error in stri_extract_all_regex(V2, "(?<=\\()+.+?(\\))") : 
  Syntax error in regex pattern. (U_REGEX_RULE_SYNTAX, context=`(?<=\()+.+?(\))`)

I checked the expression here: [regex check](https://regex101.com/r/ExrVt8/1)

The following command works perfect.
```
stri_extract_all_regex(V2,"(\\()+.+?(\\))")
```
it seems that the lookahead (positive and negative) doesn't work.

**Comment by gagolews** [comment]
There is a syntax error in your regex.

You cannot have a quantifier `+` applied on a look-behind assertion.

Consult the ICU regex syntax at https://unicode-org.github.io/icu/userguide/strings/regexp.html.
