### ISSUE TITLE
Normalization Form Decompose does not apply correctly to Koreans

### ISSUE THREAD

**Issue by kwhkim** [gagolews/stringi#465]
Since `stringi` documentation explicitly says it supports unicode 10,

  I tried with `stringi::stri_trans_nfkd` with '\ud4db'(퓛), which should be decomposed into `\u1100\u1161\u11a8`.

  (http://www.unicode.org/reports/tr15/tr15-45.html)

  I dont know much about the implementation but I guess there seems to be some omission error,

  because according to the doc, decomposition is simply applying recursively decomposition mapping.

**Comment by kwhkim** [comment]
There must have been some errors. I can't reproduce this :(

**Comment by kwhkim** [comment]
Since it is rendered into full syllable even if it is normalization decomposition form like `\u1100\u1161\u11a8`.

I suggest using `strsplit(x, "")` after `x <- stri_trans_nfkd('\ud4db')` or `utf8ToInt(x)`

**Comment by gagolews** [comment]
I get:

```r
stringi::stri_escape_unicode(stringi::stri_trans_nfkd("\ud4db"))
## [1] "\\u1111\\u1171\\u11b6"
```
