### ISSUE TITLE
install locally successfully,but when install others needs such inpendendcy, failed

### ISSUE THREAD

**Issue by asmlgkj** [gagolews/stringi#468]
dear gagolews,
thanks a lot for your attention to this issue. 
linux centos7.0 Platform

I install stringi from  install.paackages failed. so I intall as your https://stringi.gagolewski.com/install.html

```
wget https://github.com/gagolews/stringi/archive/master.zip -O stringi.zip
unzip stringi.zip
sed -i '/\/icu..\/data/d' stringi-master/.Rbuildignore
R CMD build stringi-master
```
but when  install library
BiocManager::install("BSgenome.Hsapiens.UCSC.hg19")

still occurs such problem
![image](https://user-images.githubusercontent.com/50854682/144532705-c786ccdb-4464-4e5b-9b40-398349e265a9.png)

when I install any package needs stringi, it always ask me to update, if I select no, it stops installing

**Comment by gagolews** [comment]
Can you send the whole output generated during a call to `BiocManager::install("BSgenome.Hsapiens.UCSC.hg19")` ?

**Comment by asmlgkj** [comment]
> BiocManager::install("BSgenome.Hsapiens.UCSC.hg19")
Bioconductor version 3.10 (BiocManager 1.30.16), R 3.6.0 (2019-04-26)
Installation paths not writeable, unable to update packages
  path: /usr/lib64/R/library
  packages:
    boot, class, cluster, codetools, KernSmooth, lattice, MASS, Matrix, mgcv,
    nlme, nnet, spatial, survival
Old packages: 'stringi'
Update all/some/none? [a/s/n]: s
stringi :
 Version 1.7.5.9001 installed in /home/kobe/R/x86_64-redhat-linux-gnu-library/3.6 
 Version 1.7.6 available at https://cloud.r-project.org
Update? (Yes/no/cancel) no
Warning message:
package(s) not installed when version(s) same as current; use `force = TRUE` to
  re-install: 'BSgenome.Hsapiens.UCSC.hg19' 
> BiocManager::install("BSgenome.Hsapiens.UCSC.hg19")
Bioconductor version 3.10 (BiocManager 1.30.16), R 3.6.0 (2019-04-26)
Installation paths not writeable, unable to update packages
  path: /usr/lib64/R/library
  packages:
    boot, class, cluster, codetools, KernSmooth, lattice, MASS, Matrix, mgcv,
    nlme, nnet, spatial, survival
Old packages: 'stringi'
Update all/some/none? [a/s/n]: a
trying URL 'https://cloud.r-project.org/src/contrib/stringi_1.7.6.tar.gz'
Content type 'application/x-gzip' length 7600716 bytes (7.2 MB)
==================================================
downloaded 7.2 MB

* installing *source* package ‘stringi’ ...
** package ‘stringi’ successfully unpacked and MD5 sums checked
** using staged installation
checking for R_HOME... /usr/lib64/R
checking for R... /usr/lib64/R/bin/R
checking for endianness... little
checking for R >= 3.1.0 for C++11 use... yes
checking for R < 3.4.0 for CXX1X flag use... no
checking for cat... /usr/bin/cat
checking for local ICUDT_DIR... icu69/data
checking for gcc... gcc -m64 -std=gnu99
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc -m64 -std=gnu99 accepts -g... yes
checking for gcc -m64 -std=gnu99 option to accept ISO C89... none needed
checking how to run the C preprocessor... gcc -m64 -std=gnu99 -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking elf.h usability... yes
checking elf.h presence... yes
checking for elf.h... yes
checking whether we are using the GNU C++ compiler... yes
checking whether g++ -m64 -std=gnu++11 accepts -g... yes
checking whether the C++ compiler supports the long long type... yes
checking whether the compiler implements namespaces... yes
checking whether the compiler supports the Standard Template Library... yes
checking whether std::map is available... yes
checking for pkg-config... /usr/bin/pkg-config
checking with pkg-config for the system ICU4C... 50.2
checking for ICU4C >= 55... no
*** ICU4C 50.2 has been detected
*** Minimal requirements, i.e., ICU4C >= 55, are not met
*** Trying with 'standard' fallback flags
checking whether an ICU4C-based project can be built... yes
checking programmatically for sufficient U_ICU_VERSION_MAJOR_NUM... no
*** This version of ICU4C cannot be used.
*** Using the ICU 69 bundle.
checking whether we may compile src/icu69/common/putil.cpp... yes
checking whether we may compile src/icu69/i18n/number_affixutils.cpp... yes
checking whether alignof(std::max_align_t) is available... no
checking whether alignof(::max_align_t) is available... yes
checking whether the ICU data library can be downloaded... downloading the ICU data library (icudt)
output path: icu69/data/icu4c-69_1-data-bin-l.zip
trying URL 'https://raw.githubusercontent.com/gagolews/stringi/master/src/icu69/data/icu4c-69_1-data-bin-l.zip'
Error in download.file(paste(href, fname, sep = ""), icudtzipfname, mode = "wb"): cannot open URL 'https://raw.githubusercontent.com/gagolews/stringi/master/src/icu69/data/icu4c-69_1-data-bin-l.zip'

trying URL 'http://raw.githubusercontent.com/gagolews/stringi/master/src/icu69/data/icu4c-69_1-data-bin-l.zip'
Error in download.file(paste(href, fname, sep = ""), icudtzipfname, mode = "wb"): cannot open URL 'http://raw.githubusercontent.com/gagolews/stringi/master/src/icu69/data/icu4c-69_1-data-bin-l.zip'

icudt download failed
Error: Stopping on error
In addition: Warning messages:
1: In download.file(paste(href, fname, sep = ""), icudtzipfname, mode = "wb") :
  URL 'https://raw.githubusercontent.com/gagolews/stringi/master/src/icu69/data/icu4c-69_1-data-bin-l.zip': status was 'Couldn't connect to server'
2: In download.file(paste(href, fname, sep = ""), icudtzipfname, mode = "wb") :
  URL 'http://raw.githubusercontent.com/gagolews/stringi/master/src/icu69/data/icu4c-69_1-data-bin-l.zip': status was 'Couldn't connect to server'
Execution halted
*** *********************************************************************
*** stringi cannot be built.
*** Failed to download the ICU data library (icudt). Stopping now.
*** For build environments that have no internet access,
*** see the INSTALL file for a workaround.
*** *********************************************************************
ERROR: configuration failed for package ‘stringi’
* removing ‘/home/kobe/R/x86_64-redhat-linux-gnu-library/3.6/stringi’
* restoring previous ‘/home/kobe/R/x86_64-redhat-linux-gnu-library/3.6/stringi’

The downloaded source packages are in
	‘/tmp/RtmpbSMUjA/downloaded_packages’
Warning messages:
1: package(s) not installed when version(s) same as current; use `force = TRUE` to
  re-install: 'BSgenome.Hsapiens.UCSC.hg19' 
2: In install.packages(update[instlib == l, "Package"], l, contriburl = contriburl,  :
  installation of package ‘stringi’ had non-zero exit status

**Comment by asmlgkj** [comment]
> Can you send the whole output generated during a call to `BiocManager::install("BSgenome.Hsapiens.UCSC.hg19")` ?

Thanks for you kind help

**Comment by gagolews** [comment]
Just choose NOT to update stringi during install.

**Comment by gagolews** [comment]
Or follow the instructions from https://stringi.gagolewski.com/install.html#icu-data-library-and-no-internet-access as there was recently an update.

**Comment by asmlgkj** [comment]
this time stop update works, it does not work just now. thanks a lot.https://raw.githubusercontent.com/gagolews/stringi/master/src/icu69/data/icu4c-69_1-data-bin-l.zip  this link now opens ok in windows, but fails in linux still, is it because og my internet on linux?

Thanks a lot

**Comment by gagolews** [comment]
Probably because you are behind some proxy? 

Anyway, glad it's fixed now.

**Comment by asmlgkj** [comment]
> Probably because you are behind some proxy?
> 
> Anyway, glad it's fixed now.

thanks a lot.
