### ISSUE TITLE
unable to install stringi in cluster 

### ISSUE THREAD

**Issue by MixxyhLeon** [gagolews/stringi#472]
I used my Dept. Cluster to run R and managed to download the _stringi_ package but failed.
I have checked out the [guideline](https://stringi.gagolewski.com/install.html) and issues #452 and tried to fix it step by step. 
Still, it didn't work; I have no ideas about how to fix the emerging errors at this moment. Much appreciate any helpful information in advance! Below are the ./configure and the file of config.log.

I used my own installed R in /home/ directory of my account based on _Conda_ environment.

### R sessionInfo(): 
R version 4.0.5 (2021-03-31)
Platform: x86_64-conda-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS/LAPACK: /home/yanhamiao2/anaconda3/envs/rrr/lib/libopenblasp-r0.3.17.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.0.5 tools_4.0.5   

### config.log
[config.log](https://github.com/gagolews/stringi/files/8041917/config.log)

### ./configure
checking for R_HOME... /share/apps/R-3.0.1/lib64/R
checking for R... /share/apps/R-3.0.1/lib64/R/bin/R
checking for endianness... /share/apps/R-3.0.1/lib64/R/bin/exec/R: error while loading shared libraries: libreadline.so.5: cannot open shared object file: No such file or directory
big
checking for R >= 3.1.0 for C++11 use... /share/apps/R-3.0.1/lib64/R/bin/exec/R: error while loading shared libraries: libreadline.so.5: cannot open shared object file: No such file or directory
no
*** Support for R < 3.1 is deprecated.
*** Whatever follows, comes with no warranty.
*** Disabling C++11 use.
checking for R < 3.4.0 for CXX1X flag use... /share/apps/R-3.0.1/lib64/R/bin/exec/R: error while loading shared libraries: libreadline.so.5: cannot open shared object file: No such file or directory
yes
checking for cat... /bin/cat
checking for local ICUDT_DIR... icu55/data
checking for gcc... gcc -std=gnu99
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc -std=gnu99 accepts -g... yes
checking for gcc -std=gnu99 option to accept ISO C89... none needed
checking how to run the C preprocessor... cpp
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking elf.h usability... yes
checking elf.h presence... yes
checking for elf.h... yes
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking whether the C++ compiler supports the long long type... yes
checking whether the compiler implements namespaces... yes
checking whether the compiler supports the Standard Template Library... yes
checking whether std::map is available... yes
checking for pkg-config... /bin/pkg-config
checking with pkg-config for the system ICU4C... 50.1.2
checking for ICU4C >= 55... no
*** ICU4C 50.1.2 has been detected
*** Minimal requirements, i.e., ICU4C >= 55, are not met
*** Trying with 'standard' fallback flags
checking whether an ICU4C-based project can be built... yes
checking programmatically for sufficient U_ICU_VERSION_MAJOR_NUM... no
*** This version of ICU4C cannot be used.
*** Using the ICU 55 bundle.
checking whether we may compile src/icu55/common/umapfile.c... yes
checking whether we may compile src/icu55/common/putil.cpp... yes
checking whether the ICU data library can be downloaded... /share/apps/R-3.0.1/lib64/R/bin/exec/R: error while loading shared libraries: libreadline.so.5: cannot open shared object file: No such file or directory
*** *********************************************************************
*** stringi cannot be built.
*** Failed to download the ICU data library (icudt). Stopping now.
*** For build environments that have no internet access,
*** see the INSTALL file for a workaround.
*** *********************************************************************

**Comment by gagolews** [comment]
I see ` /share/apps/R-3.0.1/lib64/R/bin/exec/R: error while loading shared libraries: libreadline.so.5: cannot open shared object file`

Also, this in `config.log`:

```
/home/yanhamiao2/anaconda3/envs/rrr/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: /home/yanhamiao2/anaconda3/envs/rrr/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/lib/../lib/libstdc++.so: undefined reference to `aligned_alloc@GLIBC_2.16'
/home/yanhamiao2/anaconda3/envs/rrr/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: /home/yanhamiao2/anaconda3/envs/rrr/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/lib/../lib/libstdc++.so: undefined reference to `clock_gettime@GLIBC_2.17'
```

Are you able to compile other packages at all?

Also, this is a quite outdated version of R, I suggest an update. (to anaconda?)

**Comment by MixxyhLeon** [comment]
Thanks for the prompt reply. I'm actually a newcomer to R. some R packages can be downloaded and loaded successfully, but others not, like _tidyverse_.
e.g.,
```
attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets  methods  
[8] base     

other attached packages:
[1] readr_2.1.1   ggplot2_3.3.5

loaded via a namespace (and not attached):
 [1] magrittr_2.0.2   hms_1.1.1        tidyselect_1.1.1 munsell_0.5.0   
 [5] colorspace_2.0-2 R6_2.5.1         rlang_1.0.0      fansi_1.0.2     
 [9] dplyr_1.0.7      grid_4.0.5       gtable_0.3.0     utf8_1.2.2      
[13] cli_3.1.1        DBI_1.1.2        withr_2.4.3      ellipsis_0.3.2  
[17] assertthat_0.2.1 tibble_3.1.6     lifecycle_1.0.1  crayon_1.4.2    
[21] tzdb_0.2.0       purrr_0.3.4      vctrs_0.3.8      glue_1.6.1      
[25] compiler_4.0.5   pillar_1.6.5     generics_0.1.1   scales_1.1.1    
[29] pkgconfig_2.0.3 
```

I just feel confused about this line, `/share/apps/R-3.0.1/lib64/R/bin/exec/R: error while loading shared libraries: libreadline.so.5: cannot open shared object file`

The root user has downloaded several R versions for access; why was the oldest one  _R-3.0.1_ used? Was it the default version? Or whether it means that the _libreadline.so.5_ exists, but I can not access it as I don't have root authority.
```
(base) -bash-4.2$ ls /share/apps/ | grep R
R-3.0.1
R-3.3.1_ifort
R-4.1.2
RPMs
```

Thanks.

**Comment by MixxyhLeon** [comment]
Okay, thank you!
