### ISSUE TITLE
No warning for invalid locales

### ISSUE THREAD

**Issue by hadley** [gagolews/stringi#476]
``` r
stringi::stri_sort("a", opts_collator = stringi::stri_opts_collator(locale = "doesntexist"))
#> [1] "a"
```

<sup>Created on 2022-04-14 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Originally filed in https://github.com/tidyverse/stringr/issues/440

**Comment by gagolews** [comment]
As far as I remember, ICU is quite tolerant with regards to what it accepts as a valid locale id and tries hard to fall back to something closely approximating what the user needs (as per https://unicode-org.github.io/icu/userguide/locale/ and https://unicode-org.github.io/icu/userguide/locale/resources.html)

It might be a good idea to implement what you request  based on what https://unicode-org.github.io/icu-docs/apidoc/released/icu4c/classicu_1_1Collator.html says about `static Collator* icu::Collator::createInstance ( const Locale & loc, UErrorCode &  err )`

> *The UErrorCode& err parameter is used to return status information to the user. To check whether the construction succeeded or not, you should check the value of [U_SUCCESS(err)](https://unicode-org.github.io/icu-docs/apidoc/released/icu4c/utypes_8h.html#a527f2c69e6b2e3b2c53ad8a99fb36711). If you wish more detailed information, you can check for informational error results which still indicate success. U_USING_FALLBACK_ERROR indicates that a fall back locale was used. For example, 'de_CH' was requested, but nothing was found there, so 'de' was used. U_USING_DEFAULT_ERROR indicates that the default locale data was used; neither the requested locale nor any of its fall back locales could be found.*

**Comment by gagolews** [comment]
So the above would be an instance of `U_USING_DEFAULT_ERROR`

**Comment by hadley** [comment]
I wonder if it's worth warning/messagining on `U_USING_FALLBACK_ERROR` and erroring on `U_USING_DEFAULT_ERROR`?

**Comment by gagolews** [comment]
`U_USING_DEFAULT_WARNING` when requesting a Collator (and only when; other settings led to too frequent warnings) now triggers a warning:

```r
> stringi::stri_sort(c("a", "c", "ch", "h", "ą"), locale="C")
[1] "a"  "ą"  "c"  "ch" "h" 
> stringi::stri_sort(c("a", "c", "ch", "h", "ą"), locale="en")
[1] "a"  "ą"  "c"  "ch" "h" 
> stringi::stri_sort(c("a", "c", "ch", "h", "ą"), locale="pl")
[1] "a"  "ą"  "c"  "ch" "h" 
> stringi::stri_sort(c("a", "c", "ch", "h", "ą"), locale="sk")
[1] "a"  "ą"  "c"  "h"  "ch"
> stringi::stri_sort(c("a", "c", "ch", "h", "ą"), locale="unknown")
[1] "a"  "ą"  "c"  "ch" "h" 
Warning message:
In stringi::stri_sort(c("a", "c", "ch", "h", "ą"), locale = "unknown") :
  A resource bundle lookup returned a result either from the root or the default locale.
```

**Comment by hadley** [comment]
Thanks!

**Comment by pietervreeburg** [comment]
When I try to set my locale to "nl" I get a warning in the newest version of stringr/stringi. Is this expectd behaviour?

``` r
library(stringr)
x <- "TEXT IN CAPS"
str_to_title(x, locale = "nl")
#> Warning in stri_trans_totitle(string, opts_brkiter = stri_opts_brkiter(locale =
#> locale)): A resource bundle lookup returned a result either from the root or
#> the default locale.
#> [1] "Text In Caps"
```

<sup>Created on 2025-01-24 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by gagolews** [comment]
This means there are no language-specific for this language. Actually, in the case of translations, very few extra locales are supported. 

This is normal.
