### ISSUE TITLE
Special UTF Code Points: Enhancements to UTF

### ISSUE THREAD

**Issue by discoleo** [gagolews/stringi#478]
I have some suggestions to improve the UTF standard. I am not familiar with the Standards Committee; although I hope that the stringi developers have better contacts in the field. The proposals are not directly linked to the R package stringi either - but could be useful if integrated into UTF.

## Special Code-Points for:
1.) Parenthesized expression vs Numbered List
2.) Dot as sentence delimiter vs Word abbreviation

Implementing UTF code points with semantic meaning would greatly improve the automatic processing of textual information. Many text articles can be curated, even if the initial document did not use the specialized UTF codes; researchers (e.g. in text mining) could benefit afterwards from the specialized UTF codes.

### 1.) Parenthesized expression vs Numbered List
- the code-points have the same glyph, but the semantic meaning can be differentiated based on the different code points;

1.a.) Parenthesized expression:
- "a*(b+c)" a real mathematical expression, or
- "(some text)"

1.b.) Numbered list
- Examples: "1)" or "1.)", or "a)", or "(a)" (this one is tricky but can use the numbered-list code points), etc.

1.c.) Parenthesized References
- Examples: "(Ref 1)" or "(1)",  or "(a)" - used as a reference - could use a specialized code-point as well; or it may reuse the code-points described in (1.a.);

#### Some analysis:
- I have extracted 1200 abstracts from Pubmed and analysed the matching of parenthesis in these abstracts;
- a total of 1094 abstracts contained at least 1 parenthesis;
- 35 of these abstracts contained a mismatch;
- 22 were true mismatch errors (with a total of 31 such errors), while the remaining 13 contained numbered lists;

A csv file with proposed corrections is uploaded on Github, see:
https://github.com/discoleo/R/tree/master/TextMining/Pubmed
```
# R code to count the 22 true mismatches
tmp = read.csv("Pubmed.Abstracts.Corrections.Parenthesis.csv")
length(unique(tmp$PMID))
```

The processing code is detailed in:
TextMining.Examples.R;

The initial xml file containing the Pubmed articles can be downloaded from Pubmed using the code detailed in:
Pubmed.Examples.R;
(the content may differ slightly as I set a limit to 1200 articles)

### 2.) Dot as Sentence Delimiter vs Word Abbreviation

Differentiating the termination of a sentence vs an abbreviation can be a hard task in NLP (natural language processing). Specialized UTF code points would greatly simplify this task.

Existing documents can be curated and modified to use the improved code points. Researchers could then benefit in the future from the additional value of these semantic code points.

The decimal separator is a third semantic variant: a locale-independent code-point may be a good solution as well.

**Comment by gagolews** [comment]
The above is quite out of scope here, but I recommend you start a discussion on one of the Unicode or ICU mailing lists -> https://icu.unicode.org/contacts or https://icu.unicode.org/bugs or https://www.unicode.org/consortium/distlist.html

Note that there are actually some enclosed alphanumerics in the U+2460-U+24FF block, see https://en.wikipedia.org/wiki/Enclosed_Alphanumerics, but that they are rarely used in practice (e.g., in published) is a different story...

As far as the full stop is concerned, sometimes these can be distinguished by analysing the spacing after the dot, e.g., in English spacing (https://en.wikipedia.org/wiki/Sentence_spacing) there is a wide (double) space between sentences whereas after an abbreviation often a non-breaking space follows...

But again, having separate code points vs making the use thereof a popular practice is a separate issue. Worth discussing though, still.

Good luck!
