### ISSUE TITLE
neither conda R version nor base R installed stringi successfully

### ISSUE THREAD

**Issue by asmlgkj** [gagolews/stringi#481]
Dear professor,
Thanks a lot for this popular package. I knoe the error I input here other has reported, but none of that could solve mine.

centos 7

I installed conda R4.2.0, and then enter into R by input R, then run command install.packages('stringi'), the error as following picture shows

![image](https://user-images.githubusercontent.com/50854682/175772933-305cbb69-a2a4-4687-bfe8-d4c6af19df6c.png)

<br>
<br>
I also has R not installed by conda, but just installed directly,
![image](https://user-images.githubusercontent.com/50854682/175772976-29f1822d-2cfa-4586-b2e4-b416c66df96c.png)

<br>
can you have a look, thanks a lot

**Comment by gagolews** [comment]
Have you tried:

conda install -c r r-stringi

*Sent from my mobile device. Please excuse my brevity.*

**Comment by asmlgkj** [comment]
Thanks a lot for your kind help, I did that past. but errors the same
> library(srtingi)
Error in library(srtingi) : there is no package called ‘srtingi’

#also in the base R, I also can not install stringi

**Comment by gagolews** [comment]
> library(srtingi)
> Error in library(srtingi) : there is no package called ‘srtingi’
> 
> 
> 

Hmmm… there’s a typo above..

**Comment by asmlgkj** [comment]
oh sorry, a typo error.
is there a method to install stringi in base R instead of conda verserion,

**Comment by gagolews** [comment]
Did you try the solutions from #452 ?

**Comment by gagolews** [comment]
Also #296 ?

**Comment by asmlgkj** [comment]
@gagolews  thanks a lot, I hve tried that, but still failed
![image](https://user-images.githubusercontent.com/50854682/176093169-7fc332a1-0758-45cb-8a73-1e09e78a2501.png)
<br>
<br>
![image](https://user-images.githubusercontent.com/50854682/176093444-aa455a0a-cdb7-4213-8e95-9ae0d083b224.png)

**Comment by gagolews** [comment]
Let's give it another try: https://stringi.gagolewski.com/install.html -> *ICU Data Library and No Internet Access* and *C++11 Issues*


```
wget https://github.com/gagolews/stringi/archive/master.zip -O stringi.zip
unzip stringi.zip
sed -i '/\/icu..\/data/d' stringi-master/.Rbuildignore
R CMD build stringi-master
```

and then in R

```
install.packages("stringi_x.y.z.tar.gz", repos=NULL, configure.args="--with-extra-cxxflags='-std=c++11'") # replace with file name
```

or

```
install.packages("stringi_x.y.z.tar.gz", repos=NULL, configure.args="--disable-cxx11") # replace with file name
```

**Comment by asmlgkj** [comment]
@gagolews 
thanks  a lot for your continuous help, finally works
