### ISSUE TITLE
DOI not found: https://dx.doi.org/10.18637/jss.v103.i02

### ISSUE THREAD

**Issue by KyleHaynes** [gagolews/stringi#483]
Was interested in reading this, however the URL indicates it's not found?

URL: https://dx.doi.org/10.18637/jss.v103.i02

Current output:

![image](https://user-images.githubusercontent.com/5267027/177471263-f8225bc4-a06a-4757-aea4-8d1f3e6833af.png)

**Comment by gagolews** [comment]
It will soon become available – the article is in press.

In the meanwhile, take a look at https://stringi.gagolewski.com/, where I provided a browser-friendly version of this article (the first  10 or so sections).

**Comment by KyleHaynes** [comment]
Thanks and will do.
