### ISSUE TITLE
stri_split_boundaries() returns slightly different tokens when the ICU rules are supplied

### ISSUE THREAD

**Issue by koheiw** [gagolews/stringi#489]
We are trying to switch quanteda's tokenizer to custom RBBI in the upcoming version (https://github.com/quanteda/quanteda/pull/2216). We noticed that the `stri_split_boundaries()` returns slightly different tokens when we supply the ICU rules.  It is probably an edge case, but I wonder where the difference is coming from.

``` r
require(stringi)
#> Loading required package: stringi
word <- readLines("https://raw.githubusercontent.com/unicode-org/icu/main/icu4c/source/data/brkitr/rules/word.txt") 
txt <- "übër u\u0308be\u0308r \u0308ubër"

stri_split_boundaries(txt, type = paste0(word, collapse = "\n"))
#> [[1]]
#> [1] "übër" " "    "übër" " ̈"    "ubër"
stri_split_boundaries(txt)
#> [[1]]
#> [1] "übër " "übër " "̈ubër"
```

<sup>Created on 2023-03-20 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by gagolews** [comment]
They are the same, if you set the `type` explicitly:

```r
stri_split_boundaries(txt, type="word")
## [[1]]
## [1] "übër" " "    "übër" " ̈"    "ubër"
```

**Comment by koheiw** [comment]
Sorry that I forgot about the argument! Thank you very much.

**Comment by koheiw** [comment]
It was my bad but I think ICU rules has been updated about colons and at marks. Great to see the rules are still evolving.

https://github.com/unicode-org/icu/commit/49d192fefe09fcc38547203487cf4e63d2dad61f

``` r
require(stringi)
#> Loading required package: stringi
word <- readLines("https://raw.githubusercontent.com/unicode-org/icu/main/icu4c/source/data/brkitr/rules/word.txt") 
txt <- "aaa@bbb @cc"
stri_split_boundaries(txt, type = paste0(word, collapse = "\n"))
#> [[1]]
#> [1] "aaa@bbb" " "       "@cc"
stri_split_boundaries(txt, type = "word")
#> [[1]]
#> [1] "aaa" "@"   "bbb" " "   "@"   "cc"
```

<sup>Created on 2023-03-20 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
