### ISSUE TITLE
[Feature] Convert String to Code Points

### ISSUE THREAD

**Issue by discoleo** [gagolews/stringi#490]
# Convert String to Code Points
- issue solved: function already exists;
- issue left open because the documentation may need some improvement;

I want to encode various strings using unicode code points. I would like to avoid the actual characters and instead use the Unicode code points in the program. I did not find any function to escape the unicode characters using code points, e.g.:
	charToRaw("ându")
	# c3 a2 6e 64 75

But "C3 A2" is NOT the code point to use with "\u...". Manually searching the web for the unicode characters is quite time consuming.

## Solution

I found in the meantime the solution:
> stringi::stri_escape_unicode("ându")

Got somehow distracted by the *transform* functions.

**Comment by gagolews** [comment]
`stringi::stri_enc_toutf32` might be what you are looking for.

**Comment by discoleo** [comment]
Note:
- the functionality already exists:
> stringi::stri_escape_unicode("ându")

However, the documentation may need some improvement. When I searched the documentation, I somehow skipped over the function **stri_escape_unicode** and landed at the *str_trans* group of functions.

I do not have an optimal wording: it may be reformulated to indicate explicitly that the result is a string formed by ASCII codes.
> "Generates an ASCII string where all non-printable ASCII codes and the remaining Unicode code points are converted to ..."
