### ISSUE TITLE
Unable to install stringi in R 4.3

### ISSUE THREAD

**Issue by LittleTealeaf** [gagolews/stringi#492]
I guess I've recently updated to R 4.3 (found that out today when I tried running some code), so apparently I need to reinstall all of my packages. In doing so, I tried reinstalling tidyverse only to stumble into the inability to install stringi

Trying to just install stringi returns the following error:
```
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for ‘stringi’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/home/tealeaf/R/x86_64-pc-linux-gnu-library/4.3/00LOCK-stringi/00new/stringi/libs/stringi.so':
  libicui18n.so.72: cannot open shared object file: No such file or directory
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/home/tealeaf/R/x86_64-pc-linux-gnu-library/4.3/stringi’

The downloaded source packages are in
	‘/tmp/RtmpR6oZSB/downloaded_packages’
Warning message:
In install.packages("stringi") :
  installation of package ‘stringi’ had non-zero exit status
```

I tried looking up the documentation and other information, but found nothing related to this error. Any suggestions / fixes?

**Comment by gagolews** [comment]
Try doing this directly from the terminal maybe?

1. Start `R`
2. Run `install.packages("stringi")`

?

**Comment by LittleTealeaf** [comment]
The screenshot I provided was straight from the terminal, I tried it both in dataspell and just in the terminal and got the same errors

**Comment by LittleTealeaf** [comment]
Just did a dummy-check and tried it again in the terminal. This is what I got

![image](https://user-images.githubusercontent.com/35083315/234018054-8d3e95ca-7438-41dc-8e7d-9a2303207e4a.png)

**Comment by gagolews** [comment]
I guess you should either update ICU on your system (I don't know which system are you on, so can't give you more details) or use `install.packages("stringi", configure.args="--disable-pkg-config")`. HTH

**Comment by LittleTealeaf** [comment]
So using the `--disable-pkg-config` was able to get it installed, but I'm still having issues with other libraries, so I want to make sure that it isn't the same issue.

I'm currently running Pop_os! 22.04, and it seems I have ICU version 72.1 currently on my system. I'm trying to find out how to update that, but things are almost looking like its a "just use R version 4.2 for now" angle.

**Comment by gagolews** [comment]
It's a Ubuntu flavour, so maybe `sudo apt install libicu-dev` ?

**Comment by LittleTealeaf** [comment]
Yup, states it's already installed on the latest version (version 70.1-2)

**Comment by MislavSag** [comment]
Just to confirm I have the similar error:
```
[jmaric@padobran mlr3-supek]$ apptainer run image.sif test.R
Error: package or namespace load failed for ‘batchtools’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/home/jmaric/Rlibs/stringi/libs/stringi.so':
  libicui18n.so.60: cannot open shared object file: No such file or directory
In addition: Warning message:
package ‘batchtools’ was built under R version 4.3.1
Execution halted

```
Linux info:
```
NAME="Rocky Linux"
VERSION="8.8 (Green Obsidian)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Rocky Linux 8.8 (Green Obsidian)"
ANSI_COLOR="0;32"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:rocky:rocky:8:GA"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
SUPPORT_END="2029-05-31"
ROCKY_SUPPORT_PRODUCT="Rocky-Linux-8"
ROCKY_SUPPORT_PRODUCT_VERSION="8.8"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.8"

```

**Comment by gagolews** [comment]
Could you try installing stringi via `install.packages("stringi", configure.args="--disable-pkg-config")` as per https://stringi.gagolewski.com/install.html ?

**Comment by MislavSag** [comment]
It seems thare were some problems with R libpaths. I have created R lib path for the user and inside container.  I have deleted one T lib path and now works. Seems it is not directly connected with stringi, at least in my case.
