### ISSUE TITLE
install issue, no internet

### ISSUE THREAD

**Issue by aepva** [gagolews/stringi#493]
Attempted to install stringi_1.7.12.tar.gz on a Windows10 machine with no internet access; managed to acquire a suitable ICUdt.zip file and put it in a local directory; as directed in the INSTALL readme, used configure.vars to identify the location of the zip file but no luck. The installer attempted to reach GitHub anyway and the install failed.

Also used the suggested configure.args  = "--disable-pkg-config" with no success; for all attempts using install.packages, repos = NULL and type = "source". No matter what options I tried, the installer still tried to download the zip file from GitHub and failed. 

Also tried with stringi_1.7.8.tar.gz with the same results.  Due to environment restrictions I am not able to modify Rbuildignore in a dev version of stringi to rebuild the package as suggested in the INSTALL readme and StackOverflow. 

All attempts were from within RStudio with R 4.2.1 installed; I forgot to write down the Studio version but the R version is definitely "Funny Looking Kid" (4.2.1)

**Comment by gagolews** [comment]
If you are on Windows, I recommend you try installing the binary version (`install.packages("stringi")`) from CRAN (https://cran.r-project.org/web/packages/stringi/index.html)...

**Comment by gagolews** [comment]
This will be fixed in the upcoming release (>=1.8.0)
