### ISSUE TITLE
Calling stringi C functions without Rcpp

### ISSUE THREAD

**Issue by hongyuanjia** [gagolews/stringi#499]
This related to #88. This may sound like a silly question and, but how could I use the stringi C functions without using Rcpp? Thanks!

**Comment by hongyuanjia** [comment]
Found a good reference to start with: https://github.com/rorynolan/strex/blob/master/src/detect.c Close the issue now.

Btw, I would like to suggest removing default arguments in `stringi.h` so that it can be directly used in C code. Thanks for this amazing package.

**Comment by gagolews** [comment]
Thanks for the suggestion!
