### ISSUE TITLE
Feature request: stri_replace_*_regex pattern is a column name, replacement a $1 

### ISSUE THREAD

**Issue by AlbanSagouis** [gagolews/stringi#507]
I'm trying to replace substrings in a column with patterns found in another column and reusing this pattern in the replacement argument.
In other words, I have strings such as "Amnicolalimosus" in column `species` and I want to use the patterns in column `genus`, such as "Amnicola"", to split genus and species names "Amnicola" spp".

``` r
taxo <- data.frame(species = c("Amnicolalimosus", "Ablabesmyiaspp"),
                   genus = c("Amnicola", "Ablabesmyia"))
# Does this make sense?
stringi::stri_replace_all_regex(str = taxo$species, pattern = taxo$genus, replacement = "$1 ")
```

**Comment by gagolews** [comment]
Could you please indicate the exact output you would like to get in the above example?

A more sophisticated example could also be helpful.

**Comment by AlbanSagouis** [comment]
Of course, the desired output would be obtained with these two steps:
``` r
taxo <- data.frame(species = c("Amnicolalimosus", "Crematogasteremeryana", "Ablabesmyiaspp"),
                   genus = c("Amnicola", "Crematogaster", "Ablabesmyia"))

stringi::stri_replace_all_fixed(str = taxo$species, pattern = taxo$genus, replacement = "$1 ") |> 
   stringi::stri_replace_all_fixed(pattern = "$1", replacement = taxo$genus)
[1] "Amnicola limosus" "Crematogaster emeryana" "Ablabesmyia spp" 
```

**Comment by gagolews** [comment]
I think the `vectorise_all` argument is what you are after:

```r
stringi::stri_replace_all_fixed(taxo$species, taxo$genus, taxo$species %s+% " ", vectorise_all=FALSE)
[1] "Amnicolalimosus limosus"        "Crematogasteremeryana emeryana" "Ablabesmyiaspp spp" 
```

**Comment by AlbanSagouis** [comment]
Oh that looks interesting, I played a little with `vectorise_all`. Here I'm especially curious about `%s+% ` but it does not work on my system: 
``` r
R> stringi::stri_replace_all_fixed(taxo$species, taxo$genus, taxo$species %s+% " ", vectorise_all=FALSE)
Error in taxo$species %s+% " " : could not find function "%s+%"
```

**Comment by gagolews** [comment]
Please call library(“stringi”) first.HTH*Sent from my mobile device. Please excuse my brevity.*On 25 Apr 2024, at 18:22, AlbanSagouis ***@***.***> wrote:﻿
Oh that looks interesting, I played a little with vectorise_all. Here I'm especially curious about %s+%  but it does not work on my system:
R> stringi::stri_replace_all_fixed(taxo$species, taxo$genus, taxo$species %s+% " ", vectorise_all=FALSE)
Error in taxo$species %s+% " " : could not find function "%s+%"

**Comment by AlbanSagouis** [comment]
Thanks a lot,
``` r
stringi::stri_replace_all_fixed(
   str = taxo$species, 
   pattern = taxo$genus,
   replacement = taxo$genus %s+% " ",
   vectorise_all = FALSE)
```
Does exactly what I need, thank you.
