### ISSUE TITLE
Compilation errors on R-devel

### ISSUE THREAD

**Issue by krlmlr** [gagolews/stringi#508]
Currently, stringi fais to build with R-devel. This leads to failing builds in CI/CD pipelines on GitHub Actions.

Is there a workaround? Thanks!

https://www.r-project.org/nosvn/R.check/r-devel-windows-x86_64/stringi-00install.html

**Comment by gagolews** [comment]
Thanks for the report, I'll take a look at what happened on the Windows R-devel side this week.

**Comment by gagolews** [comment]
@jeroen Any idea what could have caused the build failure?

**Comment by jeroen** [comment]
No I don't see the problem. Maybe @kalibera has changed something in the toolchain or default build flags on R-4.5?
