### ISSUE TITLE
stri_write_lines, append mode

### ISSUE THREAD

**Issue by bartoszukm** [gagolews/stringi#82]
Can you add an "append" mode to stri_write_lines function? I have a project, where I concatenate many small files (~5kB) into one big file(~100MB). I have to read this big file for every single small file, so I can add some lines and write it again as whole file. After some iterations, this process get slower and slower, because I have to read bigger and bigger file to memory (stri_read_lines) every single time.

**Comment by gagolews** [comment]
done in #187 : stri_read_lines now supports connection objects
